### PR TITLE
Formatting: remove unused variables

### PR DESCRIPTION
**Pull request by Glutexo**
Fixed the F841 Flake8 rule complaning about unused variables.

This is a part of the first step to fix all the formatting. See #189, #335 and #331.

### CODE REVIEW

**Comment by diegorafrh** [comment]
They are both the same https://github.com/RedHatInsights/insights-host-inventory/pull/341 - it was  intentional?

**Comment by Glutexo** [comment]
It wasn’t. I messed up with push targets. Fixed now. Thanks for pointing out!

**Comment by Glutexo** [comment]
Rebased on the [current](https://github.com/RedHatInsights/insights-host-inventory/tree/fdc1251bd7ee6ec72cd47d387938e4c8c7b7b64f) [_master_](https://github.com/RedHatInsights/insights-host-inventory).

**Comment by Glutexo** [comment]
This has been actually merged without an explicit approval. But I suppose that @dehort took a look before merging.

**Pull request merged**
