### PR TITLE
Migration to add org_id column, and its associated index to hosts/

### PR DESCRIPTION
**Pull request by roliveri**
# Overview

Add migration to add org_id column, and its associated index to the hosts table.

This PR is being created to address [ESSNTL-2522](https://issues.redhat.com/browse/ESSNTL-2522).

## PR Checklist

- [ ] Keep PR title short, ideally under 72 characters
- [ ] Descriptive comments provided in complex code blocks
- [ ] Tests: validate optimal/expected output
- [ ] Tests: validate exceptions and failure scenarios
- [ ] Tests: edge cases
- [ ] Recovers or fails gracefully during potential resource outages (e.g. DB, Kafka)
- [ ] Documentation, if this PR changes the way other services interact with host inventory
- [ ] Links to related PRs

## Secure Coding Practices Documentation Reference

You can find documentation on this checklist [here](https://github.com/RedHatInsights/secure-coding-checklist).

## Secure Coding Checklist

- [ ] Input Validation
- [ ] Output Encoding
- [ ] Authentication and Password Management
- [ ] Session Management
- [ ] Access Control
- [ ] Cryptographic Practices
- [ ] Error Handling and Logging
- [ ] Data Protection
- [ ] Communication Security
- [ ] System Configuration
- [ ] Database Security
- [ ] File Management
- [ ] Memory Management
- [ ] General Coding Practices

### CODE REVIEW

**Comment by roliveri** [comment]
Not sure what the length of the column should be. The account column is currently 10, but I'm not sure if the org_id has a well defined format, to I made it 255 to be safe.

**Review by kruai — APPROVED** [review]

**Review by thearifismail — APPROVED** [review]
LGTM

**Review by kruai — CHANGES_REQUESTED** [review]
I actually just learned that the [official Postgres guidance](https://wiki.postgresql.org/wiki/Don't_Do_This#Text_storage) is to not use char(n)/strings of fixed length. They actually recommend Text, but we can use a CHECK constraint to verify that they're not longer than 36 chars. IDK how to do that in SQLAlchemy off the top of my head though

**Comment by thearifismail** [comment]
I guess 
```
op.add_column("hosts", sa.Column("org_id", sa.String(length=36), nullable=True))
``` 
should be replaced by 
```
op.add_column("hosts", sa.Column("org_id", UUID, nullable=True))
```
where `UUID` provided by `sqlalchemy.dialects.postgresql`

**Comment by roliveri** [comment]
@thearifismail Is it a UUID? UUID implies a format in addition to length. Validation would fail if the org_id isn't in "UUID" format. Unless we know that the org_id will always be in a recognized UUID format, we probably should just restrict the length.

**Comment by kruai** [comment]
> I guess
> 
> ```
> op.add_column("hosts", sa.Column("org_id", sa.String(length=36), nullable=True))
> ```
> 
> should be replaced by
> 
> ```
> op.add_column("hosts", sa.Column("org_id", UUID, nullable=True))
> ```
> 
> where `UUID` provided by `sqlalchemy.dialects.postgresql`

We don't know that it's going to be UUID format yet; we just know that it will not be longer than a UUID. It could end up being no longer than our current account numbers. We should use a Text type and validate the length using a CHECK constraint

**Comment by roliveri** [comment]
@kruai But we're not using `char(n)` strings. It seems these columns are defined as `varchar(n)` strings in postgres. The document you reference seems to have less of a problem with `varchar(n)` than it does with `char(n)`. In our usage, it seems to me that the larger fields might be more of a problem: `display_name(200)`, `ansibel_host(255)` and `reporter(255)`. However, I think these are ok, as I believe using `text` would be overkill in these instances.

If we do determine that our string definitions should change, should they all be addressed in a followup PR?

**Pull request merged**
