### PR TITLE
Add gpg_pubkey array to system profile

### PR DESCRIPTION
**Pull request by CodeHeeler**
## Overview

This PR is being created to address https://issues.redhat.com/browse/HBISPSC-51 to split out the gpg_pubkey from the rpms in installed_packages or installed_packages_delta and still keep them as a separate fact.

## PR Checklist

- [x] Keep PR title short, ideally under 72 characters
- [ ] Descriptive comments provided in complex code blocks
- [x] Tests: validate optimal/expected output
- [x] Tests: validate exceptions and failure scenarios
- [ ] Tests: edge cases
- [ ] Documentation, if this PR changes the way other services interact with host inventory
- [x] Links to related PRs

## Secure Coding Practices Checklist GitHub Link

- https://github.com/RedHatInsights/secure-coding-checklist

## Secure Coding Checklist

- [x] Input Validation
- [ ] Output Encoding
- [ ] Authentication and Password Management
- [ ] Session Management
- [ ] Access Control
- [ ] Cryptographic Practices
- [ ] Error Handling and Logging
- [ ] Data Protection
- [ ] Communication Security
- [ ] System Configuration
- [ ] Database Security
- [ ] File Management
- [ ] Memory Management
- [ ] General Coding Practices

### CODE REVIEW

**Comment by CodeHeeler** [comment]
You've changed some things since I last added a new system profile fact, I saw that it was handled differently in the model for instance, but is there something new I need to be aware of in place of commenting out the installed_packages here?
https://github.com/RedHatInsights/insights-host-inventory/blob/master/utils/payloads.py#L449-L451

installed_packages_delta isn't even there either, so I left off adding the gpg_pubkeys here, but let me know if I need to add it anyway here or elsewhere.

**Comment by CodeHeeler** [comment]
Related PRs:
https://github.com/RedHatInsights/inventory-schemas/pull/58
https://github.com/RedHatInsights/insights-puptoo/pull/145

**Review by kruai — APPROVED** [review]
LGTM!

**Review by tahmidefaz — APPROVED** [review]
Looks good! Thank you! The test updates are optional in HBI :slightly_smiling_face:

**Pull request merged**
