### PR TITLE
feat(RHINENG-10631): Implement Reaper batch DB operation

### PR DESCRIPTION
**Pull request by kruai**
# Overview

This PR is being created to address [RHINENG-10631](https://issues.redhat.com/browse/RHINENG-10631).
It enables batch operation for Reaper, so it deletes a number of hosts in one commit, and then sends out a message for each one. This should ease the load on the DB during Reaper runs.

## PR Checklist

- [x] Keep PR title short, ideally under 72 characters
- [ ] Descriptive comments provided in complex code blocks
- [ ] Include raw query examples in the PR description, if adding/modifying SQL query
- [ ] Tests: validate optimal/expected output
- [ ] Tests: validate exceptions and failure scenarios
- [ ] Tests: edge cases
- [x] Recovers or fails gracefully during potential resource outages (e.g. DB, Kafka)
- [x] Uses [type hinting](https://docs.python.org/3/library/typing.html), if convenient
- [ ] Documentation, if this PR changes the way other services interact with host inventory
- [ ] Links to related PRs

## Secure Coding Practices Documentation Reference

You can find documentation on this checklist [here](https://github.com/RedHatInsights/secure-coding-checklist).

## Secure Coding Checklist

- [ ] Input Validation
- [ ] Output Encoding
- [ ] Authentication and Password Management
- [ ] Session Management
- [ ] Access Control
- [ ] Cryptographic Practices
- [ ] Error Handling and Logging
- [ ] Data Protection
- [ ] Communication Security
- [ ] System Configuration
- [ ] Database Security
- [ ] File Management
- [ ] Memory Management
- [ ] General Coding Practices

### CODE REVIEW

**Comment by kruai** [comment]
We're hitting that Jenkins bug again, so I'm gonna wait a bit before I retest

**Review by chambridge — APPROVED** [review]
LGTM

**Pull request merged**
