### PR TITLE
Provide a message when 503 or other errors are encountered

### PR DESCRIPTION
**Pull request by thearifismail**
# Overview

This PR is being created to address [this Jira](https://issues.redhat.com/browse/ESSNTL-870).

## PR Checklist

- [x] Keep PR title short, ideally under 72 characters
- [ ] Descriptive comments provided in complex code blocks
- [ ] Tests: validate optimal/expected output
- [ ] Tests: validate exceptions and failure scenarios
- [ ] Tests: edge cases
- [ ] Documentation, if this PR changes the way other services interact with host inventory
- [ ] Links to related PRs

## Secure Coding Practices Documentation Reference

You can find documentation on this checklist [here](https://github.com/RedHatInsights/secure-coding-checklist).

## Secure Coding Checklist

- [ ] Input Validation
- [ ] Output Encoding
- [ ] Authentication and Password Management
- [ ] Session Management
- [ ] Access Control
- [ ] Cryptographic Practices
- [ ] Error Handling and Logging
- [ ] Data Protection
- [ ] Communication Security
- [ ] System Configuration
- [ ] Database Security
- [ ] File Management
- [ ] Memory Management
- [ ] General Coding Practices

### CODE REVIEW

**Comment by ryandillinfelton** [comment]
I think we intentionally keep this vague. We have logs that let us developers know what is wrong, and as far as users are concerned a 500 is a 500, they don't know what xjoin is. I've never personally felt it was a big risk to divulge this kind of info but it seems superfluous and IIRC @jharting had some security concerns about surfacing this kind of information when I proposed something similar in the past. I'll let him keep me honest there though. 

Essentially I don't think think the change is necessary and I believe it might be in conflict with best practices. I'd love to get some alternative opinions though. @kruai ?

**Comment by kruai** [comment]
> I think we intentionally keep this vague. We have logs that let us developers know what is wrong, and as far as users are concerned a 500 is a 500, they don't know what xjoin is. I've never personally felt it was a big risk to divulge this kind of info but it seems superfluous and IIRC @jharting had some security concerns about surfacing this kind of information when I proposed something similar in the past. I'll let him keep me honest there though.
> 
> Essentially I don't think think the change is necessary and I believe it might be in conflict with best practices. I'd love to get some alternative opinions though. @kruai ?

It's very true that for our customers, this information would be useless and/or confusing. This was most likely requested by a developer who wanted more info on failing requests, but I'm unable to tell from the Jira. Who requested this functionality, @thearifismail?

**Comment by ryandillinfelton** [comment]
> > I think we intentionally keep this vague. We have logs that let us developers know what is wrong, and as far as users are concerned a 500 is a 500, they don't know what xjoin is. I've never personally felt it was a big risk to divulge this kind of info but it seems superfluous and IIRC @jharting had some security concerns about surfacing this kind of information when I proposed something similar in the past. I'll let him keep me honest there though.
> > Essentially I don't think think the change is necessary and I believe it might be in conflict with best practices. I'd love to get some alternative opinions though. @kruai ?
> 
> It's very true that for our customers, this information would be useless and/or confusing. This was most likely requested by a developer who wanted more info on failing requests, but I'm unable to tell from the Jira. Who requested this functionality, @thearifismail?

I can see the case from a developer perspective. If we were to enable the more verbose errors only when deployed in a development environment I would be okay with the change.

**Comment by jharting** [comment]
@ryandillinfelton I agree that this kind of information is not relevant to the user. IMO it would be better to instead log the details when these conditions are matched.

**Comment by thearifismail** [comment]
The concern from @ryandillinfelton and @jharting makes sense.  So now logging the missing `xjoin` as an error for debugging by dev and not sending back to the client.

**Review by ryandillinfelton — APPROVED** [review]
Logging approach looks good :+1:

**Review by kruai — APPROVED** [review]
This way works for me too!

**Review by kruai — APPROVED** [review]
Still LGTM

**Review by ryandillinfelton — APPROVED** [review]
Still Gucci :handbag:

**Pull request merged**
