### PR TITLE
updated system_profile filtering section

### PR DESCRIPTION
**Pull request by ryandillinfelton**
## Overview

This PR is being created to address [this Jira](https://issues.redhat.com/browse/RHCLOUD-13266).

I wanted to make sure that we documented the new system_profile fields we can filter on. I noticed that the current docs use fields that actually are not supported so I updated the examples to use supported fields instead. I also added a list of the fields we do support so that it's not ambiguous for users.

## PR Checklist

- [x] Keep PR title short, ideally under 72 characters
- [ ] Descriptive comments provided in complex code blocks
- [ ] Tests: validate optimal/expected output
- [ ] Tests: validate exceptions and failure scenarios
- [ ] Tests: edge cases
- [x] Documentation, if this PR changes the way other services interact with host inventory
- [ ] Links to related PRs

## Secure Coding Practices Checklist GitHub Link

- https://github.com/RedHatInsights/secure-coding-checklist

## Secure Coding Checklist

- [ ] Input Validation
- [ ] Output Encoding
- [ ] Authentication and Password Management
- [ ] Session Management
- [ ] Access Control
- [ ] Cryptographic Practices
- [ ] Error Handling and Logging
- [ ] Data Protection
- [ ] Communication Security
- [ ] System Configuration
- [ ] Database Security
- [ ] File Management
- [ ] Memory Management
- [ ] General Coding Practices

### CODE REVIEW

**Review by tahmidefaz — APPROVED** [review]
Nice! :+1:

**Review by thearifismail — APPROVED** [review]
LGTM

**Review by kruai — CHANGES_REQUESTED** [review]
Looks good, just requesting some minor updates

**Comment by ryandillinfelton** [comment]
@kruai Added your suggestions in!

**Review by tahmidefaz — APPROVED** [review]

**Pull request merged**
