### PR TITLE
chore(RHINENG-5893): Remove unknown staleness; spec cleanup

### PR DESCRIPTION
**Pull request by kruai**
# Overview

This PR is being created to address [RHINENG-5893](https://issues.redhat.com/browse/RHINENG-5893).
Does the following:

- Removes "unknown" from the list of staleness states
- Consolidates `stalenessNoDefaultsParam` and `stalenessParam` (into `stalenessParam`)
- Removes "UnleashToggleOut" because it's not used

## PR Checklist

- [x] Keep PR title short, ideally under 72 characters
- [ ] Descriptive comments provided in complex code blocks
- [ ] Include raw query examples in the PR description, if adding/modifying SQL query
- [ ] Tests: validate optimal/expected output
- [ ] Tests: validate exceptions and failure scenarios
- [ ] Tests: edge cases
- [ ] Recovers or fails gracefully during potential resource outages (e.g. DB, Kafka)
- [ ] Uses [type hinting](https://docs.python.org/3/library/typing.html), if convenient
- [x] Documentation, if this PR changes the way other services interact with host inventory
- [ ] Links to related PRs

## Secure Coding Practices Documentation Reference

You can find documentation on this checklist [here](https://github.com/RedHatInsights/secure-coding-checklist).

## Secure Coding Checklist

- [ ] Input Validation
- [ ] Output Encoding
- [ ] Authentication and Password Management
- [ ] Session Management
- [ ] Access Control
- [ ] Cryptographic Practices
- [ ] Error Handling and Logging
- [ ] Data Protection
- [ ] Communication Security
- [ ] System Configuration
- [ ] Database Security
- [ ] File Management
- [ ] Memory Management
- [ ] General Coding Practices

### CODE REVIEW

**Review by thearifismail — COMMENTED** [review]
I see no reference to `UnleashToggleOut` regarding this PR but being taken out to avoid creating a whole new PR.  Is it so?

Yes, the actual PR LGTM

**Review by fstavela — COMMENTED** [review]
@kruai, Could you please check the Kibana logs to see if no one uses "unknown" staleness? I just want to be double-sure that we don't break anything.

**Comment by kruai** [comment]
> I see no reference to `UnleashToggleOut` regarding this PR but being taken out to avoid creating a whole new PR. Is it so?
> 
> Yes, the actual PR LGTM

Yep - I included it in the description to make it clear that I was removing it. But yeah, it made sense to me to include in this PR where I was already cleaning up the API spec, rather than make another PR for such a tiny change

**Review by thearifismail — APPROVED** [review]

**Comment by kruai** [comment]
Something is still making API requests using `staleness=unknown`, so this is blocked for now. Converted this to a Draft so we don't accidentally merge it.

**Pull request closed without merging**
