### PR TITLE
RHIF-140 Add a `hosts/stats` endpoint for host counts

### PR DESCRIPTION
**Pull request by PaulWay**
# Overview

This PR is being created to address [RHIF-140](https://issues.redhat.com/browse/RHIF-140).

Add a `hosts/stats` endpoint with counts for the Dashboard.

At the moment, the Dashboard makes these three requests of the Inventory API:

- https://console.redhat.com/api/inventory/v1/hosts?registered_with=puptoo&per_page=1
- https://console.redhat.com/api/inventory/v1/hosts?staleness=stale&registered_with=puptoo&per_page=1
- https://console.redhat.com/api/inventory/v1/hosts?staleness=stale_warning&registered_with=puptoo&per_page=1

These in turn make three separate requests to XJoin to get that data.
We'd like to reduce that to one request to:

- https://console.redhat.com/api/inventory/v1/hosts/stats

This would produce data in a JSON object with keys:

  - total: {total of puptoo-registered hosts}
  - stale: {number of stale puptoo-registered hosts}
  - warning: {number of stale-warning puptoo-registered hosts}

The code so far does this in three SQL queries, but hopefully it will be
possible to reduce this to one query.

This is a work in progress.  Still to do:

* Test that this actually works
* Test that produces the right output
* Handle possible DB failures

## PR Checklist

- [X] Keep PR title short, ideally under 72 characters
- [X] Descriptive comments provided in complex code blocks
- [ ] Tests: validate optimal/expected output
- [ ] Tests: validate exceptions and failure scenarios
- [ ] Tests: edge cases
- [ ] Recovers or fails gracefully during potential resource outages (e.g. DB, Kafka)
- [ ] Uses [type hinting](https://docs.python.org/3/library/typing.html), if convenient
- [ ] Documentation, if this PR changes the way other services interact with host inventory
- [ ] Links to related PRs

## Secure Coding Practices Documentation Reference

You can find documentation on this checklist [here](https://github.com/RedHatInsights/secure-coding-checklist).

## Secure Coding Checklist

- [N/A] Input Validation
- [X] Output Encoding
- [X] Authentication and Password Management
- [X] Session Management
- [X] Access Control
- [N/A] Cryptographic Practices
- [ ] Error Handling and Logging
- [X] Data Protection
- [X] Communication Security
- [N/A] System Configuration
- [N/A] Database Security
- [N/A] File Management
- [N/A] Memory Management
- [X] General Coding Practices

### CODE REVIEW

**Comment by strider** [comment]
@PaulWay Could you please prefix your commit title with the Jira Issue key? As is, your PR will be fully referenced in Jira.

**Comment by PaulWay** [comment]
@strider Thanks!
@thearifismail - I haven't looked at Inventory in ages so I don't know the history on this.  I was just trying to copy the existing code in `api/host_query_db.py`.  Why are direct database queries no longer allowed?  Why use XJoin always?  If that's the way it is, then that's the way it is, but why is the DB code still there?

My task here is to try and improve the Dashboard speed by reducing the number of queries it does to Inventory.  What's the simplest way we can achieve that?

**Comment by thearifismail** [comment]
@PaulWay to deal with large number of hosts and query inventory for hosts, it was decided to use xjoin-search and elasticsearch and supporting both xjoin-search and DB queries required duplicate effort to do the same.   That's why direct querying for hosts via REST API was disabled.  However, there is a limited activity that still requires `api/host_db_query.py` and that's why it is still around.  Since all host queries are run using xjoin and if stats are collected directly from database, users may  get out-sync-data if the data has not been fully indexed between the DB and elasticsearch.

**Comment by PaulWay** [comment]
I'm not here to really debate the decision :-)  I guess I'm just wondering why we'd use the Inventory at all for this then?  If the Dashboard can make a query using GraphQL directly to XJoin, that'd be a lot faster than the Dashboard making an API request to Inventory which then makes a GraphQL query to XJoin.

**Comment by thearifismail** [comment]
Closing this PR as it is being replaced by https://github.com/RedHatInsights/xjoin-search/pull/179.  @PaulWay we can reopen it if needed.

**Pull request closed without merging**
