### PR TITLE
fix(ESSNTL-5555): Fixing right return on default api

### PR DESCRIPTION
**Pull request by fellipeh**
# Overview

This PR is being created to address [ESSNTL-5555](https://issues.redhat.com/browse/ESSNTL-5555).

We recently changed the conventional_staleness_delta default from 86400 to 104400, this commit fix that.

## PR Checklist

- [ ] Keep PR title short, ideally under 72 characters
- [ ] Descriptive comments provided in complex code blocks
- [ ] Tests: validate optimal/expected output
- [ ] Tests: validate exceptions and failure scenarios
- [ ] Tests: edge cases
- [ ] Recovers or fails gracefully during potential resource outages (e.g. DB, Kafka)
- [ ] Uses [type hinting](https://docs.python.org/3/library/typing.html), if convenient
- [ ] Documentation, if this PR changes the way other services interact with host inventory
- [ ] Links to related PRs

## Secure Coding Practices Documentation Reference

You can find documentation on this checklist [here](https://github.com/RedHatInsights/secure-coding-checklist).

## Secure Coding Checklist

- [ ] Input Validation
- [ ] Output Encoding
- [ ] Authentication and Password Management
- [ ] Session Management
- [ ] Access Control
- [ ] Cryptographic Practices
- [ ] Error Handling and Logging
- [ ] Data Protection
- [ ] Communication Security
- [ ] System Configuration
- [ ] Database Security
- [ ] File Management
- [ ] Memory Management
- [ ] General Coding Practices

### CODE REVIEW

**Review by thearifismail — COMMENTED** [review]
why `104400`? Why not `1` or `1000000000`?

**Review by thearifismail — DISMISSED** [review]

**Review by kruai — APPROVED** [review]

**Review by kruai — CHANGES_REQUESTED** [review]
Looks good, but you need to fix the unit test `test_get_sys_default_staleness` as well.

**Review by kruai — APPROVED** [review]

**Pull request merged**
