### PR TITLE
Allow more sessions in the selenium container deployment

### PR DESCRIPTION
**Pull request by SerCantus**
# Overview

In the test deployment we have errors reporting timeouts when requesting a new selenium session. This fix was proposed by other QA folks that encountered the same error.

## PR Checklist

- [x] Keep PR title short, ideally under 72 characters
- [x] Descriptive comments provided in complex code blocks
- [ ] Tests: validate optimal/expected output
- [ ] Tests: validate exceptions and failure scenarios
- [ ] Tests: edge cases
- [ ] Recovers or fails gracefully during potential resource outages (e.g. DB, Kafka)
- [ ] Uses [type hinting](https://docs.python.org/3/library/typing.html), if convenient
- [ ] Documentation, if this PR changes the way other services interact with host inventory
- [ ] Links to related PRs

### CODE REVIEW

**Review by kruai — APPROVED** [review]

**Review by thearifismail — COMMENTED** [review]
It LGTM, but would like to know the extent of its use?  How many teams or people use `testing-integration.yml`?

**Comment by thearifismail** [comment]
> It LGTM, but would like to know the extent of its use? How many teams or people use `testing-integration.yml`?

oh @kruai already approved it.

**Comment by SerCantus** [comment]
@thearifismail 
#It LGTM, but would like to know the extent of its use? How many teams or people use testing-integration.yml?
As far as I know only one. The merges in insights-host-inventory trigger my team integration tests for the task conversion. This file is the run configuration customised to this repository.

**Pull request merged**
