### PR TITLE
fix(ESSNTL-4769): Ordering groups by host_ids is random if groups have same amount of hosts

### PR DESCRIPTION
**Pull request by jpramos123**
# Overview

This PR is being created to address the bug reported at [ESSNTL-4769](https://issues.redhat.com/browse/ESSNTL-4769) .
It adds another `.order_by` to the group's query.

With this, the data that is being returned is fixed and correctly ordered.
Data is preserved when using `per_page` and `page` query parameters.

Related: ESSNTL-4769

## PR Checklist

- [ ] Keep PR title short, ideally under 72 characters
- [ ] Descriptive comments provided in complex code blocks
- [ ] Tests: validate optimal/expected output
- [ ] Tests: validate exceptions and failure scenarios
- [ ] Tests: edge cases
- [ ] Recovers or fails gracefully during potential resource outages (e.g. DB, Kafka)
- [ ] Uses [type hinting](https://docs.python.org/3/library/typing.html), if convenient
- [ ] Documentation, if this PR changes the way other services interact with host inventory
- [ ] Links to related PRs

## Secure Coding Practices Documentation Reference

You can find documentation on this checklist [here](https://github.com/RedHatInsights/secure-coding-checklist).

## Secure Coding Checklist

- [ ] Input Validation
- [ ] Output Encoding
- [ ] Authentication and Password Management
- [ ] Session Management
- [ ] Access Control
- [ ] Cryptographic Practices
- [ ] Error Handling and Logging
- [ ] Data Protection
- [ ] Communication Security
- [ ] System Configuration
- [ ] Database Security
- [ ] File Management
- [ ] Memory Management
- [x] General Coding Practices

### CODE REVIEW

**Review by kruai — COMMENTED** [review]
Looks good! Can you create or modify a test to validate the result?

**Review by thearifismail — COMMENTED** [review]
No tests to verify the ordering?

**Review by thearifismail — COMMENTED** [review]
Both of new tests are exactly the same, except the order how part.  I suggest having one test using parametrize for order_how.  See https://github.com/RedHatInsights/insights-host-inventory/blob/6eb5f4321b2639cc5e972562a29f83dc710f23f9/tests/test_api_groups_get.py#L33 for guidance.

Though it may not sound like a big deal now but given that groups have just been introduced, this test file is bound to grow.  To avoid code bloat, compaction now should help.

**Comment by jpramos123** [comment]
> Both of new tests are exactly the same, except the order how part. I suggest having one test using parametrize for order_how. See
> 
> https://github.com/RedHatInsights/insights-host-inventory/blob/6eb5f4321b2639cc5e972562a29f83dc710f23f9/tests/test_api_groups_get.py#L33
> 
> for guidance.
> Though it may not sound like a big deal now but given that groups have just been introduced, this test file is bound to grow. To avoid code bloat, compaction now should help.

Thanks @thearifismail! Made the changes to the test!

**Review by CodeHeeler — APPROVED** [review]
LGTM

**Review by thearifismail — APPROVED** [review]
LGTM

**Review by kruai — APPROVED** [review]

**Review by thearifismail — APPROVED** [review]

**Review by kruai — APPROVED** [review]

**Review by strider — APPROVED** [review]
LGTM

**Pull request merged**
