### PR TITLE
Remove Tahmid from the list of codeowners

### PR DESCRIPTION
**Pull request by tahmidefaz**
# Overview

This PR is being created to remove Tahmid from the list of codeowners.

## PR Checklist

- [ ] Keep PR title short, ideally under 72 characters
- [ ] Descriptive comments provided in complex code blocks
- [ ] Tests: validate optimal/expected output
- [ ] Tests: validate exceptions and failure scenarios
- [ ] Tests: edge cases
- [ ] Documentation, if this PR changes the way other services interact with host inventory
- [ ] Links to related PRs

## Secure Coding Practices Documentation Reference

You can find documentation on this checklist [here](https://github.com/RedHatInsights/secure-coding-checklist).

## Secure Coding Checklist

- [ ] Input Validation
- [ ] Output Encoding
- [ ] Authentication and Password Management
- [ ] Session Management
- [ ] Access Control
- [ ] Cryptographic Practices
- [ ] Error Handling and Logging
- [ ] Data Protection
- [ ] Communication Security
- [ ] System Configuration
- [ ] Database Security
- [ ] File Management
- [ ] Memory Management
- [ ] General Coding Practices

### CODE REVIEW

**Review by kruai — APPROVED** [review]
:cry:

**Review by ryandillinfelton — APPROVED** [review]
:sob: :wave:

**Comment by tahmidefaz** [comment]
@kruai @ryandillinfelton If you guys get some time, can you look into merging this one in? :slightly_smiling_face:

**Comment by kruai** [comment]
> @kruai @ryandillinfelton If you guys get some time, can you look into merging this one in?

We'd like to, but the PR builds are failing due to what appears to be a CDN issue. Once the builds are passing again, we'll be happy to merge.

**Comment by ryandillinfelton** [comment]
We'll miss you buddy :cry:

**Pull request merged**
