### PR TITLE
ESSNTL-3986: Fix "all tests" PR check pipeline

### PR DESCRIPTION
**Pull request by fstavela**
# Overview

This PR is being created to address [ESSNTL-3986](https://issues.redhat.com/browse/ESSNTL-3986).

This is a temporary workaround for the bonfire CICD script issue: https://github.com/RedHatInsights/bonfire/issues/283
In short, the issue is that `oc logs -f` stops reacting after 1 hour and then after another 30 mins of inactivity the job gets aborted and fails. This PR basically just kills the `oc logs -f` after 1 hour and starts it again.

## PR Checklist

- [x] Keep PR title short, ideally under 72 characters
- [x] Descriptive comments provided in complex code blocks
- [ ] Tests: validate optimal/expected output
- [ ] Tests: validate exceptions and failure scenarios
- [ ] Tests: edge cases
- [ ] Recovers or fails gracefully during potential resource outages (e.g. DB, Kafka)
- [ ] Uses [type hinting](https://docs.python.org/3/library/typing.html), if convenient
- [ ] Documentation, if this PR changes the way other services interact with host inventory
- [x] Links to related PRs

## Secure Coding Practices Documentation Reference

You can find documentation on this checklist [here](https://github.com/RedHatInsights/secure-coding-checklist).

## Secure Coding Checklist

- [ ] Input Validation
- [ ] Output Encoding
- [ ] Authentication and Password Management
- [ ] Session Management
- [ ] Access Control
- [ ] Cryptographic Practices
- [ ] Error Handling and Logging
- [ ] Data Protection
- [ ] Communication Security
- [ ] System Configuration
- [ ] Database Security
- [ ] File Management
- [ ] Memory Management
- [ ] General Coding Practices

### CODE REVIEW

**Review by FabriciaDinizRH — APPROVED** [review]

**Review by CodeHeeler — APPROVED** [review]
LGTM, thanks for taking care of this!

**Review by kruai — APPROVED** [review]

**Pull request merged**
