### PR TITLE
RHC-10807: Adding flush() to slow down events production to Kafka and avoid OOM …

### PR DESCRIPTION
**Pull request by thearifismail**
## Overview

This PR is being created to address [this Jira](https://issues.redhat.com/browse/RHCLOUD-10807).  It is for testing host_synchronization job which is experiencing out-of-memory problems on the stage OpenShift cluster.  Need Job deployment tested by Monday morning.
## Secure Coding Practices Checklist GitHub Link

- https://github.com/RedHatInsights/secure-coding-checklist

## Secure Coding Checklist

- [ ] Input Validation
- [ ] Output Encoding
- [ ] Authentication and Password Management
- [ ] Session Management
- [ ] Access Control
- [ ] Cryptographic Practices
- [ ] Error Handling and Logging
- [ ] Data Protection
- [ ] Communication Security
- [ ] System Configuration
- [ ] Database Security
- [ ] File Management
- [ ] Memory Management
- [ ] General Coding Practices

### CODE REVIEW

**Comment by kruai** [comment]
@thearifismail make sure you have your pre-commit check set up on your machine. It shouldn't allow you to push changes that break the pre-commit check in PRs like this

**Comment by kruai** [comment]
Although in this case, while it says the pre-commit check failed, it seems it's the unit tests that are failing. That's confusing :thinking:

**Review by kruai — APPROVED** [review]
Based on the conversation between you and Jozef on Slack, this seems like it would help address the issue. That said, I didn't realize Kafka integration could cause an OOM, so I'm not sure if my approval means a whole lot on this one, besides doing some basic checks. Do you think Jozef should review, or are we good?

**Comment by thearifismail** [comment]
> Based on the conversation between you and Jozef on Slack, this seems like it would help address the issue. That said, I didn't realize Kafka integration could cause an OOM, so I'm not sure if my approval means a whole lot on this one, besides doing some basic checks. Do you think Jozef should review, or are we good?

No.  this flush() should slow down the production of producer events and should help with OOM.  At least that's what the hope is.  Merging it does no harm because this change affects only the `host_synchronizer` script, which is not used anywhere else.  Furthermore, it is not being deployed to production environment; just `stage`.  That said, I need to get this in ASAP along with the update of E2E-deloy template.  Getting this in should give me ability to debug and monitor synchronizer pod.  Jozef can start monitoring and using this code if needed.

**Pull request merged**
