### PR TITLE
Update Kafka Topics for Clowder Template

### PR DESCRIPTION
**Pull request by BlakeHolifield**
## Overview

This PR is being created to address the change in Kafka topics [introduced here](https://github.com/RedHatInsights/insights-host-inventory/pull/843/files). `pr_check.sh` needs the updated template and topics to deploy correctly.

### CODE REVIEW

**Review by thearifismail — DISMISSED** [review]
LGTM

**Review by kruai — APPROVED** [review]
Ah, I forgot that we need to update our templates in multiple locations. This LGTM, though I realize I'm going to have to port over the changes I made in e2e-deploy

**Review by kruai — APPROVED** [review]
Still LGTM

**Comment by BlakeHolifield** [comment]
I removed the `source deploy_ephemeral_env.sh` for now because we're double deploying when we don't need to.

**Pull request merged**
