### PR TITLE
chore(SWATCH-2423): Add 'conversions' field to sp schema

### PR DESCRIPTION
**Pull request by FabriciaDinizRH**
# Overview

The field "conversions" has been added to `inventory-schemas` by https://github.com/RedHatInsights/inventory-schemas/pull/129. 
This PR adds it to HBI.

## PR Checklist

- [ ] Keep PR title short, ideally under 72 characters
- [ ] Descriptive comments provided in complex code blocks
- [ ] Tests: validate optimal/expected output
- [ ] Tests: validate exceptions and failure scenarios
- [ ] Tests: edge cases
- [ ] Recovers or fails gracefully during potential resource outages (e.g. DB, Kafka)
- [ ] Uses [type hinting](https://docs.python.org/3/library/typing.html), if convenient
- [ ] Documentation, if this PR changes the way other services interact with host inventory
- [ ] Links to related PRs

## Secure Coding Practices Documentation Reference

You can find documentation on this checklist [here](https://github.com/RedHatInsights/secure-coding-checklist).

## Secure Coding Checklist

- [ ] Input Validation
- [ ] Output Encoding
- [ ] Authentication and Password Management
- [ ] Session Management
- [ ] Access Control
- [ ] Cryptographic Practices
- [ ] Error Handling and Logging
- [ ] Data Protection
- [ ] Communication Security
- [ ] System Configuration
- [ ] Database Security
- [ ] File Management
- [ ] Memory Management
- [ ] General Coding Practices

### CODE REVIEW

**Comment by strider** [comment]
@FabriciaDinizRH Hey, is it the result of running `make update-schema`? Just for my information?

**Comment by FabriciaDinizRH** [comment]
> @FabriciaDinizRH Hey, is it the result of running `make update-schema`? Just for my information?

No, I forgot about that, honestly. I'll fix it.

**Comment by strider** [comment]
> > @FabriciaDinizRH Hey, is it the result of running `make update-schema`? Just for my information?
> 
> No, I forgot about that, honestly. I'll fix it.

`make update-schema` command doesn't update the `openapi.dev.json` file though.

**Comment by FabriciaDinizRH** [comment]
`/swagger/system_profile_commit_id` added. I got this update from the make command.

**Review by strider — APPROVED** [review]
LGTM

**Review by kruai — APPROVED** [review]

**Pull request merged**
