### PR TITLE
Improve ValidationException message

### PR DESCRIPTION
**Pull request by kruai**
# Overview

This PR is being created to address [ESSNTL-3629](https://issues.redhat.com/browse/ESSNTL-3629).
It adds the invalid data to the exception text to make debugging easier. It uses a dictionary comprehension, so I added a comment clarifying what it's doing.

## PR Checklist

- [x] Keep PR title short, ideally under 72 characters
- [x] Descriptive comments provided in complex code blocks
- [x] Tests: validate optimal/expected output
- [x] Tests: validate exceptions and failure scenarios
- [ ] Tests: edge cases
- [ ] Recovers or fails gracefully during potential resource outages (e.g. DB, Kafka)
- [ ] Uses [type hinting](https://docs.python.org/3/library/typing.html), if convenient
- [ ] Documentation, if this PR changes the way other services interact with host inventory
- [ ] Links to related PRs

## Secure Coding Practices Documentation Reference

You can find documentation on this checklist [here](https://github.com/RedHatInsights/secure-coding-checklist).

## Secure Coding Checklist

- [ ] Input Validation
- [ ] Output Encoding
- [ ] Authentication and Password Management
- [ ] Session Management
- [ ] Access Control
- [ ] Cryptographic Practices
- [ ] Error Handling and Logging
- [ ] Data Protection
- [ ] Communication Security
- [ ] System Configuration
- [ ] Database Security
- [ ] File Management
- [ ] Memory Management
- [ ] General Coding Practices

### CODE REVIEW

**Review by CodeHeeler — APPROVED** [review]
This is great, thanks so much for giving it another go!  I especially appreciate the elegance of the dictionary comprehension and that it caught all invalid values when my code would have only grabbed one.  Still not sure why I got the AttributeError when attempting to access `e.data` and you didn't, but glad it's working now.

**Review by FabriciaDinizRH — APPROVED** [review]

**Review by thearifismail — APPROVED** [review]

**Review by fstavela — APPROVED** [review]
LGTM

**Pull request merged**
