### PR TITLE
Add dependencies

### PR DESCRIPTION
**Pull request by kylape**

### CODE REVIEW

**Comment by kruai** [comment]
Should that config list the apps that must be running for HBI to work properly? Because if so, I'd say xjoin & strimzi should be on there. HBI can also technically function with or without ingress, puptoo, or engine AFAIK

**Comment by kylape** [comment]
sorry @kruai this was opened just to test out the dependency deployment functionality of bonfire. I agree that we are missing dependencies and also that the added dependencies are not true requirements for HBI.

**Comment by bsquizz** [comment]
[test]

**Comment by kruai** [comment]
@kylape Sorry this has been sitting around for so long - we're now going through open PRs that have fallen by the wayside.
If we still need these dependencies added, can you remove the changes to `pr_check.sh`? I'd be fine with merging it then

**Comment by kruai** [comment]
I'm going to close this because of how out-of-date it is (sorry)! If we still need to make a change, let me know and we can open another PR.

**Pull request closed without merging**
