### PR TITLE
add params for reading vars from app-sre env file

### PR DESCRIPTION
**Pull request by thearifismail**
# Overview

This PR is being created to address [this Jira](https://issues.redhat.com/browse/ESSNTL-xxxxx).

This PR adds new parameters to the ClowdApp's parameters list.  So the new params values could be read from the `app-sre` environment variables file.

## PR Checklist

- [ ] Keep PR title short, ideally under 72 characters
- [ ] Descriptive comments provided in complex code blocks
- [ ] Tests: validate optimal/expected output
- [ ] Tests: validate exceptions and failure scenarios
- [ ] Tests: edge cases
- [ ] Documentation, if this PR changes the way other services interact with host inventory
- [ ] Links to related PRs

## Secure Coding Practices Documentation Reference

You can find documentation on this checklist [here](https://github.com/RedHatInsights/secure-coding-checklist).

## Secure Coding Checklist

- [ ] Input Validation
- [ ] Output Encoding
- [ ] Authentication and Password Management
- [ ] Session Management
- [ ] Access Control
- [ ] Cryptographic Practices
- [ ] Error Handling and Logging
- [ ] Data Protection
- [ ] Communication Security
- [ ] System Configuration
- [ ] Database Security
- [ ] File Management
- [ ] Memory Management
- [ ] General Coding Practices

### CODE REVIEW

**Review by kruai — DISMISSED** [review]
Seems like this would be fine, but it would be great if it could be tested somehow before merging. Ephemeral cluster, maybe? I just don't want us to merge this and have to revert again

**Review by kruai — APPROVED** [review]
Everything appears to be in order here.

**Review by kruai — APPROVED** [review]

**Review by tahmidefaz — APPROVED** [review]
Looking good!

**Pull request merged**
