### PR TITLE
Build image forcing --no-cache use to pickup latest security fixes

### PR DESCRIPTION
**Pull request by thearifismail**
# Overview

This PR is being created to address [this Jira](https://issues.redhat.com/browse/ESSNTL-569).
Using `--no-cache` switch forces building image from scratch and picks all the new security patches applied to `registry.access.redhat.com/ubi8/python-38`

## PR Checklist

- [ ] Keep PR title short, ideally under 72 characters
- [ ] Descriptive comments provided in complex code blocks
- [ ] Tests: validate optimal/expected output
- [ ] Tests: validate exceptions and failure scenarios
- [ ] Tests: edge cases
- [ ] Documentation, if this PR changes the way other services interact with host inventory
- [ ] Links to related PRs

## Secure Coding Practices Documentation Reference

You can find documentation on this checklist [here](https://github.com/RedHatInsights/secure-coding-checklist).

## Secure Coding Checklist

- [ ] Input Validation
- [ ] Output Encoding
- [ ] Authentication and Password Management
- [ ] Session Management
- [ ] Access Control
- [ ] Cryptographic Practices
- [ ] Error Handling and Logging
- [ ] Data Protection
- [ ] Communication Security
- [ ] System Configuration
- [ ] Database Security
- [ ] File Management
- [ ] Memory Management
- [ ] General Coding Practices

### CODE REVIEW

**Review by kruai — APPROVED** [review]

**Comment by thearifismail** [comment]
Putting this on hold for now because Kent Aycoth wants to try `--pull` option first.

**Comment by thearifismail** [comment]
Closing this PR as it is not an issue anymore.

**Pull request closed without merging**
