### PR TITLE
Fix syntax errors and remove unused function

### PR DESCRIPTION
**Pull request by tahmidefaz**
## Overview

Pylint on my VS code was giving me warnings for possible syntax errors. So, I decided to investigate and found out that we are not providing sufficient parameters to one function and we are not using the other function at all.

## Secure Coding Practices Checklist GitHub Link

- https://github.com/RedHatInsights/secure-coding-checklist

## Secure Coding Checklist
- [x] Error Handling and Logging
- [x] General Coding Practices

### CODE REVIEW

**Review by kruai — APPROVED** [review]
LGTM!

**Comment by tahmidefaz** [comment]
I wonder what's up with the `ci.ext.devshift.net PR build` :thinking:

**Comment by kruai** [comment]
IDK - it's happening in Arif's PR too

**Comment by gmcculloug** [comment]
All tests are passing now.  @ryandillinfelton @thearifismail Please review.

**Review by thearifismail — APPROVED** [review]
LGTM

**Pull request merged**
