### PR TITLE
Run sonarqube scan during PR check and merge to master.

### PR DESCRIPTION
**Pull request by roliveri**
# Overview

This PR is being created to address [/ESSNTL-1588](https://issues.redhat.com/browse//ESSNTL-1588).
(A description of your PR's changes, along with why/context to the PR, goes here.)

## PR Checklist

- [ ] Keep PR title short, ideally under 72 characters
- [ ] Descriptive comments provided in complex code blocks
- [ ] Tests: validate optimal/expected output
- [ ] Tests: validate exceptions and failure scenarios
- [ ] Tests: edge cases
- [ ] Recovers or fails gracefully during potential resource outages (e.g. DB, Kafka)
- [ ] Documentation, if this PR changes the way other services interact with host inventory
- [ ] Links to related PRs

## Secure Coding Practices Documentation Reference

You can find documentation on this checklist [here](https://github.com/RedHatInsights/secure-coding-checklist).

## Secure Coding Checklist

- [ ] Input Validation
- [ ] Output Encoding
- [ ] Authentication and Password Management
- [ ] Session Management
- [ ] Access Control
- [ ] Cryptographic Practices
- [ ] Error Handling and Logging
- [ ] Data Protection
- [ ] Communication Security
- [ ] System Configuration
- [ ] Database Security
- [ ] File Management
- [ ] Memory Management
- [ ] General Coding Practices

### CODE REVIEW

**Comment by roliveri** [comment]
Do we need to call this from `pr_check.sh`?

**Comment by thearifismail** [comment]
@roliveri I suggest keeping it out of `pr_check` because `pr_check` fails for different reasons all the time.  Most of the times, failure causes are hard to locate. Adding `sonarqube` will simply add one more thing to sift through.

**Comment by thearifismail** [comment]
> > @roliveri I suggest keeping it out of `pr_check` because `pr_check` fails for different reasons all the time. Most of the times, failure causes are hard to locate. Adding `sonarqube` will simply add one more thing to sift through.
> 
> We do want this to be automated with each PR, though, which makes me think pr_check might be the right move. Or do you mean there's somewhere else it can automatically run?

Automation was not my mind.  If running with each PR is the goal, then that's fine.  We will just have to get used to it.

**Comment by roliveri** [comment]
@kruai @thearifismail OK, so if we call it through `pr_check`, should we call it via the Makefile: `make scan_project`, or call the shell directly: `$APP_ROOT/sonarqube.sh`?

I added the entry to the Makefile because that's how it was done for the marketplace-processor. If we call the shell directly, do we even need the Makefile changes?

**Comment by thearifismail** [comment]
Using "$APP_ROOT/sonarqube.sh" feels natural, but may be easier to run
"make ..." because the Makefile is already in the container.

My two cents.
- Arif

**Comment by kruai** [comment]
I don't know if it matters either way... `make scan_project` definitely seems cleaner

**Review by kruai — APPROVED** [review]
LGTM! It looks like this will fix the scan job that's failing on other PRs.

**Pull request merged**
