### PR TITLE
RHINENG-98: Enable TLS

### PR DESCRIPTION
**Pull request by thearifismail**
# Overview

This PR is being created to address [RHINENG-98](https://issues.redhat.com/browse/RHINENG-98).

## PR Checklist

- [ ] Keep PR title short, ideally under 72 characters
- [ ] Descriptive comments provided in complex code blocks
- [ ] Tests: validate optimal/expected output
- [ ] Tests: validate exceptions and failure scenarios
- [ ] Tests: edge cases
- [ ] Recovers or fails gracefully during potential resource outages (e.g. DB, Kafka)
- [ ] Uses [type hinting](https://docs.python.org/3/library/typing.html), if convenient
- [ ] Documentation, if this PR changes the way other services interact with host inventory
- [ ] Links to related PRs

## Secure Coding Practices Documentation Reference

You can find documentation on this checklist [here](https://github.com/RedHatInsights/secure-coding-checklist).

## Secure Coding Checklist

- [ ] Input Validation
- [ ] Output Encoding
- [ ] Authentication and Password Management
- [ ] Session Management
- [ ] Access Control
- [ ] Cryptographic Practices
- [ ] Error Handling and Logging
- [ ] Data Protection
- [ ] Communication Security
- [ ] System Configuration
- [ ] Database Security
- [ ] File Management
- [ ] Memory Management
- [ ] General Coding Practices

### CODE REVIEW

**Comment by thearifismail** [comment]
@dkuc FYI

**Review by CodeHeeler — DISMISSED** [review]
LGTM, thanks for taking care of this!

**Comment by thearifismail** [comment]
@kruai with this new check of `tlsCAPath` in place, it is safe to merge this PR.

**Comment by dkuc** [comment]
tlsCAPath requires `app-common-python` 2.5 or greater. Or read the json directly.

**Comment by dkuc** [comment]
In advsior we simplified by setting the env var in code.
https://gitlab.cee.redhat.com/insights-platform/advisor-backend/-/blob/master/api/advisor/project_settings/settings.py#L111
``` python
if LoadedConfig.tlsCAPath:
        os.environ["REQUESTS_CA_BUNDLE"] = LoadedConfig.tlsCAPath
```

**Comment by thearifismail** [comment]
Done! Though this is good for update to all containers done in once space, I liked the explicitness of what the environment variable and it value was.  Now the same info is hidden.

**Comment by thearifismail** [comment]
@dkuc, if you're okay with this state, I would like to get it merge for test deployment to the Fedramp cluster

**Review by kruai — DISMISSED** [review]

**Review by CodeHeeler — DISMISSED** [review]
LGTM, thanks for taking care of this!

**Comment by dkuc** [comment]
@thearifismail are you going to update app-common-python in a seperate MR? 2.3 is not going to work.
https://github.com/RedHatInsights/insights-host-inventory/blob/master/Pipfile.lock#L34-L40

**Comment by thearifismail** [comment]
> @thearifismail are you going to update app-common-python in a seperate MR? 2.3 is not going to work. https://github.com/RedHatInsights/insights-host-inventory/blob/master/Pipfile.lock#L34-L40
> 
> ```shell
> pipenv install --keep-outdated --selective-upgrade app-common-python==0.2.5
> pipenv lock --keep-outdated
> ```
> 
> ^ How I upgraded without updating every pipenv package

Oh I just your update method after pushing my change but good to know this trick.  Thanks.

@dkuc here is the update PR.

**Review by CodeHeeler — APPROVED** [review]
LGTM

**Review by kruai — APPROVED** [review]

**Comment by dkuc** [comment]
Looks good

**Comment by kruai** [comment]
The All Tests check has been running for over an hour, but I'll merge this as soon as it passes.

**Pull request merged**
