### PR TITLE
Add new system profile filters

### PR DESCRIPTION
**Pull request by ryandillinfelton**
## Overview

This PR is being created to address [this Jira](https://issues.redhat.com/browse/RHCLOUD-xxxxx).
(A description of your PR's changes goes here.)

## Secure Coding Practices Checklist GitHub Link

- https://github.com/RedHatInsights/secure-coding-checklist

## Secure Coding Checklist

- [ ] Input Validation
- [ ] Output Encoding
- [ ] Authentication and Password Management
- [ ] Session Management
- [ ] Access Control
- [ ] Cryptographic Practices
- [ ] Error Handling and Logging
- [ ] Data Protection
- [ ] Communication Security
- [ ] System Configuration
- [ ] Database Security
- [ ] File Management
- [ ] Memory Management
- [x] General Coding Practices

### CODE REVIEW

**Review by tahmidefaz — CHANGES_REQUESTED** [review]
Looks great! I didn't fine any issues with your implementation yet.
All the tests are for a "happy path", it might be better to add some more tests for failures. What do you think?

**Comment by ryandillinfelton** [comment]
> Looks great! I didn't fine any issue with your implementation yet.
> All the tests are for a "happy path", it might be better to add some more tests for failures. What do you think?

Right now there really ins't any handling of improper values implimented at all. I'm planning to follow up this and the PRS filters with something to impliment and test that. It's pretty similar to the situation we had with the SAP system profile field filters. JSONSchema can't enforce the format of inputs we expect so I'm going to have to come up with a manual way to check it

**Review by tahmidefaz — APPROVED** [review]
That makes sense! If we have a ticket for it, might be a good idea to link it here. It's a LGTM from me :+1:

**Comment by ryandillinfelton** [comment]
> That makes sense! If we have a ticket for it, might be a good idea to link it here. It's a LGTM from me

Here's the ticket https://issues.redhat.com/browse/RHCLOUD-10001

**Review by thearifismail — APPROVED** [review]
LGTM

**Review by kruai — APPROVED** [review]
LGTM!

**Pull request merged**
