### PR TITLE
Add mirrorlist and SAP object to System Profile

### PR DESCRIPTION
**Pull request by kruai**
# Overview

This PR is being created to address [ESSNTL-3637](https://issues.redhat.com/browse/ESSNTL-3637) and [ESSNTL-1419](https://issues.redhat.com/browse/ESSNTL-1419). It syncs the System Profile in HBI with the source of truth in inventory-schemas.

## PR Checklist

- [x] Keep PR title short, ideally under 72 characters
- [ ] Descriptive comments provided in complex code blocks
- [ ] Tests: validate optimal/expected output
- [ ] Tests: validate exceptions and failure scenarios
- [ ] Tests: edge cases
- [ ] Recovers or fails gracefully during potential resource outages (e.g. DB, Kafka)
- [ ] Uses [type hinting](https://docs.python.org/3/library/typing.html), if convenient
- [ ] Documentation, if this PR changes the way other services interact with host inventory
- [ ] Links to related PRs

## Secure Coding Practices Documentation Reference

You can find documentation on this checklist [here](https://github.com/RedHatInsights/secure-coding-checklist).

## Secure Coding Checklist

- [ ] Input Validation
- [ ] Output Encoding
- [ ] Authentication and Password Management
- [ ] Session Management
- [ ] Access Control
- [ ] Cryptographic Practices
- [ ] Error Handling and Logging
- [ ] Data Protection
- [ ] Communication Security
- [ ] System Configuration
- [ ] Database Security
- [ ] File Management
- [ ] Memory Management
- [ ] General Coding Practices

### CODE REVIEW

**Review by CodeHeeler — DISMISSED** [review]
Thanks for taking care of this!

**Comment by kruai** [comment]
I'm going to wait until this PR gets merged: https://github.com/RedHatInsights/inventory-schemas/pull/98
I'll run the update script again after that.

**Comment by kruai** [comment]
OK, it's updated with the latest spec and ready for re-review

**Review by CodeHeeler — APPROVED** [review]

**Comment by CodeHeeler** [comment]
@fstavela if that "All tests" build failure is not a concern after you check it, this can merge.

**Review by fstavela — APPROVED** [review]

**Pull request merged**
