### PR TITLE
feat(rhineng-13808): Migrate data from public schema to hbi schema

### PR DESCRIPTION
**Pull request by chambridge**
# Overview

This PR is being created to address [RHINENG-13808](https://issues.redhat.com/browse/RHINENG-13808).
* Create migration with schema creation and move tables to new schema
* Update deployment to use new schema location for data tables

## PR Checklist

- [x] Keep PR title short, ideally under 72 characters
- [ ] Descriptive comments provided in complex code blocks
- [ ] Include raw query examples in the PR description, if adding/modifying SQL query
- [ ] Tests: validate optimal/expected output
- [ ] Tests: validate exceptions and failure scenarios
- [ ] Tests: edge cases
- [ ] Recovers or fails gracefully during potential resource outages (e.g. DB, Kafka)
- [ ] Uses [type hinting](https://docs.python.org/3/library/typing.html), if convenient
- [ ] Documentation, if this PR changes the way other services interact with host inventory
- [ ] Links to related PRs

## Secure Coding Practices Documentation Reference

You can find documentation on this checklist [here](https://github.com/RedHatInsights/secure-coding-checklist).

## Secure Coding Checklist

- [ ] Input Validation
- [ ] Output Encoding
- [ ] Authentication and Password Management
- [ ] Session Management
- [ ] Access Control
- [ ] Cryptographic Practices
- [ ] Error Handling and Logging
- [ ] Data Protection
- [ ] Communication Security
- [ ] System Configuration
- [ ] Database Security
- [ ] File Management
- [ ] Memory Management
- [ ] General Coding Practices

### CODE REVIEW

**Review by kruai — DISMISSED** [review]
Seems good. Makes sense to change `INVENTORY_DB_SCHEMA` within the actual config instead of app-interface. Do we actually want that to be configurable externally? Seems like we'd always have to make a DB migration in tandem with that change

**Comment by chambridge** [comment]
> Seems good. Makes sense to change `INVENTORY_DB_SCHEMA` within the actual config instead of app-interface. Do we actually want that to be configurable externally? Seems like we'd always have to make a DB migration in tandem with that change

I essentially plan to pull out the variable altogether once we are deployed and functional in prod, but this gives us options if we need to make direct SQL changes.

**Comment by thearifismail** [comment]
@chambridge shouldn't the public schema in `INVENTORY_SCHEMA = os.getenv("INVENTORY_DB_SCHEMA", "public")` in `app.models.py` be changed to `hbi`?

**Review by kruai — APPROVED** [review]

**Review by thearifismail — APPROVED** [review]

**Pull request merged**
