### PR TITLE
Update 'coverage' version in Pipfile

### PR DESCRIPTION
**Pull request by fstavela**
# Overview

This PR is being created to address PR check failures. The PR check started failing yesterday on building the host inventory image. It fails on a step, where it tries to install Python packages - dependencies of host inventory.
I found out that the `coverage` version that we use is very old and it has deprecated code in `setup.cfg`.
Please, check this PR carefully. I don't know if we have some established process of updating dependencies that we should follow. All I did is `pipenv update coverage --dev` and `pipenv lock --dev`.

## PR Checklist

- [x] Keep PR title short, ideally under 72 characters
- [ ] Descriptive comments provided in complex code blocks
- [ ] Tests: validate optimal/expected output
- [ ] Tests: validate exceptions and failure scenarios
- [ ] Tests: edge cases
- [ ] Recovers or fails gracefully during potential resource outages (e.g. DB, Kafka)
- [ ] Uses [type hinting](https://docs.python.org/3/library/typing.html), if convenient
- [ ] Documentation, if this PR changes the way other services interact with host inventory
- [ ] Links to related PRs

## Secure Coding Practices Documentation Reference

You can find documentation on this checklist [here](https://github.com/RedHatInsights/secure-coding-checklist).

## Secure Coding Checklist

- [ ] Input Validation
- [ ] Output Encoding
- [ ] Authentication and Password Management
- [ ] Session Management
- [ ] Access Control
- [ ] Cryptographic Practices
- [ ] Error Handling and Logging
- [ ] Data Protection
- [ ] Communication Security
- [ ] System Configuration
- [ ] Database Security
- [ ] File Management
- [ ] Memory Management
- [ ] General Coding Practices

### CODE REVIEW

**Comment by fstavela** [comment]
Please, check this PR carefully. I don't know if we have some established process of updating dependencies that we should follow. All I did is pipenv update coverage --dev and pipenv lock --dev.

**Comment by fstavela** [comment]
Don't worry about the failed all-tests pipeline, those failed tests shouldn't have run, I forgot to put a temporary skip on them until MQ issues are fixed.

**Review by CodeHeeler — APPROVED** [review]
LGTM, I'm not sure why any are pinned at specific versions, so it's hard to know whether still relevant.  I agree it would be best to try moving to updated versions and if we hit issues, we can undo, comment as to why, and investigate other options.

**Review by FabriciaDinizRH — APPROVED** [review]
LGTM!

**Review by strider — APPROVED** [review]

**Pull request merged**
