### PR TITLE
Migrate documentation and convert to markdown

### PR DESCRIPTION
**Pull request by kruai**
## Overview

This PR is being created to address [this Jira](https://issues.redhat.com/browse/RHCLOUD-12611).
I took the latest version of our documentation in the old [platform-docs repo](https://gitlab.cee.redhat.com/insights-platform/platform-docs/-/blob/master/src/backend/inventory.rst) and converted it to markdown, fixing a few grammatical errors along the way. I'm sure there are a few more changes we'd like to make to the documentation, but this PR is strictly about porting from the deprecated repository.

## Secure Coding Practices Checklist GitHub Link

- https://github.com/RedHatInsights/secure-coding-checklist

## Secure Coding Checklist

- None (it's not code)

### CODE REVIEW

**Review by tahmidefaz — CHANGES_REQUESTED** [review]
I think this needs to be synced to the current version of the docs. For example, I couldn't find [this section](https://platform-docs.cloud.paas.psi.redhat.com/backend/inventory.html#fetching-sparse-system-profile-fieldsets) in the markdown

**Comment by kruai** [comment]
> I think this needs to be synced to the current version of the docs. For example, I couldn't find [this section](https://platform-docs.cloud.paas.psi.redhat.com/backend/inventory.html#fetching-sparse-system-profile-fieldsets) in the markdown

Ah, you're right... I was converting from the old documentation PR that Jag opened to our repo. I'll get the new changes added

**Review by ryandillinfelton — COMMENTED** [review]
Mostly looks good but there's some awkward error catching on the code blocks  where we use pseudo code and placeholders.

For the HTTP ones I think you can just set the syntax highlighting to "text" since it's not doing much anyways.

I'd like to keep the JSON highlighting though, so for those I think we can just wrap the contents of the arrays and objects in quotes. I'm open to debate on that though, it could be misleading about type.

**Comment by kruai** [comment]
> Mostly looks good but there's some awkward error catching on the code blocks where we use pseudo code and placeholders.
> 
> For the HTTP ones I think you can just set the syntax highlighting to "text" since it's not doing much anyways.
> 
> I'd like to keep the JSON highlighting though, so for those I think we can just wrap the contents of the arrays and objects in quotes. I'm open to debate on that though, it could be misleading about type.

What error are you seeing? I didn't see anything complain on my end. I changed the "http" blocks to "text" though, just in case.

**Review by ryandillinfelton — APPROVED** [review]
:partying_face:

**Review by tahmidefaz — APPROVED** [review]
LGTM! :+1:

**Pull request merged**
