### PR TITLE
Revert "Temporarily pin the ubi8 version"

### PR DESCRIPTION
**Pull request by kruai**
Reverts RedHatInsights/insights-host-inventory#1036. On hold until the issue described in [this Slack thread](https://coreos.slack.com/archives/CCRND57FW/p1637087808474000) is resolved.

### CODE REVIEW

**Comment by ryandillinfelton** [comment]
@kruai Should this still be open?

**Comment by kruai** [comment]
@ryandillinfelton IDK - I haven't heard whether the UBI 8 issue is resolved. We can address this after the holiday, but have you heard anything about it @thearifismail ?

**Comment by thearifismail** [comment]
@kruai no, I have not heard of this issue.  Though my build is failing but does not appear to be this reason.

**Comment by thearifismail** [comment]
IMO, it should be closed.

**Comment by kruai** [comment]
We can't leave it pinned to this old version forever, though. My understanding is that we'd want to go back to pulling the latest version after the issue was resolved. Was that not your impression @thearifismail ?

**Comment by kruai** [comment]
OK @thearifismail & @ryandillinfelton: I've made PR #1059 to unpin the version and disable beta repos, and am closing this PR in favor of that one. Disabling the beta repos is required until they fix the issue in the base UBI8 image, but it also shouldn't hurt anything on our side.

**Pull request closed without merging**
