### PR TITLE
fix(ESSNTL-4096): Enable gunicorn multiproc metrics

### PR DESCRIPTION
**Pull request by kruai**
# Overview

This PR is being created to address [ESSNTL-4096](https://issues.redhat.com/browse/ESSNTL-4096).
We recently had to revert our gunicorn multiproc metrics change (#1257) because the metrics weren't able to be scraped. This PR reimplements multiprocess metrics, but instead of using the same-server `GunicornInternalPrometheusMetrics`, it uses `GunicornPrometheusMetrics`, which serves the metrics on a separate server.

We already have unit tests that validate our metrics setup, but in order to comprehensively test them in an app-interface environment, I think we might need a new IQE smoke test. In the meantime, I'm going to run this in an ephemeral environment and validate manually.

## PR Checklist

- [x] Keep PR title short, ideally under 72 characters
- [ ] Descriptive comments provided in complex code blocks
- [ ] Tests: validate optimal/expected output
- [ ] Tests: validate exceptions and failure scenarios
- [ ] Tests: edge cases
- [ ] Recovers or fails gracefully during potential resource outages (e.g. DB, Kafka)
- [ ] Uses [type hinting](https://docs.python.org/3/library/typing.html), if convenient
- [ ] Documentation, if this PR changes the way other services interact with host inventory
- [x] Links to related PRs

## Secure Coding Practices Documentation Reference

You can find documentation on this checklist [here](https://github.com/RedHatInsights/secure-coding-checklist).

## Secure Coding Checklist

- [ ] Input Validation
- [ ] Output Encoding
- [ ] Authentication and Password Management
- [ ] Session Management
- [ ] Access Control
- [ ] Cryptographic Practices
- [ ] Error Handling and Logging
- [ ] Data Protection
- [ ] Communication Security
- [ ] System Configuration
- [ ] Database Security
- [ ] File Management
- [ ] Memory Management
- [ ] General Coding Practices

### CODE REVIEW

**Comment by kruai** [comment]
OK, I've just tested this in the ephemeral environment and it's returning the metrics on the correct port: 
```
(app-root) (app-root) sh-4.4$ curl localhost:9000/metrics
# HELP inventory_request_processing_seconds Multiprocess metric
# TYPE inventory_request_processing_seconds summary
inventory_request_processing_seconds_count 9.0
inventory_request_processing_seconds_sum 0.43767674600076134
# HELP inventory_schema_validation_seconds Multiprocess metric
# TYPE inventory_schema_validation_seconds summary
inventory_schema_validation_seconds_count 0.0
inventory_schema_validation_seconds_sum 0.0
# HELP inventory_ingress_message_parsing_seconds Multiprocess metric
# TYPE inventory_ingress_message_parsing_seconds summary
inventory_ingress_message_parsing_seconds_count 0.0
inventory_ingress_message_parsing_seconds_sum 0.0
# HELP inventory_ingress_message_handler_seconds Multiprocess metric
# TYPE inventory_ingress_message_handler_seconds summary
inventory_ingress_message_handler_seconds_count 0.0
inventory_ingress_message_handler_seconds_sum 0.0
# HELP inventory_dedup_processing_seconds Multiprocess metric
# TYPE inventory_dedup_processing_seconds summary
inventory_dedup_processing_seconds_count 0.0
inventory_dedup_processing_seconds_sum 0.0
# HELP inventory_find_host_using_elevated_ids_processing_seconds Multiprocess metric
# TYPE inventory_find_host_using_elevated_ids_processing_seconds summary
inventory_find_host_using_elevated_ids_processing_seconds_count 0.0
inventory_find_host_using_elevated_ids_processing_seconds_sum 0.0
# HELP inventory_new_host_commit_seconds Multiprocess metric
# TYPE inventory_new_host_commit_seconds summary
inventory_new_host_commit_seconds_count 0.0
inventory_new_host_commit_seconds_sum 0.0
# HELP inventory_update_host_commit_seconds Multiprocess metric
# TYPE inventory_update_host_commit_seconds summary
inventory_update_host_commit_seconds_count 0.0
inventory_update_host_commit_seconds_sum 0.0
# HELP inventory_delete_host_commit_seconds Multiprocess metric
# TYPE inventory_delete_host_commit_seconds summary
inventory_delete_host_commit_seconds_count 0.0
inventory_delete_host_commit_seconds_sum 0.0
# HELP inventory_request_count_total Multiprocess metric
# TYPE inventory_request_count_total counter
inventory_request_count_total 9.0
# HELP inventory_login_failure_count_total Multiprocess metric
# TYPE inventory_login_failure_count_total counter
inventory_login_failure_count_total 0.0
# HELP inventory_payload_tracker_message_send_failure_count_total Multiprocess metric
# TYPE inventory_payload_tracker_message_send_failure_count_total counter
inventory_payload_tracker_message_send_failure_count_total 0.0
# HELP inventory_payload_tracker_message_construction_failure_count_total Multiprocess metric
# TYPE inventory_payload_tracker_message_construction_failure_count_total counter
inventory_payload_tracker_message_construction_failure_count_total 0.0
# HELP inventory_ingress_update_system_profile_successes_total Multiprocess metric
# TYPE inventory_ingress_update_system_profile_successes_total counter
inventory_ingress_update_system_profile_successes_total 0.0
# HELP inventory_ingress_message_handler_successes_total Multiprocess metric
# TYPE inventory_ingress_message_handler_successes_total counter
inventory_ingress_message_handler_successes_total 0.0
# HELP inventory_ingress_message_handler_failures_total Multiprocess metric
# TYPE inventory_ingress_message_handler_failures_total counter
inventory_ingress_message_handler_failures_total 0.0
# HELP inventory_rbac_fetching_failures_total Multiprocess metric
# TYPE inventory_rbac_fetching_failures_total counter
inventory_rbac_fetching_failures_total 0.0
# HELP inventory_tenant_translator_fetching_failures_total Multiprocess metric
# TYPE inventory_tenant_translator_fetching_failures_total counter
inventory_tenant_translator_fetching_failures_total 0.0
# HELP inventory_create_host_count_total Multiprocess metric
# TYPE inventory_create_host_count_total counter
inventory_create_host_count_total 0.0
# HELP inventory_update_host_count_total Multiprocess metric
# TYPE inventory_update_host_count_total counter
inventory_update_host_count_total 0.0
# HELP inventory_delete_host_count_total Multiprocess metric
# TYPE inventory_delete_host_count_total counter
inventory_delete_host_count_total 0.0
# HELP inventory_reaper_fail_count_total Multiprocess metric
# TYPE inventory_reaper_fail_count_total counter
inventory_reaper_fail_count_total 0.0
# HELP inventory_synchronize_host_count_total Multiprocess metric
# TYPE inventory_synchronize_host_count_total counter
inventory_synchronize_host_count_total 0.0
# HELP inventory_synchronize_fail_count_total Multiprocess metric
# TYPE inventory_synchronize_fail_count_total counter
inventory_synchronize_fail_count_total 0.0
# HELP inventory_pendo_syncher_failures_total Multiprocess metric
# TYPE inventory_pendo_syncher_failures_total counter
inventory_pendo_syncher_failures_total 0.0
# HELP inventory_delete_duplicate_host_count_total Multiprocess metric
# TYPE inventory_delete_duplicate_host_count_total counter
inventory_delete_duplicate_host_count_total 0.0
# HELP inventory_event_producer_failures_total Multiprocess metric
# TYPE inventory_event_producer_failures_total counter
inventory_event_producer_failures_total{event_type="created",topic="platform.inventory.events"} 0.0
inventory_event_producer_failures_total{event_type="updated",topic="platform.inventory.events"} 0.0
inventory_event_producer_failures_total{event_type="delete",topic="platform.inventory.events"} 0.0
# HELP inventory_event_producer_successes_total Multiprocess metric
# TYPE inventory_event_producer_successes_total counter
inventory_event_producer_successes_total{event_type="created",topic="platform.inventory.events"} 0.0
inventory_event_producer_successes_total{event_type="updated",topic="platform.inventory.events"} 0.0
inventory_event_producer_successes_total{event_type="delete",topic="platform.inventory.events"} 0.0
# HELP notification_event_producer_failures_total Multiprocess metric
# TYPE notification_event_producer_failures_total counter
notification_event_producer_failures_total{notification_type="validation_error",topic="platform.notifications.ingress"} 0.0
# HELP notification_event_producer_successes_total Multiprocess metric
# TYPE notification_event_producer_successes_total counter
notification_event_producer_successes_total{notification_type="validation_error",topic="platform.notifications.ingress"} 0.0
# HELP inventory_rbac_access_denied_total Multiprocess metric
# TYPE inventory_rbac_access_denied_total counter
inventory_rbac_access_denied_total{required_permission="inventory:hosts:read"} 0.0
inventory_rbac_access_denied_total{required_permission="inventory:hosts:write"} 0.0
# HELP inventory_http_request_total Multiprocess metric
# TYPE inventory_http_request_total counter
inventory_http_request_total{method="GET",status="200"} 9.0
# HELP inventory_outbound_http_response_time_seconds Multiprocess metric
# TYPE inventory_outbound_http_response_time_seconds histogram
inventory_outbound_http_response_time_seconds_sum{dependency="xjoin"} 0.43089792499904433
inventory_outbound_http_response_time_seconds_sum{dependency="rbac"} 0.0
inventory_outbound_http_response_time_seconds_bucket{dependency="xjoin",le="0.005"} 0.0
inventory_outbound_http_response_time_seconds_bucket{dependency="xjoin",le="0.01"} 0.0
inventory_outbound_http_response_time_seconds_bucket{dependency="xjoin",le="0.025"} 4.0
inventory_outbound_http_response_time_seconds_bucket{dependency="xjoin",le="0.05"} 7.0
inventory_outbound_http_response_time_seconds_bucket{dependency="xjoin",le="0.075"} 7.0
inventory_outbound_http_response_time_seconds_bucket{dependency="xjoin",le="0.1"} 7.0
inventory_outbound_http_response_time_seconds_bucket{dependency="xjoin",le="0.25"} 9.0
inventory_outbound_http_response_time_seconds_bucket{dependency="xjoin",le="0.5"} 9.0
inventory_outbound_http_response_time_seconds_bucket{dependency="xjoin",le="0.75"} 9.0
inventory_outbound_http_response_time_seconds_bucket{dependency="xjoin",le="1.0"} 9.0
inventory_outbound_http_response_time_seconds_bucket{dependency="xjoin",le="2.5"} 9.0
inventory_outbound_http_response_time_seconds_bucket{dependency="xjoin",le="5.0"} 9.0
inventory_outbound_http_response_time_seconds_bucket{dependency="xjoin",le="7.5"} 9.0
inventory_outbound_http_response_time_seconds_bucket{dependency="xjoin",le="10.0"} 9.0
inventory_outbound_http_response_time_seconds_bucket{dependency="xjoin",le="+Inf"} 9.0
inventory_outbound_http_response_time_seconds_count{dependency="xjoin"} 9.0
inventory_outbound_http_response_time_seconds_bucket{dependency="rbac",le="0.005"} 0.0
inventory_outbound_http_response_time_seconds_bucket{dependency="rbac",le="0.01"} 0.0
inventory_outbound_http_response_time_seconds_bucket{dependency="rbac",le="0.025"} 0.0
inventory_outbound_http_response_time_seconds_bucket{dependency="rbac",le="0.05"} 0.0
inventory_outbound_http_response_time_seconds_bucket{dependency="rbac",le="0.075"} 0.0
inventory_outbound_http_response_time_seconds_bucket{dependency="rbac",le="0.1"} 0.0
inventory_outbound_http_response_time_seconds_bucket{dependency="rbac",le="0.25"} 0.0
inventory_outbound_http_response_time_seconds_bucket{dependency="rbac",le="0.5"} 0.0
inventory_outbound_http_response_time_seconds_bucket{dependency="rbac",le="0.75"} 0.0
inventory_outbound_http_response_time_seconds_bucket{dependency="rbac",le="1.0"} 0.0
inventory_outbound_http_response_time_seconds_bucket{dependency="rbac",le="2.5"} 0.0
inventory_outbound_http_response_time_seconds_bucket{dependency="rbac",le="5.0"} 0.0
inventory_outbound_http_response_time_seconds_bucket{dependency="rbac",le="7.5"} 0.0
inventory_outbound_http_response_time_seconds_bucket{dependency="rbac",le="10.0"} 0.0
inventory_outbound_http_response_time_seconds_bucket{dependency="rbac",le="+Inf"} 0.0
inventory_outbound_http_response_time_seconds_count{dependency="rbac"} 0.0
# HELP inventory_http_request_duration_seconds Multiprocess metric
# TYPE inventory_http_request_duration_seconds histogram
inventory_http_request_duration_seconds_sum{method="GET",status="200",url_rule="/api/inventory/v1/tags"} 0.13107527299962385
inventory_http_request_duration_seconds_sum{method="GET",status="200",url_rule="/api/inventory/v1/system_profile/sap_sids"} 0.10846333199970104
inventory_http_request_duration_seconds_sum{method="GET",status="200",url_rule="/api/inventory/v1/system_profile/sap_system"} 0.05048794499998621
inventory_http_request_duration_seconds_sum{method="GET",status="200",url_rule="/api/inventory/v1/hosts"} 0.12155522200100677
inventory_http_request_duration_seconds_sum{method="GET",status="200",url_rule="/api/inventory/v1/system_profile/operating_system"} 0.04445398000007117
inventory_http_request_duration_seconds_bucket{le="0.005",method="GET",status="200",url_rule="/api/inventory/v1/tags"} 0.0
inventory_http_request_duration_seconds_bucket{le="0.01",method="GET",status="200",url_rule="/api/inventory/v1/tags"} 0.0
inventory_http_request_duration_seconds_bucket{le="0.025",method="GET",status="200",url_rule="/api/inventory/v1/tags"} 0.0
inventory_http_request_duration_seconds_bucket{le="0.05",method="GET",status="200",url_rule="/api/inventory/v1/tags"} 1.0
inventory_http_request_duration_seconds_bucket{le="0.075",method="GET",status="200",url_rule="/api/inventory/v1/tags"} 1.0
inventory_http_request_duration_seconds_bucket{le="0.1",method="GET",status="200",url_rule="/api/inventory/v1/tags"} 1.0
inventory_http_request_duration_seconds_bucket{le="0.25",method="GET",status="200",url_rule="/api/inventory/v1/tags"} 2.0
inventory_http_request_duration_seconds_bucket{le="0.5",method="GET",status="200",url_rule="/api/inventory/v1/tags"} 2.0
inventory_http_request_duration_seconds_bucket{le="0.75",method="GET",status="200",url_rule="/api/inventory/v1/tags"} 2.0
inventory_http_request_duration_seconds_bucket{le="1.0",method="GET",status="200",url_rule="/api/inventory/v1/tags"} 2.0
inventory_http_request_duration_seconds_bucket{le="2.5",method="GET",status="200",url_rule="/api/inventory/v1/tags"} 2.0
inventory_http_request_duration_seconds_bucket{le="5.0",method="GET",status="200",url_rule="/api/inventory/v1/tags"} 2.0
inventory_http_request_duration_seconds_bucket{le="7.5",method="GET",status="200",url_rule="/api/inventory/v1/tags"} 2.0
inventory_http_request_duration_seconds_bucket{le="10.0",method="GET",status="200",url_rule="/api/inventory/v1/tags"} 2.0
inventory_http_request_duration_seconds_bucket{le="+Inf",method="GET",status="200",url_rule="/api/inventory/v1/tags"} 2.0
inventory_http_request_duration_seconds_count{method="GET",status="200",url_rule="/api/inventory/v1/tags"} 2.0
inventory_http_request_duration_seconds_bucket{le="0.005",method="GET",status="200",url_rule="/api/inventory/v1/system_profile/sap_sids"} 0.0
inventory_http_request_duration_seconds_bucket{le="0.01",method="GET",status="200",url_rule="/api/inventory/v1/system_profile/sap_sids"} 0.0
inventory_http_request_duration_seconds_bucket{le="0.025",method="GET",status="200",url_rule="/api/inventory/v1/system_profile/sap_sids"} 0.0
inventory_http_request_duration_seconds_bucket{le="0.05",method="GET",status="200",url_rule="/api/inventory/v1/system_profile/sap_sids"} 0.0
inventory_http_request_duration_seconds_bucket{le="0.075",method="GET",status="200",url_rule="/api/inventory/v1/system_profile/sap_sids"} 0.0
inventory_http_request_duration_seconds_bucket{le="0.1",method="GET",status="200",url_rule="/api/inventory/v1/system_profile/sap_sids"} 0.0
inventory_http_request_duration_seconds_bucket{le="0.25",method="GET",status="200",url_rule="/api/inventory/v1/system_profile/sap_sids"} 1.0
inventory_http_request_duration_seconds_bucket{le="0.5",method="GET",status="200",url_rule="/api/inventory/v1/system_profile/sap_sids"} 1.0
inventory_http_request_duration_seconds_bucket{le="0.75",method="GET",status="200",url_rule="/api/inventory/v1/system_profile/sap_sids"} 1.0
inventory_http_request_duration_seconds_bucket{le="1.0",method="GET",status="200",url_rule="/api/inventory/v1/system_profile/sap_sids"} 1.0
inventory_http_request_duration_seconds_bucket{le="2.5",method="GET",status="200",url_rule="/api/inventory/v1/system_profile/sap_sids"} 1.0
inventory_http_request_duration_seconds_bucket{le="5.0",method="GET",status="200",url_rule="/api/inventory/v1/system_profile/sap_sids"} 1.0
inventory_http_request_duration_seconds_bucket{le="7.5",method="GET",status="200",url_rule="/api/inventory/v1/system_profile/sap_sids"} 1.0
inventory_http_request_duration_seconds_bucket{le="10.0",method="GET",status="200",url_rule="/api/inventory/v1/system_profile/sap_sids"} 1.0
inventory_http_request_duration_seconds_bucket{le="+Inf",method="GET",status="200",url_rule="/api/inventory/v1/system_profile/sap_sids"} 1.0
inventory_http_request_duration_seconds_count{method="GET",status="200",url_rule="/api/inventory/v1/system_profile/sap_sids"} 1.0
inventory_http_request_duration_seconds_bucket{le="0.005",method="GET",status="200",url_rule="/api/inventory/v1/system_profile/sap_system"} 0.0
inventory_http_request_duration_seconds_bucket{le="0.01",method="GET",status="200",url_rule="/api/inventory/v1/system_profile/sap_system"} 0.0
inventory_http_request_duration_seconds_bucket{le="0.025",method="GET",status="200",url_rule="/api/inventory/v1/system_profile/sap_system"} 0.0
inventory_http_request_duration_seconds_bucket{le="0.05",method="GET",status="200",url_rule="/api/inventory/v1/system_profile/sap_system"} 0.0
inventory_http_request_duration_seconds_bucket{le="0.075",method="GET",status="200",url_rule="/api/inventory/v1/system_profile/sap_system"} 1.0
inventory_http_request_duration_seconds_bucket{le="0.1",method="GET",status="200",url_rule="/api/inventory/v1/system_profile/sap_system"} 1.0
inventory_http_request_duration_seconds_bucket{le="0.25",method="GET",status="200",url_rule="/api/inventory/v1/system_profile/sap_system"} 1.0
inventory_http_request_duration_seconds_bucket{le="0.5",method="GET",status="200",url_rule="/api/inventory/v1/system_profile/sap_system"} 1.0
inventory_http_request_duration_seconds_bucket{le="0.75",method="GET",status="200",url_rule="/api/inventory/v1/system_profile/sap_system"} 1.0
inventory_http_request_duration_seconds_bucket{le="1.0",method="GET",status="200",url_rule="/api/inventory/v1/system_profile/sap_system"} 1.0
inventory_http_request_duration_seconds_bucket{le="2.5",method="GET",status="200",url_rule="/api/inventory/v1/system_profile/sap_system"} 1.0
inventory_http_request_duration_seconds_bucket{le="5.0",method="GET",status="200",url_rule="/api/inventory/v1/system_profile/sap_system"} 1.0
inventory_http_request_duration_seconds_bucket{le="7.5",method="GET",status="200",url_rule="/api/inventory/v1/system_profile/sap_system"} 1.0
inventory_http_request_duration_seconds_bucket{le="10.0",method="GET",status="200",url_rule="/api/inventory/v1/system_profile/sap_system"} 1.0
inventory_http_request_duration_seconds_bucket{le="+Inf",method="GET",status="200",url_rule="/api/inventory/v1/system_profile/sap_system"} 1.0
inventory_http_request_duration_seconds_count{method="GET",status="200",url_rule="/api/inventory/v1/system_profile/sap_system"} 1.0
inventory_http_request_duration_seconds_bucket{le="0.005",method="GET",status="200",url_rule="/api/inventory/v1/hosts"} 0.0
inventory_http_request_duration_seconds_bucket{le="0.01",method="GET",status="200",url_rule="/api/inventory/v1/hosts"} 0.0
inventory_http_request_duration_seconds_bucket{le="0.025",method="GET",status="200",url_rule="/api/inventory/v1/hosts"} 2.0
inventory_http_request_duration_seconds_bucket{le="0.05",method="GET",status="200",url_rule="/api/inventory/v1/hosts"} 3.0
inventory_http_request_duration_seconds_bucket{le="0.075",method="GET",status="200",url_rule="/api/inventory/v1/hosts"} 4.0
inventory_http_request_duration_seconds_bucket{le="0.1",method="GET",status="200",url_rule="/api/inventory/v1/hosts"} 4.0
inventory_http_request_duration_seconds_bucket{le="0.25",method="GET",status="200",url_rule="/api/inventory/v1/hosts"} 4.0
inventory_http_request_duration_seconds_bucket{le="0.5",method="GET",status="200",url_rule="/api/inventory/v1/hosts"} 4.0
inventory_http_request_duration_seconds_bucket{le="0.75",method="GET",status="200",url_rule="/api/inventory/v1/hosts"} 4.0
inventory_http_request_duration_seconds_bucket{le="1.0",method="GET",status="200",url_rule="/api/inventory/v1/hosts"} 4.0
inventory_http_request_duration_seconds_bucket{le="2.5",method="GET",status="200",url_rule="/api/inventory/v1/hosts"} 4.0
inventory_http_request_duration_seconds_bucket{le="5.0",method="GET",status="200",url_rule="/api/inventory/v1/hosts"} 4.0
inventory_http_request_duration_seconds_bucket{le="7.5",method="GET",status="200",url_rule="/api/inventory/v1/hosts"} 4.0
inventory_http_request_duration_seconds_bucket{le="10.0",method="GET",status="200",url_rule="/api/inventory/v1/hosts"} 4.0
inventory_http_request_duration_seconds_bucket{le="+Inf",method="GET",status="200",url_rule="/api/inventory/v1/hosts"} 4.0
inventory_http_request_duration_seconds_count{method="GET",status="200",url_rule="/api/inventory/v1/hosts"} 4.0
inventory_http_request_duration_seconds_bucket{le="0.005",method="GET",status="200",url_rule="/api/inventory/v1/system_profile/operating_system"} 0.0
inventory_http_request_duration_seconds_bucket{le="0.01",method="GET",status="200",url_rule="/api/inventory/v1/system_profile/operating_system"} 0.0
inventory_http_request_duration_seconds_bucket{le="0.025",method="GET",status="200",url_rule="/api/inventory/v1/system_profile/operating_system"} 0.0
inventory_http_request_duration_seconds_bucket{le="0.05",method="GET",status="200",url_rule="/api/inventory/v1/system_profile/operating_system"} 1.0
inventory_http_request_duration_seconds_bucket{le="0.075",method="GET",status="200",url_rule="/api/inventory/v1/system_profile/operating_system"} 1.0
inventory_http_request_duration_seconds_bucket{le="0.1",method="GET",status="200",url_rule="/api/inventory/v1/system_profile/operating_system"} 1.0
inventory_http_request_duration_seconds_bucket{le="0.25",method="GET",status="200",url_rule="/api/inventory/v1/system_profile/operating_system"} 1.0
inventory_http_request_duration_seconds_bucket{le="0.5",method="GET",status="200",url_rule="/api/inventory/v1/system_profile/operating_system"} 1.0
inventory_http_request_duration_seconds_bucket{le="0.75",method="GET",status="200",url_rule="/api/inventory/v1/system_profile/operating_system"} 1.0
inventory_http_request_duration_seconds_bucket{le="1.0",method="GET",status="200",url_rule="/api/inventory/v1/system_profile/operating_system"} 1.0
inventory_http_request_duration_seconds_bucket{le="2.5",method="GET",status="200",url_rule="/api/inventory/v1/system_profile/operating_system"} 1.0
inventory_http_request_duration_seconds_bucket{le="5.0",method="GET",status="200",url_rule="/api/inventory/v1/system_profile/operating_system"} 1.0
inventory_http_request_duration_seconds_bucket{le="7.5",method="GET",status="200",url_rule="/api/inventory/v1/system_profile/operating_system"} 1.0
inventory_http_request_duration_seconds_bucket{le="10.0",method="GET",status="200",url_rule="/api/inventory/v1/system_profile/operating_system"} 1.0
inventory_http_request_duration_seconds_bucket{le="+Inf",method="GET",status="200",url_rule="/api/inventory/v1/system_profile/operating_system"} 1.0
inventory_http_request_duration_seconds_count{method="GET",status="200",url_rule="/api/inventory/v1/system_profile/operating_system"} 1.0
# HELP inventory_exporter_info Multiprocess metric
# TYPE inventory_exporter_info gauge
inventory_exporter_info{version="0.21.0"} 1.0
```

**Review by CodeHeeler — APPROVED** [review]
LGTM, thanks for figuring this out so quickly today!

**Review by thearifismail — APPROVED** [review]
LGTM

**Pull request merged**
