### PR TITLE
Set min/max for System Profile integers

### PR DESCRIPTION
**Pull request by kruai**
## Overview

This PR is being created to address [RHCLOUD-14535](https://issues.redhat.com/browse/RHCLOUD-14535).
It adds min/max values to System Profile int fields, since exceeding these values can lead to 5xx on our end.
inventory-schemas PR here: https://github.com/RedHatInsights/inventory-schemas/pull/67

## PR Checklist

- [x] Keep PR title short, ideally under 72 characters
- [ ] Descriptive comments provided in complex code blocks
- [ ] Tests: validate optimal/expected output
- [ ] Tests: validate exceptions and failure scenarios
- [ ] Tests: edge cases
- [ ] Documentation, if this PR changes the way other services interact with host inventory
- [x] Links to related PRs

## Secure Coding Practices Checklist GitHub Link

- https://github.com/RedHatInsights/secure-coding-checklist

## Secure Coding Checklist

- [ ] Input Validation
- [ ] Output Encoding
- [ ] Authentication and Password Management
- [ ] Session Management
- [ ] Access Control
- [ ] Cryptographic Practices
- [ ] Error Handling and Logging
- [ ] Data Protection
- [ ] Communication Security
- [ ] System Configuration
- [ ] Database Security
- [ ] File Management
- [ ] Memory Management
- [ ] General Coding Practices

### CODE REVIEW

**Review by thearifismail — COMMENTED** [review]
Shouldn't there be some tests testing values within and outside the range?

**Comment by kruai** [comment]
> Shouldn't there be some tests testing values within and outside the range?

No, we don't test System Profile values in the HBI repo; that's done in the inventory-schemas repo.
I added new test values to the PR I linked in the description.

**Review by thearifismail — APPROVED** [review]
LGTM

**Review by ryandillinfelton — APPROVED** [review]
LGTM, this was merged in Schemas :+1:

**Pull request merged**
