### PR TITLE
Add RBAC tests for system_profile

### PR DESCRIPTION
**Pull request by ryandillinfelton**
Since RBAC is getting enabled outside of CI I thought it'd be a good idea to add some tests making sure it works right for the new endpoint

### CODE REVIEW

**Review by tahmidefaz — APPROVED** [review]
LGTM :+1:

**Review by kruai — APPROVED** [review]

**Comment by thearifismail** [comment]
Any plan for dealing with the following warnings:
```
tests/test_system_profile.py::test_system_profile_sap_system_endpoint_response
tests/test_system_profile.py::test_system_profile_sap_system_endpoint_response
  /Users/aarif/.local/share/virtualenvs/ryan-vKFPkS0e/lib/python3.6/site-packages/prance/__init__.py:180: DeprecationWarning: Function 'semver.format_version' is deprecated. Deprecated since version 2.10.0.  This function will be removed in semver 3. Use 'str(versionobject)' instead.
    self.semver = semver.format_version(*version)

tests/test_system_profile.py::test_system_profile_sap_system_endpoint_response
  /Users/aarif/.local/share/virtualenvs/ryan-vKFPkS0e/lib/python3.6/site-packages/flask_sqlalchemy/utils.py:44: DeprecationWarning: The `SQLALCHEMY_POOL_SIZE` config option is deprecated and will be removed in v3.0.  Use `SQLALCHEMY_ENGINE_OPTIONS['pool_size']` instead.
    DeprecationWarning

tests/test_system_profile.py::test_system_profile_sap_system_endpoint_response
  /Users/aarif/.local/share/virtualenvs/ryan-vKFPkS0e/lib/python3.6/site-packages/flask_sqlalchemy/utils.py:44: DeprecationWarning: The `SQLALCHEMY_POOL_TIMEOUT` config option is deprecated and will be removed in v3.0.  Use `SQLALCHEMY_ENGINE_OPTIONS['pool_timeout']` instead.
    DeprecationWarning

-- Docs: https://docs.pytest.org/en/latest/warnings.html
```

**Comment by ryandillinfelton** [comment]
> Any plan for dealing with the following warnings:
> 
> ```
> tests/test_system_profile.py::test_system_profile_sap_system_endpoint_response
> tests/test_system_profile.py::test_system_profile_sap_system_endpoint_response
>   /Users/aarif/.local/share/virtualenvs/ryan-vKFPkS0e/lib/python3.6/site-packages/prance/__init__.py:180: DeprecationWarning: Function 'semver.format_version' is deprecated. Deprecated since version 2.10.0.  This function will be removed in semver 3. Use 'str(versionobject)' instead.
>     self.semver = semver.format_version(*version)
> 
> tests/test_system_profile.py::test_system_profile_sap_system_endpoint_response
>   /Users/aarif/.local/share/virtualenvs/ryan-vKFPkS0e/lib/python3.6/site-packages/flask_sqlalchemy/utils.py:44: DeprecationWarning: The `SQLALCHEMY_POOL_SIZE` config option is deprecated and will be removed in v3.0.  Use `SQLALCHEMY_ENGINE_OPTIONS['pool_size']` instead.
>     DeprecationWarning
> 
> tests/test_system_profile.py::test_system_profile_sap_system_endpoint_response
>   /Users/aarif/.local/share/virtualenvs/ryan-vKFPkS0e/lib/python3.6/site-packages/flask_sqlalchemy/utils.py:44: DeprecationWarning: The `SQLALCHEMY_POOL_TIMEOUT` config option is deprecated and will be removed in v3.0.  Use `SQLALCHEMY_ENGINE_OPTIONS['pool_timeout']` instead.
>     DeprecationWarning
> 
> -- Docs: https://docs.pytest.org/en/latest/warnings.html
> ```

those deprecation warnings appear in almost all of the test files. They might be worth addressing as tech debt in the future but I have no plans for fixing it in the meantime.

**Comment by thearifismail** [comment]
The warning in the previous comment should be fixed at some point. 

For now LGTM.

**Review by thearifismail — APPROVED** [review]

**Pull request merged**
