### PR TITLE
Remove old deployment template

### PR DESCRIPTION
**Pull request by kruai**
# Overview

This PR is being created to address [ESSNTL-3124](https://issues.redhat.com/browse/ESSNTL-3124).
Removes the old deployment template so we don't get confused.

## PR Checklist

- [x] Keep PR title short, ideally under 72 characters
- [ ] Descriptive comments provided in complex code blocks
- [ ] Tests: validate optimal/expected output
- [ ] Tests: validate exceptions and failure scenarios
- [ ] Tests: edge cases
- [ ] Recovers or fails gracefully during potential resource outages (e.g. DB, Kafka)
- [ ] Uses [type hinting](https://docs.python.org/3/library/typing.html), if convenient
- [ ] Documentation, if this PR changes the way other services interact with host inventory
- [ ] Links to related PRs

## Secure Coding Practices Documentation Reference

You can find documentation on this checklist [here](https://github.com/RedHatInsights/secure-coding-checklist).

## Secure Coding Checklist

- [ ] Input Validation
- [ ] Output Encoding
- [ ] Authentication and Password Management
- [ ] Session Management
- [ ] Access Control
- [ ] Cryptographic Practices
- [ ] Error Handling and Logging
- [ ] Data Protection
- [ ] Communication Security
- [ ] System Configuration
- [ ] Database Security
- [ ] File Management
- [ ] Memory Management
- [ ] General Coding Practices

### CODE REVIEW

**Review by thearifismail — DISMISSED** [review]
LGTM

**Comment by kruai** [comment]
Converted this to a draft until [the MR](https://gitlab.cee.redhat.com/service/app-interface/-/merge_requests/46396) is merged (just in case someone tries to merge it early)

**Review by CodeHeeler — DISMISSED** [review]
LGTM once the other merges and presumably the build will stop breaking.

**Review by thearifismail — APPROVED** [review]
LGTM

**Pull request merged**
