### PR TITLE
 Update wait command to fix PR check

### PR DESCRIPTION
**Pull request by BlakeHolifield**
Hot fix: wait on all deployments rather than oc rollout

## Overview

This PR is being created to address failing PR checks in the ephemeral env on v4.

### CODE REVIEW

**Review by thearifismail — DISMISSED** [review]
LGTM

**Review by ryandillinfelton — APPROVED** [review]

**Comment by BlakeHolifield** [comment]
Let's give this a chance to run before we merge it. Jenkins is currently getting flooded with PR builds so it may take a sec

**Comment by BlakeHolifield** [comment]
The bonfire syntax has changed, I'll update again

**Comment by kruai** [comment]
It looks like the build failed again. Is this still in progress?

**Comment by BlakeHolifield** [comment]
> It looks like the build failed again. Is this still in progress?

Yeah there is more than a single issue here. Just pushed a new commit.

**Comment by BlakeHolifield** [comment]
Okay this is working now and should be more robust. I'm going to rebase and squash all this and then we'll be good.

**Comment by BlakeHolifield** [comment]
Closing to use #816 instead

**Pull request closed without merging**
