### PR TITLE
🐛 Do not inline local references in the OpenAPI specification; introducing Translating Parser for Prance

### PR DESCRIPTION
**Pull request by Glutexo**
Adding a new Translating Parser from [prance-translating-parser](https://github.com/Glutexo/prance-translating-parser) that is going to be added to the [Prance](https://github.com/RonnyPfannschmidt/prance) library itself. It collects all referenced objects to a single document, not inlining anything.

**Asking @tahmidefaz and @RonnyPfannschmidt for a review** of the Translating Parser code in  _lib/translating_parser_. This pull request can be used to add this feature to the Host Inventory repository, so it can be tested and used even before this feature is added to Prance upstream. Primarily though it serves as a platform for the review of my existing code. After being approved, I can backport the changes and focus on upstream integration.

The code base of the Translating Parser is taken from the existing ResolvingParser that was recently patched by @tahmidefaz  to allow for some crude translation. Tests for the parser can be [found](https://github.com/Glutexo/prance-translating-parser/tree/master/tests) in the original repository.

This is intended to be a minimum viable product for the Inventory. Not all features of the original _ResolvingParser_ are supported. This includes options like encoding and strict mode as well as flags to limit the translation to only selected reference levels. There is no support for custom recursion handling as recursive references can be correctly translated. This includes the _NestedObject_ in the System Profile.

There are a few amendments to the Host Inventory codebase itself:

- Prance upgraded to the newest version. The new parser depends on new features. This required an upgrade of _Requests_ too.
- Added one missing _type: object_ clause to the API specification.
- Pointed the reference in _HostSystemProfileOut_ directly to _system_profile.spec.yaml#/$defs/SystemProfile_ and removed _api.spec.yaml#/components/schemas/SystemProfile_. Connexion does not handle references to schemas that are references themselves correctly.

### CODE REVIEW

**Comment by Glutexo** [comment]
Let’s focus now only on whether this version does not break anything (e.g. the recursive references) and fixes the inlining problem. Anything else like whatever needs to be done so this can go to Prance upstream or any additional features would be done and reviewed separately in follow-up tasks.

**Comment by RonnyPfannschmidt** [comment]
i'll verify this once i gave finished the api compatibility validation/testing on the basis of #825 (once i have figrued the output we need i can validate the details with prance

thanks for setting this up

**Comment by tahmidefaz** [comment]
@Glutexo Thanks for the PR! From my local tests, I didn't see any thing break with these changes. You need to resolve the merge conflict.

@kruai @ryandillinfelton @thearifismail anyone of you want to take a look at this PR?

**Comment by tahmidefaz** [comment]
Those who are reviewing, this is what gets fed into `connexion` from this changes: http://pastebin.test.redhat.com/963810

**Review by kruai — DISMISSED** [review]
LGTM. Take my approval with a grain of salt because most of this is new to me, but I don't see any major errors, and nothing's breaking.

**Comment by Glutexo** [comment]
Thanks for your 👍🏻, @kruai! Your review has been automatically dismissed by my rebase. May I ask for an additional ✅ ?

Resolved the _Pipfile.lock_ conflict.

**Comment by Glutexo** [comment]
@kruai, @tahmidefaz If you are interested in Prance and its translating parser, I‘d like to invite you to my Hackathon project, where I’d like to backport this feature to the upstream.

**Comment by Glutexo** [comment]
Just a note for @tahmidefaz: _pastebin.test.redhat.com_ is not accessible from the outside world. This is a Red Hat project, yet it is open source and so are open the issues, PRs and discussions.

**Review by tahmidefaz — APPROVED** [review]
@Glutexo Thanks for the information!

We need one more approval before merging :slightly_smiling_face:

**Comment by Glutexo** [comment]
Well, @kruai already approved, although with a grain of salt. The best would be to have one from @RonnyPfannschmidt, because I’d like to have feedback on the actual Parser code. But it is possible to comment on a closed PR and whatever changes would be necessary can be made in a subsequent PR. #agile

**Review by kruai — APPROVED** [review]

**Comment by Glutexo** [comment]
:shipit:

**Pull request merged**
