### PR TITLE
Configure multiprocess gunicorn + prometheus

### PR DESCRIPTION
**Pull request by kruai**
# Overview

This PR is being created to address [ESSNTL-3078](https://issues.redhat.com/browse/ESSNTL-3078).
It does the following:
- Upgrades `prometheus-flask-exporter` version
- Switch from using basic PrometheusMetrics server to GunicornInternalPrometheusMetrics server
- Remove call to `KafkaProducer.close()`, since that function does not exist; `KafkaConsumer` should be closed, but people recommend just flushing `KafkaProducer` upon exit

## PR Checklist

- [x] Keep PR title short, ideally under 72 characters
- [ ] Descriptive comments provided in complex code blocks
- [ ] Tests: validate optimal/expected output
- [ ] Tests: validate exceptions and failure scenarios
- [ ] Tests: edge cases
- [ ] Recovers or fails gracefully during potential resource outages (e.g. DB, Kafka)
- [ ] Uses [type hinting](https://docs.python.org/3/library/typing.html), if convenient
- [ ] Documentation, if this PR changes the way other services interact with host inventory
- [ ] Links to related PRs

## Secure Coding Practices Documentation Reference

You can find documentation on this checklist [here](https://github.com/RedHatInsights/secure-coding-checklist).

## Secure Coding Checklist

- [ ] Input Validation
- [ ] Output Encoding
- [ ] Authentication and Password Management
- [ ] Session Management
- [ ] Access Control
- [ ] Cryptographic Practices
- [ ] Error Handling and Logging
- [ ] Data Protection
- [ ] Communication Security
- [ ] System Configuration
- [ ] Database Security
- [ ] File Management
- [ ] Memory Management
- [ ] General Coding Practices

### CODE REVIEW

**Review by thearifismail — APPROVED** [review]
LGTM

**Review by CodeHeeler — APPROVED** [review]
I lack expertise in gunicorn, so you should get another reviewer as well if you want architectural feedback.  LGTM.

**Comment by kruai** [comment]
For posterity: I've just deployed the image in this PR, `pr-1251-be2c024`, to the ephemeral environment `ephemeral-toeeel` using 4 workers and 8 threads, and the pods spin up without restart or error.

**Review by thearifismail — APPROVED** [review]
LGTM

**Review by fstavela — APPROVED** [review]
LGTM

Hmm, the "all tests" pipeline keeps having the "Build timed out (after 30 minutes). Marking the build as failed.". There must have been something changed in app-interface or the Jenkins configuration because it was not behaving like that before. I've created a task for me to investigate and fix it: https://issues.redhat.com/browse/ESSNTL-3986

However, on my own env it works fine, so it's good to go.

**Comment by kruai** [comment]
> > For posterity: I've just deployed the image in this PR, `pr-1251-be2c024`, to the ephemeral environment `ephemeral-toeeel` using 4 workers and 8 threads, and the pods spin up without restart or error.
> 
> Thanks for doing that! Just in case, if you want to test changes to `clowdapp.yml`, that is not part of the built image, so you have to also set `--set-template-ref host-inventory=<commit-hash>` to your `bonfire deploy` command together with the new image, so in this case the commit hash would be `be2c02460a088a1328108d2d76b423137c4b11f6`.

I only changed the parameter value in `clowdapp.yml`; I replicated that by using `--set-parameter host-inventory/GUNICORN_WORKERS="4"`. But I'll try it out that way as well!

**Pull request merged**
