### PR TITLE
[NOMERGE] debug pr_check failure

### PR DESCRIPTION
**Pull request by bsquizz**

### CODE REVIEW

**Review by thearifismail — APPROVED** [review]

**Review by thearifismail — APPROVED** [review]

**Comment by kruai** [comment]
@thearifismail does `/retest` do anything? I thought that was just for app-sre-bot

**Comment by thearifismail** [comment]
Yes, `/retest` restarts a build without pushing any code changes.  I think
in app-sre `[test]` or `[retest]` is used.

**Comment by bsquizz** [comment]
[test]

**Pull request closed without merging**
