### PR TITLE
perf(cyndi): keep only the id and name fields in hosts.groups

### PR DESCRIPTION
**Pull request by skateman**
# Overview

This PR is being created to address [ESSNTL-xxxx](https://issues.redhat.com/browse/ESSNTL-xxxx).
(A description of your PR's changes, along with why/context to the PR, goes here.)

## PR Checklist

- [ ] Keep PR title short, ideally under 72 characters
- [ ] Descriptive comments provided in complex code blocks
- [x] Tests: validate optimal/expected output
- [x] Tests: validate exceptions and failure scenarios
- [ ] Tests: edge cases
- [ ] Recovers or fails gracefully during potential resource outages (e.g. DB, Kafka)
- [ ] Uses [type hinting](https://docs.python.org/3/library/typing.html), if convenient
- [ ] Documentation, if this PR changes the way other services interact with host inventory
- [ ] Links to related PRs

## Secure Coding Practices Documentation Reference

You can find documentation on this checklist [here](https://github.com/RedHatInsights/secure-coding-checklist).

## Secure Coding Checklist

- [ ] Input Validation
- [ ] Output Encoding
- [ ] Authentication and Password Management
- [ ] Session Management
- [ ] Access Control
- [ ] Cryptographic Practices
- [ ] Error Handling and Logging
- [ ] Data Protection
- [ ] Communication Security
- [ ] System Configuration
- [ ] Database Security
- [ ] File Management
- [ ] Memory Management
- [ ] General Coding Practices

### CODE REVIEW

**Comment by kruai** [comment]
Closing in favor of #1411.

**Comment by sthirugn** [comment]
@kruai can you please explain why this ticket is closed in favor of your ticket? I am wondering why you didnt review and provided comments here rather than opening a new PR on your own.

**Comment by kruai** [comment]
> @kruai can you please explain why this ticket is closed in favor of your ticket? I am wondering why you didnt review and provided comments here rather than opening a new PR on your own.

I did this for a few reasons:

- The changes in this PR do not only affect MQ messages and thus the data synced via Cyndi, but also the API responses, where we would like to keep that data.
- These changes were causing existing tests to fail
- @skateman notified me that he wasn't able to get the dev setup working, but also told me that this needed to go in ASAP to avoid DB performance and size issues

With these in mind, and since I'm very familiar with the code, I figured it would be quicker to just open a PR. Is that OK with you @sthirugn?

**Comment by sthirugn** [comment]
Thank you for the explanation @kruai 

We really like to see more developers across all Insights services learn and contribute to HBI. Anything you call can do towards this goal is much appreciated.

**Comment by kruai** [comment]
> Thank you for the explanation @kruai
> 
> We really like to see more developers across all Insights services learn and contribute to HBI. Anything you call can do towards this goal is much appreciated.

Sure thing @sthirugn. I guess the main thing that would help in this scenario is... @skateman can you please let us know what issues you had with your dev setup? If the steps in the README didn't work, we want to update them.

**Comment by skateman** [comment]
We were trying hard with @petrblaho to bring up the pipenv, without success :disappointed:

**Pull request closed without merging**
