### PR TITLE
Update System Profile schema

### PR DESCRIPTION
**Pull request by kruai**
# Overview

This PR is being created to address [ESSNTL-3672](https://issues.redhat.com/browse/ESSNTL-3672).
Updates our System Profile spec and commit version to the latest.

## PR Checklist

- [x] Keep PR title short, ideally under 72 characters
- [ ] Descriptive comments provided in complex code blocks
- [ ] Tests: validate optimal/expected output
- [ ] Tests: validate exceptions and failure scenarios
- [ ] Tests: edge cases
- [ ] Recovers or fails gracefully during potential resource outages (e.g. DB, Kafka)
- [ ] Uses [type hinting](https://docs.python.org/3/library/typing.html), if convenient
- [ ] Documentation, if this PR changes the way other services interact with host inventory
- [ ] Links to related PRs

## Secure Coding Practices Documentation Reference

You can find documentation on this checklist [here](https://github.com/RedHatInsights/secure-coding-checklist).

## Secure Coding Checklist

- [ ] Input Validation
- [ ] Output Encoding
- [ ] Authentication and Password Management
- [ ] Session Management
- [ ] Access Control
- [ ] Cryptographic Practices
- [ ] Error Handling and Logging
- [ ] Data Protection
- [ ] Communication Security
- [ ] System Configuration
- [ ] Database Security
- [ ] File Management
- [ ] Memory Management
- [ ] General Coding Practices

### CODE REVIEW

**Review by CodeHeeler — APPROVED** [review]
LGTM

**Review by thearifismail — APPROVED** [review]
LGTM

**Review by thearifismail — CHANGES_REQUESTED** [review]
@CodeHeeler Upon seeing the related PR for `xjoin-search`, I realized that this PR needs tests in `test_xjoin.py` using the new SP fields.

**Comment by CodeHeeler** [comment]
> @CodeHeeler Upon seeing the related PR for `xjoin-search`, I realized that this PR needed tests in `test_xjoin.py` using the new SP fields.

Thanks!  I think Zhamilya mentioned the same, I'll get to work on that.

**Comment by kruai** [comment]
> @CodeHeeler Upon seeing the related PR for `xjoin-search`, I realized that this PR needed tests in `test_xjoin.py` using the new SP fields.

@thearifismail  The System Profile fields are already all tested in the inventory-schemas repo [here](https://github.com/RedHatInsights/inventory-schemas/tree/master/tests). I don't think we need to write bespoke tests for each of them again in HBI, since it would just be testing the format of something we've already validated

**Comment by CodeHeeler** [comment]
> > @CodeHeeler Upon seeing the related PR for `xjoin-search`, I realized that this PR needed tests in `test_xjoin.py` using the new SP fields.
> 
> @thearifismail The System Profile fields are already all tested in the inventory-schemas repo [here](https://github.com/RedHatInsights/inventory-schemas/tree/master/tests). I don't think we need to write bespoke tests for each of them again in HBI, since it would just be testing the format of something we've already validated

Ok, sounds good to me. Don't want to duplicate effort.

**Review by thearifismail — APPROVED** [review]
I personally would like to add tests to HBI's/tests/xjoin-test.py but don't have a strong argument for against it either.

**Pull request merged**
