### PR TITLE
Adding tests for satellite

### PR DESCRIPTION
**Pull request by tahmidefaz**
## Overview

This PR is being created to address [this Jira](https://issues.redhat.com/browse/RHCLOUD-13151).

Adding test for hosts filtering with satellite identity.

## PR Checklist

- [x] Keep PR title short, ideally under 72 characters
- [ ] Descriptive comments provided in complex code blocks
- [x] Tests: validate optimal/expected output
- [ ] Tests: validate exceptions and failure scenarios
- [ ] Tests: edge cases
- [ ] Documentation, if this PR changes the way other services interact with host inventory
- [ ] Links to related PRs

## Secure Coding Practices Checklist GitHub Link

- https://github.com/RedHatInsights/secure-coding-checklist

## Secure Coding Checklist

- [ ] Input Validation
- [ ] Output Encoding
- [ ] Authentication and Password Management
- [ ] Session Management
- [ ] Access Control
- [ ] Cryptographic Practices
- [ ] Error Handling and Logging
- [ ] Data Protection
- [ ] Communication Security
- [ ] System Configuration
- [ ] Database Security
- [ ] File Management
- [ ] Memory Management
- [x] General Coding Practices

### CODE REVIEW

**Review by kruai — DISMISSED** [review]
LGTM, tbh. This already feels a little redundant to other tests, but it doesn't hurt. Can't think of other ways we'd want to test this without it being even more so!

**Review by ryandillinfelton — CHANGES_REQUESTED** [review]
The test you added looks good. However, in the PR to add support for satellite identities there were also changes made xjoin query generation, allowing satellite identities to add an `owner_id_filter`. I think we should have a test in `test_xjoin` that insures the owner_id filter is set correctly when querying the API with a satellite identity.

**Comment by tahmidefaz** [comment]
@kruai @ryandillinfelton added a test for the owner_id filter in xjoin query when using `SATELLITE_IDENTITY`. This should be good for another review. :slightly_smiling_face:

**Review by kruai — APPROVED** [review]
LGTM

**Review by ryandillinfelton — APPROVED** [review]
LTGM thanks!

**Pull request merged**
