### PR TITLE
Performance input: Cleanup payloads variables and functions

### PR DESCRIPTION
**Pull request by Glutexo**
* Removed unused variables, constants and functions.
* Ordered the objects so variables come before functions.
* Moved literal values and variables used only in one place to the respective place of usage.

### CODE REVIEW

**Comment by Glutexo** [comment]
And this one, @Jason-RH?

**Comment by Jason-RH** [comment]
This looks like it'll conflict with https://github.com/RedHatInsights/insights-host-inventory/pull/412

Do you have a preferred format you want to go with?

**Comment by Glutexo** [comment]
I‘ll rebase.

**Comment by Glutexo** [comment]
Rebased, reviewable, mergeable.

**Pull request merged**
