### PR TITLE
fix(RHINENG-12591): Fix message for unsupported filter field/operation

### PR DESCRIPTION
**Pull request by kruai**
# Overview

This PR is being created to address [RHINENG-12591](https://issues.redhat.com/browse/RHINENG-12591).
It improves the "invalid filter field" error message by making it clearer and adding more context. 
For the example request "GET /hosts?filter[system_profile][owner_id][not_eq]=123"...

- Before: "invalid filter field: not_eq"
- After: "Invalid operation or child node for owner_id: not_eq"

## PR Checklist

- [x] Keep PR title short, ideally under 72 characters
- [ ] Descriptive comments provided in complex code blocks
- [ ] Include raw query examples in the PR description, if adding/modifying SQL query
- [ ] Tests: validate optimal/expected output
- [x] Tests: validate exceptions and failure scenarios
- [x] Tests: edge cases
- [ ] Recovers or fails gracefully during potential resource outages (e.g. DB, Kafka)
- [x] Uses [type hinting](https://docs.python.org/3/library/typing.html), if convenient
- [ ] Documentation, if this PR changes the way other services interact with host inventory
- [ ] Links to related PRs

## Secure Coding Practices Documentation Reference

You can find documentation on this checklist [here](https://github.com/RedHatInsights/secure-coding-checklist).

## Secure Coding Checklist

- [ ] Input Validation
- [ ] Output Encoding
- [ ] Authentication and Password Management
- [ ] Session Management
- [ ] Access Control
- [ ] Cryptographic Practices
- [ ] Error Handling and Logging
- [ ] Data Protection
- [ ] Communication Security
- [ ] System Configuration
- [ ] Database Security
- [ ] File Management
- [ ] Memory Management
- [ ] General Coding Practices

### CODE REVIEW

**Review by thearifismail — COMMENTED** [review]
The code looks LGTM but shouldn't there be test explicitly testing `not_eq` operation?

**Review by fstavela — APPROVED** [review]
Works fine, thanks!

**Review by FabriciaDinizRH — APPROVED** [review]
LGTM

**Comment by kruai** [comment]
> The code looks LGTM but shouldn't there be test explicitly testing `not_eq` operation?

I could add a `not_eq` test case, but that was just an example. The point was that `not_eq` is not a valid operator or field (the correct equivalent is `neq`). Since we already had tests for invalid operations/fields, I just updated those

**Pull request merged**
