### PR TITLE
[HBISPSC-52] Rename installed_packages_delta

### PR DESCRIPTION
**Pull request by CodeHeeler**
Customer feedback requested renaming from delta to multiple to
be more clear.

## Overview

This PR is being created to address [this Jira](https://issues.redhat.com/browse/RHCLOUD-xxxxx).
(A description of your PR's changes goes here.)

## Secure Coding Practices Checklist GitHub Link

- https://github.com/RedHatInsights/secure-coding-checklist

## Secure Coding Checklist

- [x] Input Validation
- [ ] Output Encoding
- [ ] Authentication and Password Management
- [ ] Session Management
- [ ] Access Control
- [ ] Cryptographic Practices
- [ ] Error Handling and Logging
- [ ] Data Protection
- [ ] Communication Security
- [ ] System Configuration
- [ ] Database Security
- [ ] File Management
- [ ] Memory Management
- [x] General Coding Practices

### CODE REVIEW

**Comment by CodeHeeler** [comment]
Related PRs:
https://github.com/RedHatInsights/inventory-schemas/pull/56
https://github.com/RedHatInsights/insights-puptoo/pull/138

**Comment by RonnyPfannschmidt** [comment]
@kruai  do we need a accompanying database migration to rename the field in the places where it might have data ?

**Comment by kruai** [comment]
> @kruai do we need a accompanying database migration to rename the field in the places where it might have data ?

I think so, though I don't know what the process is for HBI. If we don't do a migration, the values that are in there now will be inaccessible and will need to be repopulated as the new field name. I assume that would be an issue, right @CodeHeeler ?

**Comment by CodeHeeler** [comment]
After further discussion on a call today, we decided that a better description and documentation clarifying that installed_packages is a duplicate free subset and those packages not included there, the delta, are in this field.  Long term, this field will be going away; it is not worth the added work to change the name for something that is not permanent.  Closing this and related PRs.  Thanks all for the in-depth discussion.

**Pull request closed without merging**
