### PR TITLE
Make it possible to configure more Clowder's CRD properties

### PR DESCRIPTION
**Pull request by jhutar**
# Overview

This makes it possible to deploy two different namespaces with HBI to one cluster

### CODE REVIEW

**Review by kruai — APPROVED** [review]

**Comment by jhutar** [comment]
Hello @thearifismail Could you please take a look why PR build failed?

**Comment by kruai** [comment]
> Hello @thearifismail Could you please take a look why PR build failed?

It appears that the same IQE test is failing for both this and #1165. @fstavela does this need to be fixed in HBI or in the test itself?

**Comment by fstavela** [comment]
> > Hello @thearifismail Could you please take a look why PR build failed?
> 
> It appears that the same IQE test is failing for both this and #1165. @fstavela does this need to be fixed in HBI or in the test itself?

I've prepared one MR for the tests for both https://github.com/RedHatInsights/xjoin-search/pull/159 and https://github.com/RedHatInsights/insights-host-inventory/pull/1157 and I wanted to merge it once they are ready, but since the xjoin PR is already merged, I will split that into 2 MRs and fix the test that is failing now.

**Comment by jhutar** [comment]
Thank you!

**Pull request merged**
