### PR TITLE
[WIP] Add owner id to system profile

### PR DESCRIPTION
**Pull request by thearifismail**
## Overview

This PR adds `owner_id` to a host['system_profile'] when missing.  At the moment, it deals with `identity['type'] == "System"`

When the reporter is `rhsm-conduit`, a system identity is created the `cn` is set to the `subscription_manager_id` from the host.

PROBLEM: when using a System Id, the xjoin search does not fetch even when elasticsearch shows that the desired hosts are present and the http response code is 200.  When an invalid key or wrong key is used, xjoin-search responds with response_code 400

TODO: 

1.  Add handling new host coming from mq but using basic-auth.
2. Fix tests to use identity when adding hosts using mq

## Secure Coding Practices Checklist GitHub Link

- https://github.com/RedHatInsights/secure-coding-checklist

## Secure Coding Checklist

- [ ] Input Validation
- [ ] Output Encoding
- [ ] Authentication and Password Management
- [ ] Session Management
- [ ] Access Control
- [ ] Cryptographic Practices
- [ ] Error Handling and Logging
- [ ] Data Protection
- [ ] Communication Security
- [ ] System Configuration
- [ ] Database Security
- [ ] File Management
- [ ] Memory Management
- [ ] General Coding Practices

### CODE REVIEW

**Comment by kruai** [comment]
@thearifismail I thought we collectively decided yesterday that the reporters would be setting the owner_id of the system profile that they pass in. Did you hear something else afterwards?

**Comment by thearifismail** [comment]
No.  I was working to make add_host with identity in metadata.

**Comment by iphands** [comment]
> Question for @lphiri and @iphands, what should the owner_id be set to when the identity['type'] == "User? Should it be not set or set to the account number?

I was pretty sure that the only time `owner_id` would be considered is if the current auth method is CertAuth...
That is the same as saying type: System + auth_method: CertAuth.
Which implies that if the type == User we should skip all owner_id logic (dont read or update it).

@lphiri am I off base there?

**Comment by thearifismail** [comment]
> I was pretty sure that the only time `owner_id` would be considered is if the current auth method is CertAuth...
> That is the same as saying type: System + auth_method: CertAuth.
> Which implies that if the type == User we should skip all owner_id logic (dont read or update it).
> 
> @lphiri am I off base there?

@iphands you're right and that's how it's been implemented.  I am sorry the context to my question was bad;  I thought I had to add `owner_ids` to existing systems.  I missed yesterday that all the reporters would add `owner_id` to their existing systems.

**Comment by lphiri** [comment]
> > Question for @lphiri and @iphands, what should the owner_id be set to when the identity['type'] == "User? Should it be not set or set to the account number?
> 
> I was pretty sure that the only time `owner_id` would be considered is if the current auth method is CertAuth...
> That is the same as saying type: System + auth_method: CertAuth.
> Which implies that if the type == User we should skip all owner_id logic (dont read or update it).
> 
> @lphiri am I off base there?

That is correct.

**Comment by thearifismail** [comment]
This PR has been replaced by https://github.com/RedHatInsights/insights-host-inventory/pull/814

**Pull request closed without merging**
