### PR TITLE
feat(ESSNTL-5389): Include platform_metadata for MQ messages from API requests

### PR DESCRIPTION
**Pull request by kruai**
# Overview

This PR is being created to address [ESSNTL-5389](https://issues.redhat.com/browse/ESSNTL-5389).
Adds a limited `platform_metadata` to MQ messages produced by API requests. It also reduces redundancy a bit, refactoring a couple of places that encoded/decoded the identity.

The docs are being updated in [MR 233](https://gitlab.cee.redhat.com/consoledot/consoledot.pages.redhat.com/-/merge_requests/233), which also addresses [ESSNTL-4047](https://issues.redhat.com/browse/ESSNTL-4047).

## PR Checklist

- [x] Keep PR title short, ideally under 72 characters
- [ ] Descriptive comments provided in complex code blocks
- [x] Tests: validate optimal/expected output
- [ ] Tests: validate exceptions and failure scenarios
- [ ] Tests: edge cases
- [ ] Recovers or fails gracefully during potential resource outages (e.g. DB, Kafka)
- [x] Uses [type hinting](https://docs.python.org/3/library/typing.html), if convenient
- [x] Documentation, if this PR changes the way other services interact with host inventory
- [x] Links to related PRs

## Secure Coding Practices Documentation Reference

You can find documentation on this checklist [here](https://github.com/RedHatInsights/secure-coding-checklist).

## Secure Coding Checklist

- [ ] Input Validation
- [ ] Output Encoding
- [ ] Authentication and Password Management
- [ ] Session Management
- [ ] Access Control
- [ ] Cryptographic Practices
- [ ] Error Handling and Logging
- [ ] Data Protection
- [ ] Communication Security
- [ ] System Configuration
- [ ] Database Security
- [ ] File Management
- [ ] Memory Management
- [ ] General Coding Practices

### CODE REVIEW

**Comment by fstavela** [comment]
@kruai Will you please add one more unit test for delete event too?

**Comment by fstavela** [comment]
/retest

Hmm, the PR check was aborted for some reason

**Comment by kruai** [comment]
> @kruai Will you please add one more unit test checking correct identity in delete event too?

I actually hadn't accounted for deletes. I've now implemented that, and updated `assert_delete_event_is_valid` so that all API-host-delete tests now also validate the platform_metadata for the produced messages.

**Review by thearifismail — DISMISSED** [review]
The code LGTM but the amount of code added just to include identity to events feels too much and too complicated.  I am wondering if adding identity to events could be simplified.

**Comment by kruai** [comment]
It appears that the failing IQE tests are caused by MQ messages not lining up with the tests' expectations. @fstavela can you confirm, and should I hold off on merging?

**Comment by kruai** [comment]
Actually, come to think of it, it may be worth it to add the `user` field to the identity on those tests. When the Identity type is "User", the `user` object is required, unless that requirement changed. I could also make it optional in HBI, but only if those are the reqs. WDYT @fstavela?

**Comment by fstavela** [comment]
@kruai The tests found a couple issues:

- I can't create/update host if I don't provide `account_number` in the identity. Since we use `org_id` as an account identificator, `account_number` shouldn't be required. Here is a traceback:
```
[2023-11-09 12:15:20,166] [1] [139811031322880] [inventory.app.queue.queue] [ERROR] Unable to process message
Traceback (most recent call last):
File "/opt/app-root/src/app/queue/queue.py", line 92, in _get_identity
identity = Identity(identity)
File "/opt/app-root/src/app/auth/identity.py", line 65, in __init__
result = IdentitySchema().load(obj)
File "/usr/local/lib/python3.8/site-packages/marshmallow/schema.py", line 722, in load
return self._do_load(
File "/usr/local/lib/python3.8/site-packages/marshmallow/schema.py", line 908, in _do_load
self.handle_error(exc, data, many=many, partial=partial)
File "/opt/app-root/src/app/auth/identity.py", line 115, in handle_error
raise ValueError(err.messages)
ValueError: {'account_number': ['Field may not be null.']}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "/opt/app-root/src/app/queue/queue.py", line 292, in handle_message
output_host, host_id, insights_id, operation_result = message_operation(
File "/opt/app-root/src/app/queue/queue.py", line 247, in add_host
identity = _get_identity(host_data, platform_metadata)
File "/opt/app-root/src/app/queue/queue.py", line 94, in _get_identity
raise ValidationException(str(e))
app.exceptions.ValidationException: {'account_number': ['Field may not be null.']}
```

- It looks like HBI stopped producing notification error messages (for example, try to not provide org_id in the identity).

**Comment by thearifismail** [comment]
> @kruai The tests found a couple issues:
> 
>     * I can't create/update host if I don't provide `account_number` in the identity. Since we use `org_id` as an account identificator, `account_number` shouldn't be required. Here is a traceback:

@fstavela, this is strange.  Since `org_id` became a `required` attribute in identity, `account` has been removed from the [identity](https://github.com/RedHatInsights/insights-host-inventory/blob/909bad7095102515bcb6cf71f370acce95d7f900/utils/payloads.py#L10) used for creating hosts by our test utility.

**Comment by kruai** [comment]
> > @kruai The tests found a couple issues:
> > ```
> > * I can't create/update host if I don't provide `account_number` in the identity. Since we use `org_id` as an account identificator, `account_number` shouldn't be required. Here is a traceback:
> > ```
> 
> @fstavela, this is strange. Since `org_id` became a `required` attribute in identity, `account` has been removed from the [identity](https://github.com/RedHatInsights/insights-host-inventory/blob/909bad7095102515bcb6cf71f370acce95d7f900/utils/payloads.py#L10) used for creating hosts by our test utility.

Yep, though it looks like the account number was still required when the identity was provided via API header. My latest push should have resolved that (still looking at the notifs issue)

**Pull request merged**
