### PR TITLE
Add SLI section to grafana [RHCLOUD-10103]

### PR DESCRIPTION
**Pull request by ryandillinfelton**
Adds a section highlighting metrics related to our service level objectives.

Service Level Indicators
- Latency of HTTP requests
- Number of HTTP 5xx responses
- Consumer lag on ingress topics
- Number of ingress processing errors
- Not processing any messages over a given period of time (current: 5mins)

SLI_grafana_section

### CODE REVIEW

**Review by kruai — APPROVED** [review]
Looks good!

**Review by kruai — CHANGES_REQUESTED** [review]
As discussed in the chit-chat meeting, the kibana links need to be updated.

**Comment by ryandillinfelton** [comment]
I've updated the Kibana links

**Review by kruai — APPROVED** [review]
Looks good with the Kibana links!

**Review by tahmidefaz — APPROVED** [review]
LGTM :+1:

**Comment by thearifismail** [comment]
LGTM.  This is what I see but there is more below the screen.
PR746

**Pull request merged**
