### PR TITLE
fix(RHINENG-9037) More XJoin migration bugfixes

### PR DESCRIPTION
**Pull request by kruai**
# Overview

This PR is being created to address the most recent bugs identified in [RHINENG-9037](https://issues.redhat.com/browse/RHINENG-9037):

- If you use /hosts/<hosts_ids> and no hosts are found, it now returns HTTP 200 with an empty list instead of HTTP 404.
- If you filter on multiple values for an array-type field, it now uses "AND" logic.
- If you don't include an operator when filtering on an array-type field, it uses "contains" implicitly.
- If you filter on operating_system with multiple range operations (gt, lt, etc), it combines those using "AND".
- If you filter on operating_system without including a minor version, it now uses the appropriate logic to ignore the minor version (the logic is a bit complicated, but I documented it pretty thoroughly).
- If you filter on an integer field and set the value to blank or a non-integer value, it now returns HTTP 400 with a descriptive error message.
- Filtering on display_name and hostname_or_id now works with wildcards (e.g. "1*m" matches "HkqL12lmIW").
- Filtering integer fields on nil/not_nil now works.
- Filtering on big ints now works (e.g. system_memory_bytes == 3453124492938321).
- Sorting by `group_name` ASC now puts ungrouped hosts at the top, and DESC puts them at the end.
- The `/system_profile/operating_system` endpoint now no longer returns HTTP 500 when there are hosts with no operating_system field.

## PR Checklist

- [x] Keep PR title short, ideally under 72 characters
- [x] Descriptive comments provided in complex code blocks
- [x] Tests: validate optimal/expected output
- [x] Tests: validate exceptions and failure scenarios
- [x] Tests: edge cases
- [ ] Recovers or fails gracefully during potential resource outages (e.g. DB, Kafka)
- [x] Uses [type hinting](https://docs.python.org/3/library/typing.html), if convenient
- [ ] Documentation, if this PR changes the way other services interact with host inventory
- [ ] Links to related PRs

## Secure Coding Practices Documentation Reference

You can find documentation on this checklist [here](https://github.com/RedHatInsights/secure-coding-checklist).

## Secure Coding Checklist

- [ ] Input Validation
- [ ] Output Encoding
- [ ] Authentication and Password Management
- [ ] Session Management
- [ ] Access Control
- [ ] Cryptographic Practices
- [ ] Error Handling and Logging
- [ ] Data Protection
- [ ] Communication Security
- [ ] System Configuration
- [ ] Database Security
- [ ] File Management
- [ ] Memory Management
- [ ] General Coding Practices

### CODE REVIEW

**Review by fpjrh — APPROVED** [review]
Read through the details of all changes and they look good.

**Review by chambridge — APPROVED** [review]

**Review by FabriciaDinizRH — APPROVED** [review]

**Pull request merged**
