### PR TITLE
feat(ESSNTL-4617, ESSNTL-4689, ESSNTL-4694): Address groups MQ issues

### PR DESCRIPTION
**Pull request by kruai**
# Overview

This PR is being created to address [ESSNTL-4617](https://issues.redhat.com/browse/ESSNTL-4617), [ESSNTL-4689](https://issues.redhat.com/browse/ESSNTL-4689), [ESSNTL-4694](https://issues.redhat.com/browse/ESSNTL-4694).
It restructures our groups MQ implementation to address the above bugs. It does the following:

- Moves session_guards and MQ production so that messages are only produced after all of the requested DB changes have been successfully committed
- Removes 2 unused functions
- Removes some unnecessary parameters from functions
- Refreshes host data before producing MQ messages so that the host's timestamps are accurate

This PR also obsoletes #1303, as it fixes broader implementation issues.

## PR Checklist

- [x] Keep PR title short, ideally under 72 characters
- [x] Descriptive comments provided in complex code blocks
- [x] Tests: validate optimal/expected output
- [x] Tests: validate exceptions and failure scenarios
- [ ] Tests: edge cases
- [ ] Recovers or fails gracefully during potential resource outages (e.g. DB, Kafka)
- [ ] Uses [type hinting](https://docs.python.org/3/library/typing.html), if convenient
- [ ] Documentation, if this PR changes the way other services interact with host inventory
- [ ] Links to related PRs

## Secure Coding Practices Documentation Reference

You can find documentation on this checklist [here](https://github.com/RedHatInsights/secure-coding-checklist).

## Secure Coding Checklist

- [ ] Input Validation
- [ ] Output Encoding
- [ ] Authentication and Password Management
- [ ] Session Management
- [ ] Access Control
- [ ] Cryptographic Practices
- [ ] Error Handling and Logging
- [ ] Data Protection
- [ ] Communication Security
- [ ] System Configuration
- [ ] Database Security
- [ ] File Management
- [ ] Memory Management
- [ ] General Coding Practices

### CODE REVIEW

**Review by CodeHeeler — COMMENTED** [review]
LGTM once tests are passing

**Comment by kruai** [comment]
> LGTM once tests are passing

Huh, that's strange... they pass locally. I'll rebase and see if it happens again

**Comment by CodeHeeler** [comment]
> > LGTM once tests are passing
> 
> Huh, that's strange... they pass locally. I'll rebase and see if it happens again

Actually, I think the same tests are failing for arif's PR which is just a readme so it may be something larger going on that started recently.

**Review by thearifismail — DISMISSED** [review]
LGTM

**Review by CodeHeeler — DISMISSED** [review]

**Comment by fstavela** [comment]
The tests don't even run. The PR check can't build the image. It fails on this step:
`STEP 12/17: RUN python -m pip install --upgrade pip setuptools wheel &&     python -m pip install pipenv &&     pipenv install --system --dev`
With a lot of messages similar to this:
`An error occurred while installing atomicwrites==1.4.1 ; python_version >= '2.7' and python_version not in '3.0, 3.1, 3.2, 3.3' --hash=sha256:81b2c9071a49367a7f770170e5eec8cb66567cfbbc8c73d20ce5ca4a8d71cf11! Will try again.`

**Comment by fstavela** [comment]
It's still happening. But our Dockerfile hasn't been changed in 2 months. I don't know what is wrong.

**Comment by fstavela** [comment]
It looks like we are using very old version of `coverage` package, which has some deprecated configuration and it's failing to install that package during the image building.

**Comment by fstavela** [comment]
I created this PR to address the image building issue: https://github.com/RedHatInsights/insights-host-inventory/pull/1307

**Comment by fstavela** [comment]
Based on the failed tests, it looks like we can't create an empty group - it will error out with error 500.

**Comment by kruai** [comment]
> Based on the failed tests, it looks like we can't create an empty group - it will error out with error 500.

I've updated it so that it works if you omit the `host_ids` field entirely, and added a test to validate that.

**Review by thearifismail — APPROVED** [review]
LGTM

**Review by strider — APPROVED** [review]

**Pull request merged**
