### PR TITLE
Fix the floorist query

### PR DESCRIPTION
**Pull request by fijshion**
# Overview

This PR is being created to address [ESSNTL-xxxx](https://issues.redhat.com/browse/ESSNTL-xxxx).
(A description of your PR's changes, along with why/context to the PR, goes here.)

## PR Checklist

- [ ] Keep PR title short, ideally under 72 characters
- [ ] Descriptive comments provided in complex code blocks
- [ ] Tests: validate optimal/expected output
- [ ] Tests: validate exceptions and failure scenarios
- [ ] Tests: edge cases
- [ ] Recovers or fails gracefully during potential resource outages (e.g. DB, Kafka)
- [ ] Documentation, if this PR changes the way other services interact with host inventory
- [ ] Links to related PRs

## Secure Coding Practices Documentation Reference

You can find documentation on this checklist [here](https://github.com/RedHatInsights/secure-coding-checklist).

## Secure Coding Checklist

- [ ] Input Validation
- [ ] Output Encoding
- [ ] Authentication and Password Management
- [ ] Session Management
- [ ] Access Control
- [ ] Cryptographic Practices
- [ ] Error Handling and Logging
- [ ] Data Protection
- [ ] Communication Security
- [ ] System Configuration
- [ ] Database Security
- [ ] File Management
- [ ] Memory Management
- [ ] General Coding Practices

### CODE REVIEW

**Review by kruai — APPROVED** [review]

**Comment by fijshion** [comment]
@kruai anything blocking this from being merged?

**Comment by kruai** [comment]
@fijshion Not from my end. We just require at least 2 approvals before something can be merged. @ryandillinfelton @thearifismail can you please review this as well?

**Comment by kruai** [comment]
@fijshion Actually, screw it. If it's broken right now and this will fix it, I'm going to merge using my admin powers. If y'all determine there's something wrong with this, LMK and we can revert it.

**Comment by fijshion** [comment]
ty!

**Pull request merged**
