### PR TITLE
ESSNTL-3503: Notification messages bugs

### PR DESCRIPTION
**Pull request by FabriciaDinizRH**
# Overview

This PR is being created to address [ESSNTL-3503](https://issues.redhat.com/browse/ESSNTL-3503).
This PR improves exception handling so that the following cases produce notification messages:
 - none of the canonical facts are provided
 - insights_id as a list containing a valid id
 - identity validation errors

## PR Checklist

- [x] Keep PR title short, ideally under 72 characters
- [ ] Descriptive comments provided in complex code blocks
- [x] Tests: validate optimal/expected output
- [x] Tests: validate exceptions and failure scenarios
- [ ] Tests: edge cases
- [ ] Recovers or fails gracefully during potential resource outages (e.g. DB, Kafka)
- [ ] Uses [type hinting](https://docs.python.org/3/library/typing.html), if convenient
- [ ] Documentation, if this PR changes the way other services interact with host inventory
- [ ] Links to related PRs

## Secure Coding Practices Documentation Reference

You can find documentation on this checklist [here](https://github.com/RedHatInsights/secure-coding-checklist).

## Secure Coding Checklist

- [ ] Input Validation
- [ ] Output Encoding
- [ ] Authentication and Password Management
- [ ] Session Management
- [ ] Access Control
- [ ] Cryptographic Practices
- [ ] Error Handling and Logging
- [ ] Data Protection
- [ ] Communication Security
- [ ] System Configuration
- [ ] Database Security
- [ ] File Management
- [ ] Memory Management
- [ ] General Coding Practices

### CODE REVIEW

**Review by CodeHeeler — DISMISSED** [review]
LGTM.  You weren't kidding about there being a lot of lines of test code to update.  Thanks for taking care of this!

**Review by CodeHeeler — APPROVED** [review]
LGTM, thanks for adding the additional case

**Review by kruai — APPROVED** [review]
LGTM. Thanks for correcting some spelling as well!

**Review by thearifismail — APPROVED** [review]

**Pull request merged**
