### PR TITLE
Add checks to Identity constructor

### PR DESCRIPTION
**Pull request by kruai**
## Overview

This PR is being created to address [RHCLOUD-13572](https://issues.redhat.com/browse/RHCLOUD-13572).
It adds checks to the Identity constructor so that we raise ValueErrors instead of KeyErrors. It also simplifies/organizes the logic to make it easier to read.

## PR Checklist

- [x] Keep PR title short, ideally under 72 characters
- [x] Descriptive comments provided in complex code blocks
- [x] Tests: validate optimal/expected output
- [x] Tests: validate exceptions and failure scenarios
- [x] Tests: edge cases
- [ ] Documentation, if this PR changes the way other services interact with host inventory
- [ ] Links to related PRs

## Secure Coding Practices Checklist GitHub Link

- https://github.com/RedHatInsights/secure-coding-checklist

## Secure Coding Checklist

- [x] Error Handling and Logging
- [x] General Coding Practices

### CODE REVIEW

**Comment by thearifismail** [comment]
What this PR is doing is already handled by [Identity.validate()](https://github.com/RedHatInsights/insights-host-inventory/blob/1b570d601b6f9bb089fd953203a65527525bf022/app/auth/identity.py#L98).

IMO, the `Identity.validate()` and the Identity constructor should be merged, i.e. the Identity class should be restructured.  Even if this PR is merged it does not solved the problem reported by @fstavela in [RHCLOUD-11801](https://issues.redhat.com/browse/RHCLOUD-11801?focusedCommentId=16018362&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-16018362).

**Comment by kruai** [comment]
> What this PR is doing is already handled by [Identity.validate()](https://github.com/RedHatInsights/insights-host-inventory/blob/1b570d601b6f9bb089fd953203a65527525bf022/app/auth/identity.py#L98)?
> 
> IMO, the `Identity.validate()` and the Identity constructor should be merged, i.e. the Identity class should be restructured. Even if this PR is merged it does not solved the problem reported by @fstavela in [RHCLOUD-11801](https://issues.redhat.com/browse/RHCLOUD-11801?focusedCommentId=16018362&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-16018362).

This PR wasn't made to address RHCLOUD-11801... it was made to address RHCLOUD-13572. The goal was to raise proper exceptions instead of causing KeyErrors (causing HTTP 500). Do you mean that this PR is duplicating work that you're doing for RHCLOUD-11801?

**Comment by thearifismail** [comment]
> Do you mean that this PR is duplicating work that you're doing for RHCLOUD-11801?

Yes, it was done a while back to address the same problem of reporting the following:`{
    "detail": "Provided apikey is not valid",
    "status": 401,
    "title": "Unauthorized",
    "type": "about:blank"
}`

This PR handles the missing user and system in the constructor and mine waits until `identity.validate()` is called.  I ran your code and got the exact same message.  Your code is slightly different and I had hoped that it might bypass the `"detail": "Provided apikey is not valid"` but it did not.

Irregardless of what type exception is thrown, the message passed back to the client is form `flask` NOT our.  I tried using `flask.abort(401, "User field not set on provided user-type Identity")` but still got `{
    "detail": "Provided apikey is not valid",
    "status": 401,
    "title": "Unauthorized",
    "type": "about:blank"
}`

**Comment by kruai** [comment]
> > Do you mean that this PR is duplicating work that you're doing for RHCLOUD-11801?
> 
> Yes, it was done a while back to address the same problem of reporting the following:`{ "detail": "Provided apikey is not valid", "status": 401, "title": "Unauthorized", "type": "about:blank" }`
> 
> This PR handles the missing user and system in the constructor and mine waits until `identity.validate()` is called. I ran your code and got the exact same message. Your code is slightly different and I had hoped that it might bypass the `"detail": "Provided apikey is not valid"` but it did not.
> 
> Irregardless of what type exception is thrown, the message passed back to the client is form `flask` NOT our. I tried using `flask.abort(401, "User field not set on provided user-type Identity")` but still got `{ "detail": "Provided apikey is not valid", "status": 401, "title": "Unauthorized", "type": "about:blank" }`

I get what you're saying for API requests, but this issue affects the message queue as well. This is trying to address the errors that you can see in this [Kibana query](https://kibana-kibana.5a9f.insights-dev.openshiftapps.com/app/kibana#/discover?_g=(refreshInterval:(pause:!t,value:0),time:(from:now-24h,mode:quick,to:now))&_a=(columns:!(_source),index:d2da0310-7048-11e9-a501-7998195d35a8,interval:auto,query:(language:lucene,query:'@log_stream:%20%22inventory-mq-%22%20AND%20levelname:%20%22ERROR%22%20AND%20@message:%20%22KeyError%22'),sort:!('@timestamp',desc))).

**Comment by thearifismail** [comment]
> It's trying to make sure that a ValueError with a descriptive message is thrown instead of a KeyError, while it would appear that the Jira you're referencing is to make the API show the specific message from the ValueErrors instead of the general one we're seeing now. Is that accurate @thearifismail?

Yes.  IMO, all the `validate()` method validating individual parameters should be in the constructor.  That's said, if you're comfortable with splitting the validation between the `constructor` and `validate` method, like in this PR, I am OK and can approve it.

**Comment by kruai** [comment]
> > It's trying to make sure that a ValueError with a descriptive message is thrown instead of a KeyError, while it would appear that the Jira you're referencing is to make the API show the specific message from the ValueErrors instead of the general one we're seeing now. Is that accurate @thearifismail?
> 
> Yes. IMO, all the `validate()` method validating individual parameters should be in the constructor. That's said, if you're comfortable with splitting the validation between the `constructor` and `validate` method, like in this PR, I am OK and can approve it.

That feels a little out of scope for what this was trying to do, but I agree with you, based on how we're doing validation. I'll consolidate the constructor and validation functions and update the references to them

**Comment by kruai** [comment]
OK, so... by request, I've combined the constructor and validator for Identity. This is ready for another review whenever!

**Review by tahmidefaz — APPROVED** [review]
Looks good! :+1:

**Review by thearifismail — APPROVED** [review]
LGTM

**Pull request merged**
