### PR TITLE
Add external listener to Kafka

### LINKED ISSUE #393: Kafka client doesn’t resolve localhost on a Mac
Currently, our development [docker-compose](https://github.com/RedHatInsights/insights-host-inventory/blob/4b377d01559b22e374341c9cb15454a3dff61087/dev.yml) file configures Kafka to use only a [single](https://github.com/RedHatInsights/insights-host-inventory/blob/4b377d01559b22e374341c9cb15454a3dff61087/dev.yml#L24) advertised listener. This listener is used both for the internal communication inside Docker and for the communication with the outside world – our app. The only way to use this listener is to create a _hosts_ entry for _kafka_ pointing to _127.0.0.1_ to mimic the internal Docker environment.

```yaml
…
services:
  …
  kafka:
    …
    environment:
        …
        - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:29092
        …
```

```
127.0.0.1 kafka
```

This is a mere workaround and there is a better way to configure the advertised listeners: to have one for the internal communication and one for the external. Here is a nice, understandable [tl;dr](https://rmoff.net/2018/08/02/kafka-listeners-explained/) for that.

```yaml
…
services:
  …
  kafka:
    …
    environment:
        …
        - KAFKA_LISTENERS=INTERNAL://kafka:9092,EXTERNAL://kafka:29092
        - KAFKA_ADVERTISED_LISTENERS=INTERNAL://kafka:9092,EXTERNAL://localhost:29092
        - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
        - KAFKA_INTER_BROKER_LISTENER_NAME=INTERNAL
        …
```

Although this is the “correct” settings, there is still a problem with that. If Kafka is configured to use _localhost_ as a hostname for external connection, the Inventory app cannot connect, failing with a _NoBrokersAvailable_ error. At least on a Mac.

```
kafka.errors.NoBrokersAvailable: NoBrokersAvailable
```

The reason is that _localhost_ is a special hostname that resolves to several IP addresses. The version of _kafka-python_ we [use](https://github.com/RedHatInsights/insights-host-inventory/blob/4b377d01559b22e374341c9cb15454a3dff61087/Pipfile.lock#L245) (1.3.5) doesn’t try all the addresses and fails fast if it cannot connect using the first in order.

This is a known [issue](https://github.com/dpkp/kafka-python/issues/1308) and has been [fixed](https://github.com/dpkp/kafka-python/pull/1411) already. However, the Kafka client package is listed under two different names on PyPI:

* [_kafka_](https://pypi.org/project/kafka/), which we are [using](https://github.com/RedHatInsights/insights-host-inventory/blob/4b377d01559b22e374341c9cb15454a3dff61087/Pipfile#L30), does not receive updates any more and the last release [_1.3.5_](https://pypi.org/project/kafka/1.3.5/) has the aforementioned bug.
* [_kafka-python_](https://pypi.org/project/kafka-python/) with the latest version being [_1.4.6_](https://pypi.org/project/kafka-python/1.4.6/) where the bug is already fixed

When the newer version is used, it is possible to connect to Kafka using the _localhost_ advertised listener.

Steps to reproduce:

1. Deploy the fixed [_dev.yml_](https://github.com/Glutexo/insights-host-inventory/blob/kafka_listeners/dev.yml) _docker-compose_ bundle. `docker-compose -f dev.yml up`
2. Make sure you have the _29092_ port properly forwarded to Docker and possibly Docker-machine. Following Python code can help:

```python
import socket
print(socket.getaddrinfo("localhost", 29092))'
```

3. Make sure you don’t have a _kafka_ entry in _/etc/hosts_.

```
$ ping kafka                                                                    
ping: cannot resolve kafka: Unknown host
```

4. Run the application with proper Kafka configuration.

```bash
$ KAFKA_TOPIC=platform.system-profile KAFKA_EVENT_TOPIC=platform.inventory.events KAFKA_GROUP=inventory KAFKA_BOOTSTRAP_SERVERS=localhost:29092 pipenv run python run_gunicorn.py
```

5. See that it crashes, because of not being able to connect to Kafka.

```
kafka.errors.NoBrokersAvailable: NoBrokersAvailable
```

6. Upgrade the _kafka-python_ package to the fixed version.

```
$ pipenv run pip uninstall kafka
$ pipenv run pip install kafka-python
```

7. Restart the application and see that it connects to Kafka without any issues.

If the steps above don’t work for you, please drop a comment.

### PR DESCRIPTION
**Pull request by Glutexo**
Configure the [Kafka](https://github.com/Glutexo/insights-host-inventory/blob/c27951b90fe4e360f56a25fe41d251972f3692a2/dev.yml#L17) Docker container to advertise separate [listeners](https://github.com/Glutexo/insights-host-inventory/blob/c27951b90fe4e360f56a25fe41d251972f3692a2/dev.yml#L25) for internal and external communication. This allows to use the _localhost_ hostname to connect to Kafka from outside Docker. Thanks to that it’s no longer necessary to have a _hosts_ record redirecting the _kafka_ hostname, mimicking the internal Docker namespace.

For this configuration to work properly on all platforms (namely on a Mac), replaced the [_kafka_](https://github.com/RedHatInsights/insights-host-inventory/blob/4b377d01559b22e374341c9cb15454a3dff61087/Pipfile#L30) dependency with [_kafka-python_](https://github.com/Glutexo/insights-host-inventory/blob/d3ccbaa07719097877b083b02d7c31ae710057d0/Pipfile#L30). It is the same library, but the latter has newer versions available, fixing the bug. Upgraded thus to [_1.4.6_](https://github.com/Glutexo/insights-host-inventory/blob/d3ccbaa07719097877b083b02d7c31ae710057d0/Pipfile.lock#L245).

Changed the default value for the [_bootstrap_servers_](https://github.com/Glutexo/insights-host-inventory/blob/d3ccbaa07719097877b083b02d7c31ae710057d0/app/config.py#L34) configuration value. It is just a cosmetic change, because the default is [never used](https://github.com/Glutexo/insights-host-inventory/blob/d3ccbaa07719097877b083b02d7c31ae710057d0/app/config.py#L36).

Fixes #393.

### CODE REVIEW

**Comment by Glutexo** [comment]
It’s exactly as you wrote, @dehort. It’s all described in this nice [article](https://rmoff.net/2018/08/02/kafka-listeners-explained/). The bootstrap server returns an address of brokers to connect to, that means that the server must report an address that is reachable from your environment. You can use the [_kafkacat_](https://github.com/edenhill/kafkacat) tool to see that:

```
$ kafkacat -L -b localhost:29092                                                                                                       
Metadata for all topics (from broker -1: localhost:29092/bootstrap):
 1 brokers:
  broker 1 at kafka:29092 (controller)
…
```

**Comment by Glutexo** [comment]
Rebased. Will do again after https://github.com/RedHatInsights/insights-host-inventory/pull/387 gets merged.

**Comment by dehort** [comment]
@Glutexo Please rebase this and I'll get it merged in next.

**Comment by Glutexo** [comment]
Rebased, mergeable!

**Pull request merged**
