### PR TITLE
Allow encoded commas when querying tags

### PR DESCRIPTION
**Pull request by kruai**
# Overview

This PR is being created to address [ESSNTL-1675](https://issues.redhat.com/browse/ESSNTL-1675).
It changes the spec for Tags to be pipe-delimited instead of comma-delimited. We also have the option to make it space-delimited; it just depends on what character we don't want to allow in the tag.

We also had some tests that validated the csv-style of supplying multiple values to this query param; I've modified these to send the `tags` param multiple times, since that's the way the front-ends supply that query.

## PR Checklist

- [x] Keep PR title short, ideally under 72 characters
- [ ] Descriptive comments provided in complex code blocks
- [x] Tests: validate optimal/expected output
- [x] Tests: validate exceptions and failure scenarios
- [ ] Tests: edge cases
- [ ] Recovers or fails gracefully during potential resource outages (e.g. DB, Kafka)
- [ ] Uses [type hinting](https://docs.python.org/3/library/typing.html), if convenient
- [ ] Documentation, if this PR changes the way other services interact with host inventory
- [ ] Links to related PRs

## Secure Coding Practices Documentation Reference

You can find documentation on this checklist [here](https://github.com/RedHatInsights/secure-coding-checklist).

## Secure Coding Checklist

- [ ] Input Validation
- [ ] Output Encoding
- [ ] Authentication and Password Management
- [ ] Session Management
- [ ] Access Control
- [ ] Cryptographic Practices
- [ ] Error Handling and Logging
- [ ] Data Protection
- [ ] Communication Security
- [ ] System Configuration
- [ ] Database Security
- [ ] File Management
- [ ] Memory Management
- [ ] General Coding Practices

### CODE REVIEW

**Review by CodeHeeler — COMMENTED** [review]
Why the changes to using the helper function quote()?  Is it necessary when using f strings?

**Comment by kruai** [comment]
> Why the changes to using the helper function quote()? Is it necessary when using f strings?

`quote()` URL-encodes strings. I had to move the `quote()` call out of the test definition and into the parameterization because I changed the query syntax. For instance, one of them was querying ?tags=`a/b=c,d/e=f` (url-encoded) in the old csv format; since we're dropping that, I changed it to ?tags=`a/b=c`&tags=`d/e=f`.

Since the test was just wrapping the parameter with one `?tags={query_param}`, I had to move things around for those tests.

**Comment by kruai** [comment]
FYI, I updated the regex for the tags parameter in the spec. Now it explicitly disallows spaces in API requests

**Comment by kruai** [comment]
I have updated this so it's pipe-delimited instead of space-delimited.

**Review by FabriciaDinizRH — APPROVED** [review]
LGTM

**Comment by kruai** [comment]
We can't merge this because some tags use pipes. I'm going to close this and just open a PR to just disallow commas in tag queries.

**Pull request closed without merging**
