### PR TITLE
Add github action for checking base image.

### PR DESCRIPTION
**Pull request by thearifismail**
# Overview

This PR is being created to address [ESSNTL-3454](https://issues.redhat.com/browse/ESSNTL-3454).
The base image will be checked using a cron job. If a changed is realized, the HBI base image will be updated.

## PR Checklist
 
- [ ] Keep PR title short, ideally under 72 characters
- [ ] Descriptive comments provided in complex code blocks
- [ ] Tests: validate optimal/expected output
- [ ] Tests: validate exceptions and failure scenarios
- [ ] Tests: edge cases
- [ ] Recovers or fails gracefully during potential resource outages (e.g. DB, Kafka)
- [ ] Uses [type hinting](https://docs.python.org/3/library/typing.html), if convenient
- [ ] Documentation, if this PR changes the way other services interact with host inventory
- [ ] Links to related PRs

## Secure Coding Practices Documentation Reference

You can find documentation on this checklist [here](https://github.com/RedHatInsights/secure-coding-checklist).

## Secure Coding Checklist

- [ ] Input Validation
- [ ] Output Encoding
- [ ] Authentication and Password Management
- [ ] Session Management
- [ ] Access Control
- [ ] Cryptographic Practices
- [ ] Error Handling and Logging
- [ ] Data Protection
- [ ] Communication Security
- [ ] System Configuration
- [ ] Database Security
- [ ] File Management
- [ ] Memory Management
- [ ] General Coding Practices

### CODE REVIEW

**Review by CodeHeeler — APPROVED** [review]
Overall LGTM, but you should have someone more familiar check it out as well.  My only concern would be the email address being in a public repo if it isn't already as that may get crawled and then get spam?

**Comment by thearifismail** [comment]
> Overall LGTM, but you should have someone more familiar check it out as well. My only concern would be the email address being in a public repo if it isn't already as that may get crawled and then get spam?

Thanks @CodeHeeler for reminding me.  
@vkrizan Can you please take a look at it?  I just copied the workflow from Floorist.

**Review by vkrizan — APPROVED** [review]
For base image check this looks good.

I see that your image installs and updates packages, so I'd recommend to check package updates as well. We did that by issuing `microdnf update` and then hashing list of installed/updated packages.
Check https://github.com/RedHatInsights/eventing-integrations/pull/91/files

**Review by kruai — COMMENTED** [review]
This looks good to me, though it sounds like it would be worth implementing the suggested `microdnf update` change as well

**Comment by thearifismail** [comment]
> This looks good to me, though it sounds like it would be worth implementing the suggested `microdnf update` change as well

`microdnf` is in `ubi8/minimal`; `ubi8/python38` has `dnf`.  IMO `dnf update` should be added by a separate PR because it will be to the Dockerfile producing a specific image.

**Review by kruai — APPROVED** [review]

**Pull request merged**
