### PR TITLE
Replace empty-string host.groups values with empty arrays instead

### PR DESCRIPTION
**Pull request by kruai**
# Overview

This PR is being created to address an issue where some hosts created in the early stages of Inventory Groups have host.groups set to `""`. If a host isn't associated with a group, its default value should be `[]`.
This just creates a new alembic migration to update the existing errant data.

### CODE REVIEW

**Review by thearifismail — DISMISSED** [review]
LGTM

**Review by thearifismail — APPROVED** [review]
LGTM

**Comment by fstavela** [comment]
@kruai I'll need to adjust IQE tests for this. The DB schema tests don't expect `groups` to not be nullable.

**Pull request merged**
