### PR TITLE
Use post to query hosts

### PR DESCRIPTION
**Pull request by fijshion**
My linter cleaned up a bunch of stuff automatically. If you need me to rip those changes out to make it easier to review, let me know.

### CODE REVIEW

**Comment by Glutexo** [comment]
This looks reviewable even with the style changes, even though they are not relevant to the PR subject. The problems with those are:

* it will heavily break other pending PRs, they will have to be manually rebased
* we should agree on some style or linter+configuration before pushing any complex changes

See #189. @jhjaggars suggested using [_Black_](https://github.com/ambv/black).

**Comment by dehort** [comment]
@fijshion we've made a number of changes to the code lately.  I've merged master into the use_post_to_query_hosts branch.  Can you resolve these conflicts and remove the formatting changes?  Sorry for the trouble!  I appreciate the help.

**Comment by Glutexo** [comment]
I’ll review this after the rebase.

**Comment by dehort** [comment]
@fijshion Can you modify the queries to by default return the host data without the "facts" and "system_profile"?  Then add some flags/options to allow returning the "facts" and "system_profile"?  Let me know what you think.

**Comment by fijshion** [comment]
The rebase was really nasty so I just created a new branch. See #233. Closing this PR.

**Comment by Glutexo** [comment]
Thanks a lot! Will take a look.

**Pull request closed without merging**
