### PR TITLE
Rebuild events bugfix

### PR DESCRIPTION
**Pull request by kruai**
# Overview

This PR is being created to address [ESSNTL-1363](https://issues.redhat.com/browse/ESSNTL-1363).
Basically, reverts most of the bigger changes I made in my last bugfix (#1008), and makes a small JSON fix.

## PR Checklist

- [x] Keep PR title short, ideally under 72 characters
- [ ] Descriptive comments provided in complex code blocks
- [ ] Tests: validate optimal/expected output
- [ ] Tests: validate exceptions and failure scenarios
- [ ] Tests: edge cases
- [ ] Documentation, if this PR changes the way other services interact with host inventory
- [x] Links to related PRs

## Secure Coding Practices Documentation Reference

You can find documentation on this checklist [here](https://github.com/RedHatInsights/secure-coding-checklist).

## Secure Coding Checklist

- [ ] Input Validation
- [ ] Output Encoding
- [ ] Authentication and Password Management
- [ ] Session Management
- [ ] Access Control
- [ ] Cryptographic Practices
- [ ] Error Handling and Logging
- [ ] Data Protection
- [ ] Communication Security
- [ ] System Configuration
- [ ] Database Security
- [ ] File Management
- [ ] Memory Management
- [ ] General Coding Practices

### CODE REVIEW

**Review by thearifismail — COMMENTED** [review]
The code LGTM but the tests in the test_event_rebuilder.py failed.  Attaching the test log.  I need to run but consider it `approved` WHEN these tests pass.

**Comment by thearifismail** [comment]
[failed_tests.txt](https://github.com/RedHatInsights/insights-host-inventory/files/7268745/failed_tests.txt)

**Comment by kruai** [comment]
> The code LGTM but the tests in the test_event_rebuilder.py failed. Attaching the test log. I need to run but consider it `approved` WHEN these tests pass.

Oops, looks like I messed up my mocks. I'll fix it

**Review by ryandillinfelton — DISMISSED** [review]
LGTM

**Review by thearifismail — APPROVED** [review]
all tests passed with the latest pull

**Pull request merged**
