### PR TITLE
Disallow commas in tags query

### PR DESCRIPTION
**Pull request by kruai**
# Overview

This PR is being created to address [ESSNTL-1675](https://issues.redhat.com/browse/ESSNTL-1675).
It just updates the tags regex in the API spec to disallow commas in the tag values, since that's what we're using as a delimiter.

## PR Checklist

- [x] Keep PR title short, ideally under 72 characters
- [ ] Descriptive comments provided in complex code blocks
- [ ] Tests: validate optimal/expected output
- [ ] Tests: validate exceptions and failure scenarios
- [ ] Tests: edge cases
- [ ] Recovers or fails gracefully during potential resource outages (e.g. DB, Kafka)
- [ ] Uses [type hinting](https://docs.python.org/3/library/typing.html), if convenient
- [ ] Documentation, if this PR changes the way other services interact with host inventory
- [ ] Links to related PRs

## Secure Coding Practices Documentation Reference

You can find documentation on this checklist [here](https://github.com/RedHatInsights/secure-coding-checklist).

## Secure Coding Checklist

- [ ] Input Validation
- [ ] Output Encoding
- [ ] Authentication and Password Management
- [ ] Session Management
- [ ] Access Control
- [ ] Cryptographic Practices
- [ ] Error Handling and Logging
- [ ] Data Protection
- [ ] Communication Security
- [ ] System Configuration
- [ ] Database Security
- [ ] File Management
- [ ] Memory Management
- [ ] General Coding Practices

### CODE REVIEW

**Review by CodeHeeler — DISMISSED** [review]
LGTM, the tests failing are the ones related to the puptoo change which should go to prod Tuesday.

**Review by FabriciaDinizRH — APPROVED** [review]

**Review by thearifismail — APPROVED** [review]
LGTM

**Review by FabriciaDinizRH — APPROVED** [review]

**Review by fstavela — APPROVED** [review]
Only one test failed in the full tests run called "test_create_hosts_with_tag_containing_special_characters"
This is expected because the test tries to create hosts with different special characters and one of them is a comma, which this PR prohibits. I've already created a patch for the test, but I can merge it only after this PR is merged, otherwise, the PR checks would start failing on other PRs.

So LGTM!

**Comment by kruai** [comment]
> Only one test failed in the full tests run called "test_create_hosts_with_tag_containing_special_characters" This is expected because the test tries to create hosts with different special characters and one of them is a comma, which this PR prohibits. I've already created a patch for the test, but I can merge it only after this PR is merged, otherwise, the PR checks would start failing on other PRs.
> 
> So LGTM!

OK! I'll go ahead and merge it then.

**Pull request merged**
