### PR TITLE
fix: add yum update to fix security vulnerabilities at build

### PR DESCRIPTION
**Pull request by SteveHNH**
This is a method I use with a few of the apps in the platform to keep
the packages on our images up to date. I noticed some alerts in the quay
vulnerability channel in slack. You can also update, or remove packages
you don't use, but this is handy at keeping images updated at build.

Signed-off-by: Stephen Adams <tsadams@gmail.com>

## Overview

This PR is being created to address [this Jira](https://issues.redhat.com/browse/RHCLOUD-xxxxx).
(A description of your PR's changes goes here.)

## Secure Coding Practices Checklist GitHub Link

- https://github.com/RedHatInsights/secure-coding-checklist

## Secure Coding Checklist

- [ ] Input Validation
- [ ] Output Encoding
- [ ] Authentication and Password Management
- [ ] Session Management
- [ ] Access Control
- [ ] Cryptographic Practices
- [ ] Error Handling and Logging
- [ ] Data Protection
- [ ] Communication Security
- [ ] System Configuration
- [ ] Database Security
- [ ] File Management
- [ ] Memory Management
- [ ] General Coding Practices

### CODE REVIEW

**Comment by kruai** [comment]
I had convinced myself that this wouldn't work for us, but I don't see why it wouldn't! Let's give it a shot :)

**Review by kruai — APPROVED** [review]

**Comment by kruai** [comment]
@SteveHNH Actually, I realized that the dockerfile is only used for our dev environments. Our project uses s2i via buildfactory, so this actually won't work for us :(

**Comment by kruai** [comment]
@tahmidefaz @ryandillinfelton @thearifismail lmk if you disagree with the above ^
Otherwise, I'll close this one

**Review by thearifismail — APPROVED** [review]
LGTM

**Pull request closed without merging**
