### PR TITLE
Migrate to Deployments

### PR DESCRIPTION
**Pull request by psav**
Migration from pods to deployments in Clowder

### CODE REVIEW

**Review by kruai — APPROVED** [review]
I can't find any issues with this! LGTM

**Comment by gmcculloug** [comment]
@thearifismail Please review

**Review by thearifismail — COMMENTED** [review]
LGTM.  A minor question though.  Should the name be `host-inventory` for clarity and avoid confusion because of `topological-inventory`?
```yaml
- name: APP_NAME
  value: inventory
```

**Comment by thearifismail** [comment]
@kylape your thoughts about https://github.com/RedHatInsights/insights-host-inventory/pull/770#pullrequestreview-554829038

**Comment by kylape** [comment]
The APP_NAME env var is not used by Clowder.  Is it used by your app code?

**Comment by thearifismail** [comment]
Must be because it is defined the same way in saas-template.

**Review by thearifismail — APPROVED** [review]

**Comment by BlakeHolifield** [comment]
This can be closed. It was brought in as a part of #792

**Pull request closed without merging**
