### PR TITLE
Remove display_name workaround

### PR DESCRIPTION
**Pull request by kruai**
## Overview

This PR is being created to address [RHCLOUD-13330](https://issues.redhat.com/browse/RHCLOUD-13330).
This removes the workarounds we implemented for `display_name`, due to the various restrictions that ended up being required. [RHCLOUD-5954](https://issues.redhat.com/browse/RHCLOUD-5954) added the first workaround because Yupana kept overwriting the `display_name` field. Later, we completed [RHCLOUD-13105](https://issues.redhat.com/browse/RHCLOUD-13105), which allowed some reporters to set the field if they didn't have an Insights ID. We eventually decided that this logic should not be owned by HBI, and that the offending reporter (Yupana) should just stop constantly overwriting that field.

The Yupana team has already merged [their PR](https://github.com/quipucords/yupana/pull/346), which strips `display_name` from the payloads they send to us. 

## PR Checklist

- [x] Keep PR title short, ideally under 72 characters
- [ ] Descriptive comments provided in complex code blocks
- [ ] Tests: validate optimal/expected output
- [ ] Tests: validate exceptions and failure scenarios
- [ ] Tests: edge cases
- [ ] Documentation, if this PR changes the way other services interact with host inventory
- [x] Links to related PRs

## Secure Coding Practices Checklist GitHub Link

- https://github.com/RedHatInsights/secure-coding-checklist

## Secure Coding Checklist

- [ ] Input Validation
- [ ] Output Encoding
- [ ] Authentication and Password Management
- [ ] Session Management
- [ ] Access Control
- [ ] Cryptographic Practices
- [ ] Error Handling and Logging
- [ ] Data Protection
- [ ] Communication Security
- [ ] System Configuration
- [ ] Database Security
- [ ] File Management
- [ ] Memory Management
- [x] General Coding Practices

### CODE REVIEW

**Review by thearifismail — APPROVED** [review]
LGTM

**Comment by tahmidefaz** [comment]
@kruai The changes looks good. I had a question: This used to also restrict `rhsm-conduit` from updating the `display_name`, were there any talks regarding this with the `rhsm-conduit` team?

**Comment by kruai** [comment]
> @kruai The changes looks good. I had a question: This used to also restrict `rhsm-conduit` from updating the `display_name`, were there any talks regarding this with the `rhsm-conduit` team?

Yes, although the discussions in question were what prompted [RHCLOUD-13105](https://issues.redhat.com/browse/RHCLOUD-13105). It seems [RHCLOUD-5954](https://issues.redhat.com/browse/RHCLOUD-5954) was opened and merged (maybe too hastily) in order to stop Yupana from constantly overwriting other reporters' updates to `display_name`. The reason we added the `or "insights_id" not in self.canonical_facts` part of the conditional was a safety measure, just to make sure that puptoo's hosts' display_name didn't get overwritten. I don't see the display_name overwrite issue becoming a problem again now that Yupana has stopped trying to update it.

**Review by tahmidefaz — APPROVED** [review]
Sounds good! Thanks! :+1:

**Pull request merged**
