### PR TITLE
Add Marshmallow validation for sap_sids

### PR DESCRIPTION
**Pull request by CodeHeeler**

### CODE REVIEW

**Comment by CodeHeeler** [comment]
@jharting @Glutexo any guess on what's going on with the pr-head and pre-commit failures?  It appears to be unrelated to my work and I'm not sure how to get this moving forward.  Thanks!

**Comment by jharting** [comment]
@CodeHeeler do you have [pre-commit hooks](https://github.com/RedHatInsights/insights-host-inventory#contributing) enabled?

**Comment by CodeHeeler** [comment]
> @CodeHeeler do you have [pre-commit hooks](https://github.com/RedHatInsights/insights-host-inventory#contributing) enabled?

Ah!  I have never used these before, but I'd wondered why you didn't have travis checking for black and flake8 like we do on our Drift repos.  It all makes sense now, thank you.

**Comment by CodeHeeler** [comment]
@jharting Still the same two are failing, pr-head and pre-commit.  Any other ideas?

**Comment by beav** [comment]
@CodeHeeler the error was buried in `pipeline.log`. It failed its `black` check. This patch fixes it:

```diff
diff --git a/app/models.py b/app/models.py
index 0b8a5ee..770d4d0 100644
--- a/app/models.py
+++ b/app/models.py
@@ -309,7 +309,7 @@ class SystemProfileSchema(Schema):
     installed_services = fields.List(fields.Str(validate=validate.Length(max=512)))
     enabled_services = fields.List(fields.Str(validate=validate.Length(max=512)))
     sap_system = fields.Bool()
-    sap_sids = fields.List(fields.Str(validate=[validate.Length(max=3), validate.Regexp(regex=r'^[A-Z][A-Z0-9]{2}$')]))
+    sap_sids = fields.List(fields.Str(validate=[validate.Length(max=3), validate.Regexp(regex=r"^[A-Z][A-Z0-9]{2}$")]))
```

**Comment by tahmidefaz** [comment]
I think if you run `make style` and push up the changes, it'll take care of it :slightly_smiling_face:

**Review by ryandillinfelton — APPROVED** [review]
Looks good, and works as expected in my testing :+1:

**Comment by Glutexo** [comment]
🤦🏻‍♂️ https://github.com/RedHatInsights/insights-host-inventory/commit/25c640f1de141fc48717726d81e9cd5dd0361054 reverted the _sap_sids_ validation rule from the System Profile.

**Review by Glutexo — COMMENTED** [review]
This is the first field with a more complex validation rule. We don’t have tests for that yet, but we will (see #715), then all of these should have tests.

**Pull request merged**
