### PR TITLE
Add sap_local_instances fact

### PR DESCRIPTION
**Pull request by CodeHeeler**

### CODE REVIEW

**Comment by Glutexo** [comment]
Waiting for https://github.com/RedHatInsights/inventory-schemas/pull/3.

**Comment by gmcculloug** [comment]
@Glutexo Can this move forward now that RedHatInsights/inventory-schemas#3 is merged?

cc @tahmidefaz

**Comment by CodeHeeler** [comment]
It's my understanding that this was opened before we understood that what we meant was sap_sids which was handled in https://github.com/RedHatInsights/insights-host-inventory/pull/709

The next sap related facts we will be adding are: sap_instance_number, sap_system_number and sap_version_info

I have not investigated those yet as first we are finishing tuned_profile and then addressing two SELinux facts.

I am closing this PR and new appropriate ones will be opened soon instead. Looping in @beav for reference.

**Comment by Glutexo** [comment]
So _sap_sids_ is the correct field name for what in this PR is called _sap_local_instances_? If so, then 👍🏻 for closing this.

**Comment by CodeHeeler** [comment]
Yes, this was opened first as a first attempt and we later learned we were incorrect and meant sap_sids. as the array.

**Pull request closed without merging**
