### PR TITLE
ci(ESSNTL-4712): Add dependabot.yml workflow

### PR DESCRIPTION
**Pull request by strider**
# Overview

This PR is being created to address [ESSNTL-4712](https://issues.redhat.com/browse/ESSNTL-4712).
This patch enables Dependabot in insights-host-inventory to automatically updates the packages we use.

## PR Checklist

- [ ] Keep PR title short, ideally under 72 characters
- [ ] Descriptive comments provided in complex code blocks
- [ ] Tests: validate optimal/expected output
- [ ] Tests: validate exceptions and failure scenarios
- [ ] Tests: edge cases
- [ ] Recovers or fails gracefully during potential resource outages (e.g. DB, Kafka)
- [ ] Uses [type hinting](https://docs.python.org/3/library/typing.html), if convenient
- [ ] Documentation, if this PR changes the way other services interact with host inventory
- [ ] Links to related PRs

## Secure Coding Practices Documentation Reference

You can find documentation on this checklist [here](https://github.com/RedHatInsights/secure-coding-checklist).

## Secure Coding Checklist

- [ ] Input Validation
- [ ] Output Encoding
- [ ] Authentication and Password Management
- [ ] Session Management
- [ ] Access Control
- [ ] Cryptographic Practices
- [ ] Error Handling and Logging
- [ ] Data Protection
- [ ] Communication Security
- [ ] System Configuration
- [ ] Database Security
- [ ] File Management
- [ ] Memory Management
- [ ] General Coding Practices

### CODE REVIEW

**Review by CodeHeeler — APPROVED** [review]
LGTM, dependabot is very helpful.

**Comment by kruai** [comment]
Bit confused - don't we already have dependabot? It's opened a few PRs, at least (like [PR 1250](https://github.com/RedHatInsights/insights-host-inventory/pull/1250)).

**Comment by strider** [comment]
> Bit confused - don't we already have dependabot? It's opened a few PRs, at least (like [PR 1250](https://github.com/RedHatInsights/insights-host-inventory/pull/1250)).

Yes, didn't mention this PR enable Dependabot Version Update(s). What we already have is Dependabot Alerts and Dependabot Security Update(s) to fix those alerts.

**Comment by kruai** [comment]
> > Bit confused - don't we already have dependabot? It's opened a few PRs, at least (like [PR 1250](https://github.com/RedHatInsights/insights-host-inventory/pull/1250)).
> 
> Yes, didn't mention this PR enables Dependabot Version Update(s). What we already have is Dependabot Alerts and Dependabot Security Update(s) to fix those alerts.

Ah, thank you for the clarification.

**Pull request merged**
