### PR TITLE
RHCLOUD-23862 use ubi8-minimal image for building host-inventory images

### PR DESCRIPTION
**Pull request by thearifismail**
# Overview

This PR is being created to address [RHCLOUD-23862](https://issues.redhat.com/browse/RHCLOUD-23862).
The JIRA card provides the reason as to why ubi8-minimal image is being used. Let's see how this image respond when deployed into minikube and OpenShift.

## PR Checklist

- [ ] Keep PR title short, ideally under 72 characters
- [ ] Descriptive comments provided in complex code blocks
- [ ] Tests: validate optimal/expected output
- [ ] Tests: validate exceptions and failure scenarios
- [ ] Tests: edge cases
- [ ] Recovers or fails gracefully during potential resource outages (e.g. DB, Kafka)
- [ ] Uses [type hinting](https://docs.python.org/3/library/typing.html), if convenient
- [ ] Documentation, if this PR changes the way other services interact with host inventory
- [ ] Links to related PRs

## Secure Coding Practices Documentation Reference

You can find documentation on this checklist [here](https://github.com/RedHatInsights/secure-coding-checklist).

## Secure Coding Checklist

- [ ] Input Validation
- [ ] Output Encoding
- [ ] Authentication and Password Management
- [ ] Session Management
- [ ] Access Control
- [ ] Cryptographic Practices
- [ ] Error Handling and Logging
- [ ] Data Protection
- [ ] Communication Security
- [ ] System Configuration
- [ ] Database Security
- [ ] File Management
- [ ] Memory Management
- [ ] General Coding Practices

### CODE REVIEW

**Review by jpramos123 — COMMENTED** [review]
Dockerfile looks good to me.

As @CodeHeeler suggested, maybe we can use ubi9 image!

Also, please rebase your fork and push the code again!

Thanks

**Comment by thearifismail** [comment]
@jpramos123 `ubi9` is too new to feel comfortable with it.  Furthermorethe pipeline failure has been caused by `clowder/rbac` which is beyond host-inventory.  Let me rebase and see if the pipeline succeed.

**Review by CodeHeeler — APPROVED** [review]
We can revisit the ubi9 conversation later, but this looks good for now.  Tests are now passing as well. Thanks!

**Review by jpramos123 — APPROVED** [review]
LGTM!

All tests are passing!

Thanks

**Comment by strider** [comment]
@thearifismail, It would be great to update the `dev.dockerfile` as well? Wouldn't it? As you are on this.

**Review by kruai — APPROVED** [review]
Should be good! I wanna make sure the "all tests" PR passes for this one though

**Pull request merged**
