### PR TITLE
Enable gunicorn to support multiple workers using MultiprocessPrometh…

### PR DESCRIPTION
**Pull request by thearifismail**
…eusMetrics

# Overview

This PR is being created to address [ESSNTL-2927](https://issues.redhat.com/browse/ESSNTL-2927) and [ESSNTL-2950](https://issues.redhat.com/browse/ESSNTL-2950)
This PR implements the use of MultiprocessPrometheusMetrics to deal with the "address already in use" error. Now multiple workers are run without complaining about "address already in use"

It also updates prometheus-client and prometheus-flask-exporter to the latest versions available.

## PR Checklist

- [ ] Keep PR title short, ideally under 72 characters
- [ ] Descriptive comments provided in complex code blocks
- [ ] Tests: validate optimal/expected output
- [ ] Tests: validate exceptions and failure scenarios
- [ ] Tests: edge cases
- [ ] Recovers or fails gracefully during potential resource outages (e.g. DB, Kafka)
- [ ] Uses [type hinting](https://docs.python.org/3/library/typing.html), if convenient
- [ ] Documentation, if this PR changes the way other services interact with host inventory
- [ ] Links to related PRs

## Secure Coding Practices Documentation Reference

You can find documentation on this checklist [here](https://github.com/RedHatInsights/secure-coding-checklist).

## Secure Coding Checklist

- [ ] Input Validation
- [ ] Output Encoding
- [ ] Authentication and Password Management
- [ ] Session Management
- [ ] Access Control
- [ ] Cryptographic Practices
- [ ] Error Handling and Logging
- [ ] Data Protection
- [ ] Communication Security
- [ ] System Configuration
- [ ] Database Security
- [ ] File Management
- [ ] Memory Management
- [ ] General Coding Practices

### CODE REVIEW

**Comment by InsightsDroid** [comment]
Test results are available in Ibutsu:
https://url.corp.redhat.com/ibutsu-runs-2e334ce4-a792-427d-8280-569db0a80a83

**Comment by fstavela** [comment]
I don't see any errors about "address already in use" anymore, but this PR introduces the service restarts bug again, which could cause problems for other services as it did last time. Here is the log from ephemeral env:
```
[2022-06-27 06:58:49 +0000] [1] [INFO] Starting gunicorn 19.9.0
[2022-06-27 06:58:49 +0000] [1] [INFO] Listening at: http://0.0.0.0:8000 (1)
[2022-06-27 06:58:49 +0000] [1] [INFO] Using worker: threads
/usr/lib64/python3.8/os.py:1023: RuntimeWarning: line buffering (buffering=1) isn't supported in binary mode, the default buffer size will be used
return io.open(fd, *args, **kwargs)
[2022-06-27 06:58:49 +0000] [8] [INFO] Booting worker with pid: 8
[2022-06-27 06:58:49 +0000] [9] [INFO] Booting worker with pid: 9
[2022-06-27 06:58:49 +0000] [10] [INFO] Booting worker with pid: 10
[2022-06-27 06:58:49 +0000] [11] [INFO] Booting worker with pid: 11
Unable to configure watchtower logging. Please verify watchtower logging configuration!
[2022-06-27 06:58:58,153] [9] [139992742265088] [inventory.app.config] [INFO] Insights Host Inventory Configuration:
[2022-06-27 06:58:58,153] [9] [139992742265088] [inventory.app.config] [INFO] Build Version: Unknown
[2022-06-27 06:58:58,153] [9] [139992742265088] [inventory.app.config] [INFO] DB Host: host-inventory-db.ephemeral-oofjho.svc
[2022-06-27 06:58:58,153] [9] [139992742265088] [inventory.app.config] [INFO] DB Name: host-inventory
[2022-06-27 06:58:58,153] [9] [139992742265088] [inventory.app.config] [INFO] DB Connection URI: postgresql://xxxx:XXXX@host-inventory-db.ephemeral-oofjho.svc:5432/host-inventory
[2022-06-27 06:58:58,153] [9] [139992742265088] [inventory.app.config] [INFO] API URL Path: /api/inventory/v1
[2022-06-27 06:58:58,153] [9] [139992742265088] [inventory.app.config] [INFO] Management URL Path Prefix: /
[2022-06-27 06:58:58,153] [9] [139992742265088] [inventory.app.config] [INFO] RBAC Bypassed: True
[2022-06-27 06:58:58,153] [9] [139992742265088] [inventory.app.config] [INFO] RBAC Endpoint: http://rbac-service.ephemeral-oofjho.svc:8000
[2022-06-27 06:58:58,153] [9] [139992742265088] [inventory.app.config] [INFO] RBAC Retry Times: 2
[2022-06-27 06:58:58,153] [9] [139992742265088] [inventory.app.config] [INFO] RBAC Timeout Seconds: 10
[2022-06-27 06:58:58,153] [9] [139992742265088] [inventory.app.config] [INFO] Bypassing tenant translation for hosts missing org_id: False
[2022-06-27 06:58:58,153] [9] [139992742265088] [inventory.app.config] [INFO] Kafka Bootstrap Servers: env-ephemeral-oofjho-f43d6ef2-kafka-bootstrap.ephemeral-oofjho.svc:9092
[2022-06-27 06:58:58,153] [9] [139992742265088] [inventory.app.config] [INFO] Kafka Event Topic: platform.inventory.events
[2022-06-27 06:58:58,154] [9] [139992742265088] [inventory.app.config] [INFO] Payload Tracker Kafka Topic: platform.payload-status
[2022-06-27 06:58:58,154] [9] [139992742265088] [inventory.app.config] [INFO] Payload Tracker Service Name: inventory
[2022-06-27 06:58:58,154] [9] [139992742265088] [inventory.app.config] [INFO] Payload Tracker Enabled: True

Unable to configure watchtower logging. Please verify watchtower logging configuration!
[2022-06-27 06:58:58,350] [11] [139992742265088] [inventory.app.config] [INFO] Insights Host Inventory Configuration:
[2022-06-27 06:58:58,351] [11] [139992742265088] [inventory.app.config] [INFO] Build Version: Unknown
[2022-06-27 06:58:58,351] [11] [139992742265088] [inventory.app.config] [INFO] DB Host: host-inventory-db.ephemeral-oofjho.svc
[2022-06-27 06:58:58,351] [11] [139992742265088] [inventory.app.config] [INFO] DB Name: host-inventory
[2022-06-27 06:58:58,351] [11] [139992742265088] [inventory.app.config] [INFO] DB Connection URI: postgresql://xxxx:XXXX@host-inventory-db.ephemeral-oofjho.svc:5432/host-inventory
[2022-06-27 06:58:58,351] [11] [139992742265088] [inventory.app.config] [INFO] API URL Path: /api/inventory/v1
[2022-06-27 06:58:58,351] [11] [139992742265088] [inventory.app.config] [INFO] Management URL Path Prefix: /
[2022-06-27 06:58:58,351] [11] [139992742265088] [inventory.app.config] [INFO] RBAC Bypassed: True
[2022-06-27 06:58:58,351] [11] [139992742265088] [inventory.app.config] [INFO] RBAC Endpoint: http://rbac-service.ephemeral-oofjho.svc:8000
[2022-06-27 06:58:58,351] [11] [139992742265088] [inventory.app.config] [INFO] RBAC Retry Times: 2
[2022-06-27 06:58:58,351] [11] [139992742265088] [inventory.app.config] [INFO] RBAC Timeout Seconds: 10
[2022-06-27 06:58:58,351] [11] [139992742265088] [inventory.app.config] [INFO] Bypassing tenant translation for hosts missing org_id: False
[2022-06-27 06:58:58,351] [11] [139992742265088] [inventory.app.config] [INFO] Kafka Bootstrap Servers: env-ephemeral-oofjho-f43d6ef2-kafka-bootstrap.ephemeral-oofjho.svc:9092
[2022-06-27 06:58:58,351] [11] [139992742265088] [inventory.app.config] [INFO] Kafka Event Topic: platform.inventory.events
[2022-06-27 06:58:58,351] [11] [139992742265088] [inventory.app.config] [INFO] Payload Tracker Kafka Topic: platform.payload-status
[2022-06-27 06:58:58,351] [11] [139992742265088] [inventory.app.config] [INFO] Payload Tracker Service Name: inventory
[2022-06-27 06:58:58,351] [11] [139992742265088] [inventory.app.config] [INFO] Payload Tracker Enabled: True
```
Notice the error
```
/usr/lib64/python3.8/os.py:1023: RuntimeWarning: line buffering (buffering=1) isn't supported in binary mode, the default buffer size will be used
return io.open(fd, *args, **kwargs)
```
at the beginning, maybe it is related.

**Comment by thearifismail** [comment]
Closing this PR as not fix is needed because the problem occurs in ephemeral cluster and NOT In STAGE or PROD.  Furthermore, flask and multiprocess prometheus handling is implemented as directed and documented.

**Pull request closed without merging**
