### PR TITLE
Add model name as cpu_model to system profile

### PR DESCRIPTION
**Pull request by CodeHeeler**
Add cpu model name as cpu_model to system profile as requested:
https://issues.redhat.com/browse/HBISPSC-39

Related PRs:
https://github.com/RedHatInsights/inventory-schemas/pull/44
https://github.com/RedHatInsights/insights-puptoo/pull/117

### CODE REVIEW

**Comment by kruai** [comment]
@CodeHeeler I think I found what's missing here! The new field wasn't added to the unit test payloads and whatnot. I'm looking at this PR, for reference: https://github.com/RedHatInsights/insights-host-inventory/pull/775

**Comment by CodeHeeler** [comment]
@kruai Added.  Let's see if that's all of it to fix Travis.

**Review by ryandillinfelton — APPROVED** [review]
Looks good and all of the tests pass now :+1:

**Review by kruai — APPROVED** [review]

**Review by tahmidefaz — APPROVED** [review]
lgtm :+1:

**Pull request merged**
