### PR TITLE
Modify format of posted comments

### PR DESCRIPTION
**Pull request by kruai**
## Overview

This tiny PR just modifies the format of the comments that get posted by the SP validator.
I made this change after looking at [this dippy-bot comment](https://github.com/RedHatInsights/inventory-schemas/pull/54#issuecomment-800771714).

I have removed the checklist for this PR because this is a one-character change to a text field.

### CODE REVIEW

**Review by tahmidefaz — APPROVED** [review]
LGTM! In the future, I think it'd be cool to have the comment in the following format:

| Reporter  | Master Fail | PR Fail | Master Pass | PR Pass |
| ------------- | ------------- | ------------- | ------------- | ------------- |
| Puptoo  | 100 | 700 | 300000  | 200400  |
| Yupana  | 100 | 700 | 300000  | 200400  |

**Comment by kruai** [comment]
> LGTM! In the future, I think it'd be cool to have the comment in the following format:
> 
> Reporter	Master Fail	PR Fail	Master Pass	PR Pass
> Puptoo	100	700	300000	200400
> Yupana	100	700	300000	200400

Good call. Made a Jira to track it! https://issues.redhat.com/browse/RHCLOUD-12997

**Review by tahmidefaz — APPROVED** [review]
Still good! :+1:

**Review by ryandillinfelton — APPROVED** [review]
:+1:

**Pull request merged**
