### PR TITLE
Add pr_check script required by app-interface for build verification

### PR DESCRIPTION
**Pull request by thearifismail**
This `pr_check.sh`is a place-filler and will not be needed when [Clowder PR](https://github.com/RedHatInsights/insights-host-inventory/pull/737) is merged.  

Though `host-inventory` code can get merged without this `pr_check` script, seeing this build_check failure with every PR is  disconcerting.  
build_check_error

### CODE REVIEW

**Review by kruai — COMMENTED** [review]
It looks like this is just adding an echo statement. What's the hack part?

**Review by thearifismail — COMMENTED** [review]
Deleted the word hack.  Providing a message to communicate the essence of why this file, `pr_check.sh` is being added.

**Comment by kruai** [comment]
> Deleted the word hack. Providing a message to communicate the essence of why this file, `pr_check.sh` is being added.

OK. Let's chat about this tomorrow morning - I'm not clear on the implications of this change, and it sounds kind of ominous, so I'd like the team to weigh in.

**Review by kruai — APPROVED** [review]
After our discussion in the Inventory Chit-Chat meeting, I'm fine with this PR!

**Comment by thearifismail** [comment]
@asa @ryandillinfelton @tahmidefaz, I see the `Squash and merge` button enabled but my understanding is that we need at least two approvals, right?

**Review by tahmidefaz — APPROVED** [review]
Approving it, but we should look out for the actual fix. :slightly_smiling_face:

**Comment by thearifismail** [comment]
Once clowder config https://github.com/RedHatInsights/insights-host-inventory/pull/737 from @klape is in this pr_check file will not be needed.

**Pull request merged**
