### PR TITLE
Fix PEP 8 errors

### PR DESCRIPTION
**Pull request by Glutexo**
Fixed all PEP 8 errors that Flake8 found. Sorry for such an invasive change, @dehort. I was a bit afraid that if we won’t enforce the style now, we’d never get rid of the mess.

### CODE REVIEW

**Comment by jhjaggars** [comment]
How about using https://github.com/ambv/black to enforce style and formatting?

**Comment by Glutexo** [comment]
@jhjaggars I‘d go for it. Or at least for a flake8 PR linting. I just wanted submit a first cleanup to begin with.

**Comment by Glutexo** [comment]
This won’t be necessary if #22 gets merged. There are still some unanswered concerns. Once that is settled, let’s close this.

**Comment by Glutexo** [comment]
#22 is merged. Closing.

**Pull request closed without merging**
