### PR TITLE
chore(RHINENG-5842): Remove Edge-Parity RBAC bypass

### PR DESCRIPTION
**Pull request by kruai**
# Overview

This PR is being created to address [RHINENG-5842](https://issues.redhat.com/browse/RHINENG-5842).
Removes the RBAC bypass that was introduced in #1580, along with the feature flag it was using. It was originally introduced to facilitate the migration to Inventory Groups for the Edge Parity project. 

## PR Checklist

- [x] Keep PR title short, ideally under 72 characters
- [ ] Descriptive comments provided in complex code blocks
- [ ] Tests: validate optimal/expected output
- [ ] Tests: validate exceptions and failure scenarios
- [ ] Tests: edge cases
- [ ] Recovers or fails gracefully during potential resource outages (e.g. DB, Kafka)
- [ ] Uses [type hinting](https://docs.python.org/3/library/typing.html), if convenient
- [ ] Documentation, if this PR changes the way other services interact with host inventory
- [x] Links to related PRs

## Secure Coding Practices Documentation Reference

You can find documentation on this checklist [here](https://github.com/RedHatInsights/secure-coding-checklist).

## Secure Coding Checklist

- [ ] Input Validation
- [ ] Output Encoding
- [ ] Authentication and Password Management
- [ ] Session Management
- [ ] Access Control
- [ ] Cryptographic Practices
- [ ] Error Handling and Logging
- [ ] Data Protection
- [ ] Communication Security
- [ ] System Configuration
- [ ] Database Security
- [ ] File Management
- [ ] Memory Management
- [ ] General Coding Practices

### CODE REVIEW

**Review by thearifismail — COMMENTED** [review]
the code LGTM but the build has to successfully complete first for approval

**Comment by kruai** [comment]
> the code LGTM but the build has to successfully complete first for approval

Got it - I'll treat that as an approval and merge when the build passes

**Comment by kruai** [comment]
Not sure why the pip install is failing for this PR - there isn't even a pip change :thinking:

**Comment by thearifismail** [comment]
> Not sure why the pip install is failing for this PR - there isn't even a pip change 🤔

Yesterday I encountered the same problem but another attempt to build was successful

**Pull request merged**
