### PR TITLE
Add field to identify edge hosts

### PR DESCRIPTION
**Pull request by tahmidefaz**
## Overview

Corresponding `inventory_schemas` PR: https://github.com/RedHatInsights/inventory-schemas/pull/61

## PR Checklist

- [x] Keep PR title short, ideally under 72 characters
- [x] Links to related PRs

## Secure Coding Practices Checklist GitHub Link

- https://github.com/RedHatInsights/secure-coding-checklist

## Secure Coding Checklist

- [x] Input Validation
- [ ] Output Encoding
- [ ] Authentication and Password Management
- [ ] Session Management
- [ ] Access Control
- [ ] Cryptographic Practices
- [ ] Error Handling and Logging
- [ ] Data Protection
- [ ] Communication Security
- [ ] System Configuration
- [ ] Database Security
- [ ] File Management
- [ ] Memory Management
- [x] General Coding Practices

### CODE REVIEW

**Comment by lphiri** [comment]
@tahmidefaz  "is_edge" seems too specific as primary field.  Should we make this into more an enum of types (perhaps "host_type")? that would be me extensible i think.

**Comment by tahmidefaz** [comment]
> @tahmidefaz "is_edge" seems too specific as primary field. Should we make this into more an enum of types (perhaps "host_type")? that would be me extensible i think.

@lphiri moved this coversation over to https://github.com/RedHatInsights/inventory-schemas/pull/61

**Review by kruai — APPROVED** [review]
LGTM

**Review by ryandillinfelton — APPROVED** [review]

**Comment by kruai** [comment]
Merged this one, since the inventory-schemas PR was already merged and we need to keep them in sync

**Pull request merged**
