### PR TITLE
Port docs from central repository

### PR DESCRIPTION
**Pull request by j00bar**
Porting the docs from the platform-docs repo into the code, so that the docs can evolve with code and be synthesized with the next-gen doc system.

### CODE REVIEW

**Comment by Glutexo** [comment]
@j00bar Any reference on how the documentation is going to be grabbed and published from there?

**Comment by j00bar** [comment]
Sure!

The core-platform-docs repo has a YAML file to describe the transformation pipeline: https://github.com/RedHatInsights/core-platform-docs/blob/master/content/services/inventory/aletheia.yml - in your case, I've converted the doc to Hugo-compatible markdown already, so the pipeline is straightforward. The build uses [this utility](https://github.com/RedHatInsights/aletheia) which is containerized and run as a CronJob daily from our cluster, exporting the assembled/normalized docs into https://github.com/RedHatInsights/platform-docs. Our friends in AppSRE then build a new image for it, which gets run on our cluster.

**Comment by Glutexo** [comment]
Awesome, thank you! 🙇🏻‍♂️

**Comment by jharting** [comment]
@j00bar do the docs need to be converted to html + markdown? I though one of the selling points of Hugo was that it supports various formats and therefore we can stick with .rst if we wanted to :confused:

**Comment by j00bar** [comment]
@jharting They do not need to be in Markdown, no. However, the .rst that Sphinx consumes has a number of extensions that are not in the vanilla Restructured Text, so you would either need to remove the non-Sphinx rst bits from your content or to have a Sphinx installation here, which is totally fine (RBAC does that, for example). I'm happy to be of assistance in helping set that up if that's how you'd prefer to go.

**Comment by gmcculloug** [comment]
> you would either need to remove the non-Sphinx rst bits from your content or to have a Sphinx installation here

@jharting Did you have any preference on which option to pursue here?

**Comment by jharting** [comment]
> > you would either need to remove the non-Sphinx rst bits from your content or to have a Sphinx installation here
> 
> @jharting Did you have any preference on which option to pursue here?

I think I prefer keeping Sphinx bits especially if there is already a precedent for doing so. Not a strong preference, though.

**Comment by Glutexo** [comment]
Can some of the new code owners take a look and review? @tahmidefaz @kruai @ryandillinfelton

**Comment by kruai** [comment]
This is a lot to go through, but I think this looks fine. If we want to fix / update anything, we'll be able to make those changes once the docs actually exist in our repo  :+1:

**Review by kruai — APPROVED** [review]

**Comment by kruai** [comment]
@thearifismail @ryandillinfelton @tahmidefaz Please review this if you get the time! Otherwise I'm going to merge by EOD.

**Comment by ryandillinfelton** [comment]
> @thearifismail @ryandillinfelton @tahmidefaz Please review this if you get the time! Otherwise I'm going to merge by EOD.

I think we'll have to resolve whatever is causing the tests to fail first. But I don't have any objection to merging it one that's figured out.

**Comment by kruai** [comment]
> > @thearifismail @ryandillinfelton @tahmidefaz Please review this if you get the time! Otherwise I'm going to merge by EOD.
> 
> I think we'll have to resolve whatever is causing the tests to fail first. But I don't have any objection to merging it one that's figured out.

I'm not actually sure why the checks are failing... when I go to the Jenkins job, it shows everything as passing :thinking:

**Comment by kruai** [comment]
Oh, I see now. I had to drill into once of the green checkboxes to see the pre-commit failure... not intuitive at all lol. Looks like there's trailing whitespace, and the end-of-file-fixer picked up something, both on docs/_index.md (FYI @j00bar)

**Comment by ryandillinfelton** [comment]
> Oh, I see now. I had to drill into once of the green checkboxes to see the pre-commit failure... not intuitive at all lol. Looks like there's trailing whitespace, and the end-of-file-fixer picked up something, both on docs/_index.md (FYI @j00bar)

Ahh, thanks for figuring that out, I was also perplexed. @j00bar you can run our pre-commit check with `make style`. Usually it will fix whatever is wrong automatically.

**Comment by kruai** [comment]
Jag no longer works here, so I've picked up the mantle, so to speak. I've opened PR #828 to replace this one.

**Pull request closed without merging**
