### PR TITLE
fix(RHINENG-7754, RHINENG-2631): Fix not-yupana reporter filter

### PR DESCRIPTION
**Pull request by kruai**
# Overview

This PR is being created to address [RHINENG-7754](https://issues.redhat.com/browse/RHINENG-7754) and [RHINENG-2631](https://issues.redhat.com/browse/RHINENG-2631).
It fixes the logic used when filtering on `registered_with=yupana` and `registered_with=!yupana`. When filtering on `!yupana`, it no longer returns hosts reported via discovery or satellite. I've addressed both the xjoin and postgres implementations here, along with the unit tests for each. Follows up on #1557.

## PR Checklist

- [x] Keep PR title short, ideally under 72 characters
- [ ] Descriptive comments provided in complex code blocks
- [x] Tests: validate optimal/expected output
- [ ] Tests: validate exceptions and failure scenarios
- [x] Tests: edge cases
- [ ] Recovers or fails gracefully during potential resource outages (e.g. DB, Kafka)
- [ ] Uses [type hinting](https://docs.python.org/3/library/typing.html), if convenient
- [ ] Documentation, if this PR changes the way other services interact with host inventory
- [x] Links to related PRs

## Secure Coding Practices Documentation Reference

You can find documentation on this checklist [here](https://github.com/RedHatInsights/secure-coding-checklist).

## Secure Coding Checklist

- [ ] Input Validation
- [ ] Output Encoding
- [ ] Authentication and Password Management
- [ ] Session Management
- [ ] Access Control
- [ ] Cryptographic Practices
- [ ] Error Handling and Logging
- [ ] Data Protection
- [ ] Communication Security
- [ ] System Configuration
- [ ] Database Security
- [ ] File Management
- [ ] Memory Management
- [ ] General Coding Practices

### CODE REVIEW

**Review by FabriciaDinizRH — APPROVED** [review]
LGTM!

**Review by chambridge — APPROVED** [review]
LGTM

**Review by thearifismail — APPROVED** [review]
LGTM

**Review by fstavela — APPROVED** [review]
The registered_with filter works as expected now!

**Pull request merged**
