### PR TITLE
Fixed typo in error message in add_host_list_to_group().

### PR DESCRIPTION
**Pull request by roliveri**
# Overview

This PR is being created to address [RHINENG-8436](https://issues.redhat.com/browse/RHINENG-8436).

When getting a 400 error message on /groups/{group_id}/hosts, the text mentions 'Body content must be an array with **groups** UUIDs' when the expected list should be the an array with **system** UUIDs'.

## PR Checklist

- [ ] Keep PR title short, ideally under 72 characters
- [ ] Descriptive comments provided in complex code blocks
- [ ] Tests: validate optimal/expected output
- [ ] Tests: validate exceptions and failure scenarios
- [ ] Tests: edge cases
- [ ] Recovers or fails gracefully during potential resource outages (e.g. DB, Kafka)
- [ ] Uses [type hinting](https://docs.python.org/3/library/typing.html), if convenient
- [ ] Documentation, if this PR changes the way other services interact with host inventory
- [ ] Links to related PRs

## Secure Coding Practices Documentation Reference

You can find documentation on this checklist [here](https://github.com/RedHatInsights/secure-coding-checklist).

## Secure Coding Checklist

- [ ] Input Validation
- [ ] Output Encoding
- [ ] Authentication and Password Management
- [ ] Session Management
- [ ] Access Control
- [ ] Cryptographic Practices
- [ ] Error Handling and Logging
- [ ] Data Protection
- [ ] Communication Security
- [ ] System Configuration
- [ ] Database Security
- [ ] File Management
- [ ] Memory Management
- [ ] General Coding Practices

### CODE REVIEW

**Review by thearifismail — APPROVED** [review]
LGTM

**Review by kruai — APPROVED** [review]

**Comment by fstavela** [comment]
/retest

There was a deployment issue

**Pull request merged**
