### PR TITLE
Add custom staleness feature at organization level

### PR DESCRIPTION
**Pull request by jpramos123**
# Overview

This PR is being created to address the following:
[ESSNTL-5050](https://issues.redhat.com/browse/ESSNTL-5050)
[ESSNTL-5051](https://issues.redhat.com/browse/ESSNTL-5051)
[ESSNTL-5215](https://issues.redhat.com/browse/ESSNTL-5215)
[ESSNTL-5036](https://issues.redhat.com/browse/ESSNTL-5036)

This PR has a lot of changes, please review it carefully!

It changes the way inventory builds its GraphQL queries to handle immutable (host_type == 'edge') and conventional (host_type == None) hosts, with their new fresh, stale, stale_warning and deletion timestamps.
The same changes applies to the SQLAlchemy queries we do to the PostgresDB.

It also changes the way the host_reaper handle the host's exclusion order. It first searches for the org_ids that have a custom staleness created the in DB, otherwise it uses the system default values.

Several changes were made to the tests in order to get it working just fine.

One file with new tests specifically to the custom staleness was added as well.

## PR Checklist

- [ ] Keep PR title short, ideally under 72 characters
- [ ] Descriptive comments provided in complex code blocks
- [ ] Tests: validate optimal/expected output
- [ ] Tests: validate exceptions and failure scenarios
- [ ] Tests: edge cases
- [ ] Recovers or fails gracefully during potential resource outages (e.g. DB, Kafka)
- [ ] Uses [type hinting](https://docs.python.org/3/library/typing.html), if convenient
- [ ] Documentation, if this PR changes the way other services interact with host inventory
- [ ] Links to related PRs

## Secure Coding Practices Documentation Reference

You can find documentation on this checklist [here](https://github.com/RedHatInsights/secure-coding-checklist).

## Secure Coding Checklist

- [ ] Input Validation
- [ ] Output Encoding
- [ ] Authentication and Password Management
- [ ] Session Management
- [ ] Access Control
- [ ] Cryptographic Practices
- [ ] Error Handling and Logging
- [ ] Data Protection
- [ ] Communication Security
- [ ] System Configuration
- [ ] Database Security
- [ ] File Management
- [ ] Memory Management
- [ ] General Coding Practices

### CODE REVIEW

**Comment by thearifismail** [comment]
what is the diffferenc between this and PR #1516?

**Comment by thearifismail** [comment]
what is the diffference between this and PR #1516?

**Comment by jpramos123** [comment]
> what is the diffference between this and PR #1516?

The only thing is a issue @kruai found when it was merge that is already being covered.

Other than that, nothing changed.

**Review by thearifismail — APPROVED** [review]
LGTM

**Pull request merged**
