### PR TITLE
remove rhel_machine_id and references from HBI code

### PR DESCRIPTION
**Pull request by thearifismail**
# Overview

This PR is being created to address [this Jira](https://issues.redhat.com/browse/ESSNTL-1003).

## PR Checklist

- [x] Keep PR title short, ideally under 72 characters
- [ ] Descriptive comments provided in complex code blocks
- [ ] Tests: validate optimal/expected output
- [ ] Tests: validate exceptions and failure scenarios
- [ ] Tests: edge cases
- [ ] Documentation, if this PR changes the way other services interact with host inventory
- [ ] Links to related PRs

## Secure Coding Practices Documentation Reference

You can find documentation on this checklist [here](https://github.com/RedHatInsights/secure-coding-checklist).

## Secure Coding Checklist

- [ ] Input Validation
- [ ] Output Encoding
- [ ] Authentication and Password Management
- [ ] Session Management
- [ ] Access Control
- [ ] Cryptographic Practices
- [ ] Error Handling and Logging
- [ ] Data Protection
- [ ] Communication Security
- [ ] System Configuration
- [ ] Database Security
- [ ] File Management
- [ ] Memory Management
- [ ] General Coding Practices

### CODE REVIEW

**Review by kruai — CHANGES_REQUESTED** [review]
The RhelMachineId definition should also be removed, since it's no longer used: https://github.com/RedHatInsights/insights-host-inventory/blob/ec5fd00e128ac57500272696e394d3bd5c567caf/swagger/api.spec.yaml#L756

**Comment by thearifismail** [comment]
> The RhelMachineId definition should also be removed, since it's no longer used:
> 
> https://github.com/RedHatInsights/insights-host-inventory/blob/ec5fd00e128ac57500272696e394d3bd5c567caf/swagger/api.spec.yaml#L756

Good catch and gone!

**Review by kruai — APPROVED** [review]
Sweet

**Review by ryandillinfelton — APPROVED** [review]
LGTM

**Pull request merged**
