### PR TITLE
feat(RHINENG-5892) Re-allow "unknown" value for staleness filter

### PR DESCRIPTION
**Pull request by kruai**
# Overview

This PR is being created to address [RHINENG-5892](https://issues.redhat.com/browse/RHINENG-5892).
#1569 removed the "unknown" staleness filter value; we made sure UIs weren't explicitly sending this value, but it turns out that the ansible-collections-insights Inventory plugin was still sending it, so it broke. I opened [CCT-196](https://issues.redhat.com/browse/CCT-196) requesting that they stop sending that value (and explicit values for that filter in general), and we'll remove the value ([RHINENG-5893](https://issues.redhat.com/browse/RHINENG-5893)) after that goes in.

## PR Checklist

- [x] Keep PR title short, ideally under 72 characters
- [ ] Descriptive comments provided in complex code blocks
- [x] Tests: validate optimal/expected output
- [ ] Tests: validate exceptions and failure scenarios
- [ ] Tests: edge cases
- [ ] Recovers or fails gracefully during potential resource outages (e.g. DB, Kafka)
- [ ] Uses [type hinting](https://docs.python.org/3/library/typing.html), if convenient
- [ ] Documentation, if this PR changes the way other services interact with host inventory
- [x] Links to related PRs

## Secure Coding Practices Documentation Reference

You can find documentation on this checklist [here](https://github.com/RedHatInsights/secure-coding-checklist).

## Secure Coding Checklist

- [ ] Input Validation
- [ ] Output Encoding
- [ ] Authentication and Password Management
- [ ] Session Management
- [ ] Access Control
- [ ] Cryptographic Practices
- [ ] Error Handling and Logging
- [ ] Data Protection
- [ ] Communication Security
- [ ] System Configuration
- [ ] Database Security
- [ ] File Management
- [ ] Memory Management
- [ ] General Coding Practices

### CODE REVIEW

**Review by thearifismail — APPROVED** [review]
LGTM

**Review by fellipeh — APPROVED** [review]

**Comment by kruai** [comment]
The only failing IQE test is `test_access_host_from_another_account`, and it seems inconsistent... last time it ran, it failed on 3 scenarios, and this time it only failed on 1. It's also not due to the urllib error, so it's unclear to me what's causing this yet

**Pull request merged**
