### PR TITLE
Add all packages not in installed_packages

### PR DESCRIPTION
**Pull request by CodeHeeler**
A way to have all packages passed along and not only the max of multi values provided by installed_packages without breaking those dependent on the current implementation of installed_packages.

Dependent on:
https://github.com/RedHatInsights/insights-puptoo/pull/69

### CODE REVIEW

**Review by kruai — APPROVED** [review]
This looks fine to me, though I wonder if we could define a regex "pattern" for both this field and `installed_packages`... Even something really loose like `^.+:.+$`, just to make sure it's using the right format. That makes the assumption that all packages follow the format shown in the "example" field, though

**Comment by CodeHeeler** [comment]
> This looks fine to me, though I wonder if we could define a regex "pattern" for both this field and `installed_packages`... Even something really loose like `^.+:.+$`, just to make sure it's using the right format. That makes the assumption that all packages follow the format shown in the "example" field, though

Created an issue to track this works separately as we'll want to be careful with changes effecting installed_packages.
https://issues.redhat.com/browse/HBISPSC-27

Let's leave this PR as is.  Thanks for the suggestion though!

**Comment by kruai** [comment]
I appreciate you creating a ticket to track that. This PR looks good to me besides that.

**Comment by CodeHeeler** [comment]
Updated the name to installed_packages_delta as per today's discussion.

**Review by kruai — APPROVED** [review]

**Review by thearifismail — APPROVED** [review]
LGTM

**Review by ryandillinfelton — APPROVED** [review]

**Pull request merged**
